/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "antiklepto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment, shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment, AUTO)


PB_BIND(shiftcrypto_bitbox02_AntiKleptoSignerCommitment, shiftcrypto_bitbox02_AntiKleptoSignerCommitment, AUTO)


PB_BIND(shiftcrypto_bitbox02_AntiKleptoSignatureRequest, shiftcrypto_bitbox02_AntiKleptoSignatureRequest, AUTO)



