/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SHIFTCRYPTO_BITBOX02_ANTIKLEPTO_PB_H_INCLUDED
#define PB_SHIFTCRYPTO_BITBOX02_ANTIKLEPTO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(32) shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_commitment_t;
typedef struct _shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment {
    shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_commitment_t commitment;
} shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment;

typedef PB_BYTES_ARRAY_T(33) shiftcrypto_bitbox02_AntiKleptoSignerCommitment_commitment_t;
typedef struct _shiftcrypto_bitbox02_AntiKleptoSignerCommitment {
    shiftcrypto_bitbox02_AntiKleptoSignerCommitment_commitment_t commitment;
} shiftcrypto_bitbox02_AntiKleptoSignerCommitment;

typedef PB_BYTES_ARRAY_T(32) shiftcrypto_bitbox02_AntiKleptoSignatureRequest_host_nonce_t;
typedef struct _shiftcrypto_bitbox02_AntiKleptoSignatureRequest {
    shiftcrypto_bitbox02_AntiKleptoSignatureRequest_host_nonce_t host_nonce;
} shiftcrypto_bitbox02_AntiKleptoSignatureRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_init_default {{0, {0}}}
#define shiftcrypto_bitbox02_AntiKleptoSignerCommitment_init_default {{0, {0}}}
#define shiftcrypto_bitbox02_AntiKleptoSignatureRequest_init_default {{0, {0}}}
#define shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_init_zero {{0, {0}}}
#define shiftcrypto_bitbox02_AntiKleptoSignerCommitment_init_zero {{0, {0}}}
#define shiftcrypto_bitbox02_AntiKleptoSignatureRequest_init_zero {{0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_commitment_tag 1
#define shiftcrypto_bitbox02_AntiKleptoSignerCommitment_commitment_tag 1
#define shiftcrypto_bitbox02_AntiKleptoSignatureRequest_host_nonce_tag 1

/* Struct field encoding specification for nanopb */
#define shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    commitment,        1)
#define shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_CALLBACK NULL
#define shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_DEFAULT NULL

#define shiftcrypto_bitbox02_AntiKleptoSignerCommitment_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    commitment,        1)
#define shiftcrypto_bitbox02_AntiKleptoSignerCommitment_CALLBACK NULL
#define shiftcrypto_bitbox02_AntiKleptoSignerCommitment_DEFAULT NULL

#define shiftcrypto_bitbox02_AntiKleptoSignatureRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    host_nonce,        1)
#define shiftcrypto_bitbox02_AntiKleptoSignatureRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_AntiKleptoSignatureRequest_DEFAULT NULL

extern const pb_msgdesc_t shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_AntiKleptoSignerCommitment_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_AntiKleptoSignatureRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_fields &shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_msg
#define shiftcrypto_bitbox02_AntiKleptoSignerCommitment_fields &shiftcrypto_bitbox02_AntiKleptoSignerCommitment_msg
#define shiftcrypto_bitbox02_AntiKleptoSignatureRequest_fields &shiftcrypto_bitbox02_AntiKleptoSignatureRequest_msg

/* Maximum encoded size of messages (where known) */
#define SHIFTCRYPTO_BITBOX02_ANTIKLEPTO_PB_H_MAX_SIZE shiftcrypto_bitbox02_AntiKleptoSignerCommitment_size
#define shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_size 34
#define shiftcrypto_bitbox02_AntiKleptoSignatureRequest_size 34
#define shiftcrypto_bitbox02_AntiKleptoSignerCommitment_size 35

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
