/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "backup_commands.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(shiftcrypto_bitbox02_CheckBackupRequest, shiftcrypto_bitbox02_CheckBackupRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_CheckBackupResponse, shiftcrypto_bitbox02_CheckBackupResponse, AUTO)


PB_BIND(shiftcrypto_bitbox02_CreateBackupRequest, shiftcrypto_bitbox02_CreateBackupRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_ListBackupsRequest, shiftcrypto_bitbox02_ListBackupsRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_BackupInfo, shiftcrypto_bitbox02_BackupInfo, AUTO)


PB_BIND(shiftcrypto_bitbox02_ListBackupsResponse, shiftcrypto_bitbox02_ListBackupsResponse, 4)


PB_BIND(shiftcrypto_bitbox02_RestoreBackupRequest, shiftcrypto_bitbox02_RestoreBackupRequest, AUTO)



