/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "bitbox02_system.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(shiftcrypto_bitbox02_CheckSDCardRequest, shiftcrypto_bitbox02_CheckSDCardRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_CheckSDCardResponse, shiftcrypto_bitbox02_CheckSDCardResponse, AUTO)


PB_BIND(shiftcrypto_bitbox02_DeviceInfoRequest, shiftcrypto_bitbox02_DeviceInfoRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_DeviceInfoResponse, shiftcrypto_bitbox02_DeviceInfoResponse, 2)


PB_BIND(shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth, shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth, AUTO)


PB_BIND(shiftcrypto_bitbox02_InsertRemoveSDCardRequest, shiftcrypto_bitbox02_InsertRemoveSDCardRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_ResetRequest, shiftcrypto_bitbox02_ResetRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_SetDeviceLanguageRequest, shiftcrypto_bitbox02_SetDeviceLanguageRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_SetDeviceNameRequest, shiftcrypto_bitbox02_SetDeviceNameRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_SetPasswordRequest, shiftcrypto_bitbox02_SetPasswordRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_ChangePasswordRequest, shiftcrypto_bitbox02_ChangePasswordRequest, AUTO)





