/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SHIFTCRYPTO_BITBOX02_BITBOXSYNC_PB_H_INCLUDED
#define PB_SHIFTCRYPTO_BITBOX02_BITBOXSYNC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _shiftcrypto_bitbox02_BitBoxSyncIdentityRequest {
    char dummy_field;
} shiftcrypto_bitbox02_BitBoxSyncIdentityRequest;

typedef struct _shiftcrypto_bitbox02_BitBoxSyncIdentityResponse {
    pb_callback_t auth_public_key;
    pb_callback_t wrap_public_key;
} shiftcrypto_bitbox02_BitBoxSyncIdentityResponse;

typedef struct _shiftcrypto_bitbox02_BitBoxSyncSignLoginIntentRequest {
    pb_callback_t challenge;
} shiftcrypto_bitbox02_BitBoxSyncSignLoginIntentRequest;

typedef struct _shiftcrypto_bitbox02_BitBoxSyncSignRefreshIntentRequest {
    pb_callback_t challenge;
} shiftcrypto_bitbox02_BitBoxSyncSignRefreshIntentRequest;

typedef struct _shiftcrypto_bitbox02_BitBoxSyncSignRevokeAllTokensIntentRequest {
    pb_callback_t challenge;
} shiftcrypto_bitbox02_BitBoxSyncSignRevokeAllTokensIntentRequest;

typedef struct _shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest {
    pb_callback_t challenge;
    pb_callback_t namespace_id;
    pb_callback_t invite_id;
    pb_callback_t invite_server_secret_hash;
    uint64_t expires_at;
    uint32_t max_accepted;
} shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest;

typedef struct _shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest {
    pb_callback_t namespace_id;
    pb_callback_t invite_id;
    pb_callback_t server_origin;
    uint64_t expires_at;
} shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest;

typedef struct _shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKRequest {
    pb_callback_t namespace_id;
    pb_callback_t wrapped_dek;
} shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKRequest;

typedef struct _shiftcrypto_bitbox02_BitBoxSyncSignatureResponse {
    pb_callback_t signature;
} shiftcrypto_bitbox02_BitBoxSyncSignatureResponse;

typedef struct _shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKResponse {
    pb_callback_t namespace_dek;
} shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKResponse;

typedef struct _shiftcrypto_bitbox02_BitBoxSyncRequest {
    pb_size_t which_request;
    union {
        shiftcrypto_bitbox02_BitBoxSyncIdentityRequest identity;
        shiftcrypto_bitbox02_BitBoxSyncSignLoginIntentRequest sign_login_intent;
        shiftcrypto_bitbox02_BitBoxSyncSignRefreshIntentRequest sign_refresh_intent;
        shiftcrypto_bitbox02_BitBoxSyncSignRevokeAllTokensIntentRequest sign_revoke_all_tokens_intent;
        shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest sign_create_namespace_invite_intent;
        shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest sign_join_request_intent;
        shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKRequest unwrap_namespace_dek;
    } request;
} shiftcrypto_bitbox02_BitBoxSyncRequest;

typedef struct _shiftcrypto_bitbox02_BitBoxSyncResponse {
    pb_size_t which_response;
    union {
        shiftcrypto_bitbox02_BitBoxSyncIdentityResponse identity;
        shiftcrypto_bitbox02_BitBoxSyncSignatureResponse signature;
        shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKResponse unwrap_namespace_dek;
    } response;
} shiftcrypto_bitbox02_BitBoxSyncResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define shiftcrypto_bitbox02_BitBoxSyncIdentityRequest_init_default {0}
#define shiftcrypto_bitbox02_BitBoxSyncIdentityResponse_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_BitBoxSyncSignLoginIntentRequest_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BitBoxSyncSignRefreshIntentRequest_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BitBoxSyncSignRevokeAllTokensIntentRequest_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_BitBoxSyncSignatureResponse_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKResponse_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BitBoxSyncRequest_init_default {0, {shiftcrypto_bitbox02_BitBoxSyncIdentityRequest_init_default}}
#define shiftcrypto_bitbox02_BitBoxSyncResponse_init_default {0, {shiftcrypto_bitbox02_BitBoxSyncIdentityResponse_init_default}}
#define shiftcrypto_bitbox02_BitBoxSyncIdentityRequest_init_zero {0}
#define shiftcrypto_bitbox02_BitBoxSyncIdentityResponse_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_BitBoxSyncSignLoginIntentRequest_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BitBoxSyncSignRefreshIntentRequest_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BitBoxSyncSignRevokeAllTokensIntentRequest_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_BitBoxSyncSignatureResponse_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKResponse_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BitBoxSyncRequest_init_zero {0, {shiftcrypto_bitbox02_BitBoxSyncIdentityRequest_init_zero}}
#define shiftcrypto_bitbox02_BitBoxSyncResponse_init_zero {0, {shiftcrypto_bitbox02_BitBoxSyncIdentityResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define shiftcrypto_bitbox02_BitBoxSyncIdentityResponse_auth_public_key_tag 1
#define shiftcrypto_bitbox02_BitBoxSyncIdentityResponse_wrap_public_key_tag 2
#define shiftcrypto_bitbox02_BitBoxSyncSignLoginIntentRequest_challenge_tag 1
#define shiftcrypto_bitbox02_BitBoxSyncSignRefreshIntentRequest_challenge_tag 1
#define shiftcrypto_bitbox02_BitBoxSyncSignRevokeAllTokensIntentRequest_challenge_tag 1
#define shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest_challenge_tag 1
#define shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest_namespace_id_tag 2
#define shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest_invite_id_tag 3
#define shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest_invite_server_secret_hash_tag 4
#define shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest_expires_at_tag 5
#define shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest_max_accepted_tag 6
#define shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest_namespace_id_tag 1
#define shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest_invite_id_tag 2
#define shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest_server_origin_tag 3
#define shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest_expires_at_tag 4
#define shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKRequest_namespace_id_tag 1
#define shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKRequest_wrapped_dek_tag 2
#define shiftcrypto_bitbox02_BitBoxSyncSignatureResponse_signature_tag 1
#define shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKResponse_namespace_dek_tag 1
#define shiftcrypto_bitbox02_BitBoxSyncRequest_identity_tag 1
#define shiftcrypto_bitbox02_BitBoxSyncRequest_sign_login_intent_tag 2
#define shiftcrypto_bitbox02_BitBoxSyncRequest_sign_refresh_intent_tag 3
#define shiftcrypto_bitbox02_BitBoxSyncRequest_sign_revoke_all_tokens_intent_tag 4
#define shiftcrypto_bitbox02_BitBoxSyncRequest_sign_create_namespace_invite_intent_tag 5
#define shiftcrypto_bitbox02_BitBoxSyncRequest_sign_join_request_intent_tag 6
#define shiftcrypto_bitbox02_BitBoxSyncRequest_unwrap_namespace_dek_tag 7
#define shiftcrypto_bitbox02_BitBoxSyncResponse_identity_tag 1
#define shiftcrypto_bitbox02_BitBoxSyncResponse_signature_tag 2
#define shiftcrypto_bitbox02_BitBoxSyncResponse_unwrap_namespace_dek_tag 3

/* Struct field encoding specification for nanopb */
#define shiftcrypto_bitbox02_BitBoxSyncIdentityRequest_FIELDLIST(X, a) \

#define shiftcrypto_bitbox02_BitBoxSyncIdentityRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_BitBoxSyncIdentityRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_BitBoxSyncIdentityResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    auth_public_key,   1) \
X(a, CALLBACK, SINGULAR, BYTES,    wrap_public_key,   2)
#define shiftcrypto_bitbox02_BitBoxSyncIdentityResponse_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BitBoxSyncIdentityResponse_DEFAULT NULL

#define shiftcrypto_bitbox02_BitBoxSyncSignLoginIntentRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    challenge,         1)
#define shiftcrypto_bitbox02_BitBoxSyncSignLoginIntentRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BitBoxSyncSignLoginIntentRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_BitBoxSyncSignRefreshIntentRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    challenge,         1)
#define shiftcrypto_bitbox02_BitBoxSyncSignRefreshIntentRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BitBoxSyncSignRefreshIntentRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_BitBoxSyncSignRevokeAllTokensIntentRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    challenge,         1)
#define shiftcrypto_bitbox02_BitBoxSyncSignRevokeAllTokensIntentRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BitBoxSyncSignRevokeAllTokensIntentRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    challenge,         1) \
X(a, CALLBACK, SINGULAR, BYTES,    namespace_id,      2) \
X(a, CALLBACK, SINGULAR, BYTES,    invite_id,         3) \
X(a, CALLBACK, SINGULAR, BYTES,    invite_server_secret_hash,   4) \
X(a, STATIC,   SINGULAR, UINT64,   expires_at,        5) \
X(a, STATIC,   SINGULAR, UINT32,   max_accepted,      6)
#define shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    namespace_id,      1) \
X(a, CALLBACK, SINGULAR, BYTES,    invite_id,         2) \
X(a, CALLBACK, SINGULAR, STRING,   server_origin,     3) \
X(a, STATIC,   SINGULAR, UINT64,   expires_at,        4)
#define shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    namespace_id,      1) \
X(a, CALLBACK, SINGULAR, BYTES,    wrapped_dek,       2)
#define shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_BitBoxSyncSignatureResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    signature,         1)
#define shiftcrypto_bitbox02_BitBoxSyncSignatureResponse_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BitBoxSyncSignatureResponse_DEFAULT NULL

#define shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    namespace_dek,     1)
#define shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKResponse_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKResponse_DEFAULT NULL

#define shiftcrypto_bitbox02_BitBoxSyncRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,identity,request.identity),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,sign_login_intent,request.sign_login_intent),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,sign_refresh_intent,request.sign_refresh_intent),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,sign_revoke_all_tokens_intent,request.sign_revoke_all_tokens_intent),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,sign_create_namespace_invite_intent,request.sign_create_namespace_invite_intent),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,sign_join_request_intent,request.sign_join_request_intent),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,unwrap_namespace_dek,request.unwrap_namespace_dek),   7)
#define shiftcrypto_bitbox02_BitBoxSyncRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_BitBoxSyncRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_BitBoxSyncRequest_request_identity_MSGTYPE shiftcrypto_bitbox02_BitBoxSyncIdentityRequest
#define shiftcrypto_bitbox02_BitBoxSyncRequest_request_sign_login_intent_MSGTYPE shiftcrypto_bitbox02_BitBoxSyncSignLoginIntentRequest
#define shiftcrypto_bitbox02_BitBoxSyncRequest_request_sign_refresh_intent_MSGTYPE shiftcrypto_bitbox02_BitBoxSyncSignRefreshIntentRequest
#define shiftcrypto_bitbox02_BitBoxSyncRequest_request_sign_revoke_all_tokens_intent_MSGTYPE shiftcrypto_bitbox02_BitBoxSyncSignRevokeAllTokensIntentRequest
#define shiftcrypto_bitbox02_BitBoxSyncRequest_request_sign_create_namespace_invite_intent_MSGTYPE shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest
#define shiftcrypto_bitbox02_BitBoxSyncRequest_request_sign_join_request_intent_MSGTYPE shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest
#define shiftcrypto_bitbox02_BitBoxSyncRequest_request_unwrap_namespace_dek_MSGTYPE shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKRequest

#define shiftcrypto_bitbox02_BitBoxSyncResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,identity,response.identity),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,signature,response.signature),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,unwrap_namespace_dek,response.unwrap_namespace_dek),   3)
#define shiftcrypto_bitbox02_BitBoxSyncResponse_CALLBACK NULL
#define shiftcrypto_bitbox02_BitBoxSyncResponse_DEFAULT NULL
#define shiftcrypto_bitbox02_BitBoxSyncResponse_response_identity_MSGTYPE shiftcrypto_bitbox02_BitBoxSyncIdentityResponse
#define shiftcrypto_bitbox02_BitBoxSyncResponse_response_signature_MSGTYPE shiftcrypto_bitbox02_BitBoxSyncSignatureResponse
#define shiftcrypto_bitbox02_BitBoxSyncResponse_response_unwrap_namespace_dek_MSGTYPE shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKResponse

extern const pb_msgdesc_t shiftcrypto_bitbox02_BitBoxSyncIdentityRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BitBoxSyncIdentityResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BitBoxSyncSignLoginIntentRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BitBoxSyncSignRefreshIntentRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BitBoxSyncSignRevokeAllTokensIntentRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BitBoxSyncSignatureResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BitBoxSyncRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BitBoxSyncResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define shiftcrypto_bitbox02_BitBoxSyncIdentityRequest_fields &shiftcrypto_bitbox02_BitBoxSyncIdentityRequest_msg
#define shiftcrypto_bitbox02_BitBoxSyncIdentityResponse_fields &shiftcrypto_bitbox02_BitBoxSyncIdentityResponse_msg
#define shiftcrypto_bitbox02_BitBoxSyncSignLoginIntentRequest_fields &shiftcrypto_bitbox02_BitBoxSyncSignLoginIntentRequest_msg
#define shiftcrypto_bitbox02_BitBoxSyncSignRefreshIntentRequest_fields &shiftcrypto_bitbox02_BitBoxSyncSignRefreshIntentRequest_msg
#define shiftcrypto_bitbox02_BitBoxSyncSignRevokeAllTokensIntentRequest_fields &shiftcrypto_bitbox02_BitBoxSyncSignRevokeAllTokensIntentRequest_msg
#define shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest_fields &shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest_msg
#define shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest_fields &shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest_msg
#define shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKRequest_fields &shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKRequest_msg
#define shiftcrypto_bitbox02_BitBoxSyncSignatureResponse_fields &shiftcrypto_bitbox02_BitBoxSyncSignatureResponse_msg
#define shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKResponse_fields &shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKResponse_msg
#define shiftcrypto_bitbox02_BitBoxSyncRequest_fields &shiftcrypto_bitbox02_BitBoxSyncRequest_msg
#define shiftcrypto_bitbox02_BitBoxSyncResponse_fields &shiftcrypto_bitbox02_BitBoxSyncResponse_msg

/* Maximum encoded size of messages (where known) */
/* shiftcrypto_bitbox02_BitBoxSyncIdentityResponse_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BitBoxSyncSignLoginIntentRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BitBoxSyncSignRefreshIntentRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BitBoxSyncSignRevokeAllTokensIntentRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BitBoxSyncSignCreateNamespaceInviteIntentRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BitBoxSyncSignJoinRequestIntentRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BitBoxSyncSignatureResponse_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BitBoxSyncUnwrapNamespaceDEKResponse_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BitBoxSyncRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BitBoxSyncResponse_size depends on runtime parameters */
#define SHIFTCRYPTO_BITBOX02_BITBOXSYNC_PB_H_MAX_SIZE shiftcrypto_bitbox02_BitBoxSyncIdentityRequest_size
#define shiftcrypto_bitbox02_BitBoxSyncIdentityRequest_size 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
