/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SHIFTCRYPTO_BITBOX02_BITBOX02_SYSTEM_PB_H_INCLUDED
#define PB_SHIFTCRYPTO_BITBOX02_BITBOX02_SYSTEM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _shiftcrypto_bitbox02_InsertRemoveSDCardRequest_SDCardAction {
    shiftcrypto_bitbox02_InsertRemoveSDCardRequest_SDCardAction_REMOVE_CARD = 0,
    shiftcrypto_bitbox02_InsertRemoveSDCardRequest_SDCardAction_INSERT_CARD = 1
} shiftcrypto_bitbox02_InsertRemoveSDCardRequest_SDCardAction;

/* Struct definitions */
typedef struct _shiftcrypto_bitbox02_CheckSDCardRequest {
    char dummy_field;
} shiftcrypto_bitbox02_CheckSDCardRequest;

typedef struct _shiftcrypto_bitbox02_CheckSDCardResponse {
    bool inserted;
} shiftcrypto_bitbox02_CheckSDCardResponse;

typedef struct _shiftcrypto_bitbox02_DeviceInfoRequest {
    char dummy_field;
} shiftcrypto_bitbox02_DeviceInfoRequest;

typedef PB_BYTES_ARRAY_T(32) shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth_firmware_hash_t;
typedef struct _shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth {
    /* Hash of the currently active Bluetooth firmware on the device. */
    shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth_firmware_hash_t firmware_hash;
    /* Firmware version, formated as an unsigned integer "1", "2", etc. */
    char firmware_version[33];
    /* True if Bluetooth is enabled */
    bool enabled;
} shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth;

typedef struct _shiftcrypto_bitbox02_DeviceInfoResponse {
    char name[65];
    bool initialized;
    char version[33];
    bool mnemonic_passphrase_enabled;
    uint32_t monotonic_increments_remaining;
    /* From v9.6.0: "ATECC608A" or "ATECC608B" or "OPTIGA_TRUST_M_V3". */
    char securechip_model[33];
    /* Only present in Bluetooth-enabled devices. */
    bool has_bluetooth;
    shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth bluetooth;
    /* From v9.25.0. This together with `securechip_model` determines the password stretching
 algorithm. */
    char password_stretching_algo[65];
} shiftcrypto_bitbox02_DeviceInfoResponse;

typedef struct _shiftcrypto_bitbox02_InsertRemoveSDCardRequest {
    shiftcrypto_bitbox02_InsertRemoveSDCardRequest_SDCardAction action;
} shiftcrypto_bitbox02_InsertRemoveSDCardRequest;

typedef struct _shiftcrypto_bitbox02_ResetRequest {
    char dummy_field;
} shiftcrypto_bitbox02_ResetRequest;

typedef struct _shiftcrypto_bitbox02_SetDeviceLanguageRequest {
    pb_callback_t language;
} shiftcrypto_bitbox02_SetDeviceLanguageRequest;

typedef struct _shiftcrypto_bitbox02_SetDeviceNameRequest {
    pb_callback_t name;
} shiftcrypto_bitbox02_SetDeviceNameRequest;

typedef struct _shiftcrypto_bitbox02_SetPasswordRequest {
    pb_callback_t entropy;
} shiftcrypto_bitbox02_SetPasswordRequest;

typedef struct _shiftcrypto_bitbox02_ChangePasswordRequest {
    char dummy_field;
} shiftcrypto_bitbox02_ChangePasswordRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _shiftcrypto_bitbox02_InsertRemoveSDCardRequest_SDCardAction_MIN shiftcrypto_bitbox02_InsertRemoveSDCardRequest_SDCardAction_REMOVE_CARD
#define _shiftcrypto_bitbox02_InsertRemoveSDCardRequest_SDCardAction_MAX shiftcrypto_bitbox02_InsertRemoveSDCardRequest_SDCardAction_INSERT_CARD
#define _shiftcrypto_bitbox02_InsertRemoveSDCardRequest_SDCardAction_ARRAYSIZE ((shiftcrypto_bitbox02_InsertRemoveSDCardRequest_SDCardAction)(shiftcrypto_bitbox02_InsertRemoveSDCardRequest_SDCardAction_INSERT_CARD+1))






#define shiftcrypto_bitbox02_InsertRemoveSDCardRequest_action_ENUMTYPE shiftcrypto_bitbox02_InsertRemoveSDCardRequest_SDCardAction







/* Initializer values for message structs */
#define shiftcrypto_bitbox02_CheckSDCardRequest_init_default {0}
#define shiftcrypto_bitbox02_CheckSDCardResponse_init_default {0}
#define shiftcrypto_bitbox02_DeviceInfoRequest_init_default {0}
#define shiftcrypto_bitbox02_DeviceInfoResponse_init_default {"", 0, "", 0, 0, "", false, shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth_init_default, ""}
#define shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth_init_default {{0, {0}}, "", 0}
#define shiftcrypto_bitbox02_InsertRemoveSDCardRequest_init_default {_shiftcrypto_bitbox02_InsertRemoveSDCardRequest_SDCardAction_MIN}
#define shiftcrypto_bitbox02_ResetRequest_init_default {0}
#define shiftcrypto_bitbox02_SetDeviceLanguageRequest_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_SetDeviceNameRequest_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_SetPasswordRequest_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_ChangePasswordRequest_init_default {0}
#define shiftcrypto_bitbox02_CheckSDCardRequest_init_zero {0}
#define shiftcrypto_bitbox02_CheckSDCardResponse_init_zero {0}
#define shiftcrypto_bitbox02_DeviceInfoRequest_init_zero {0}
#define shiftcrypto_bitbox02_DeviceInfoResponse_init_zero {"", 0, "", 0, 0, "", false, shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth_init_zero, ""}
#define shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth_init_zero {{0, {0}}, "", 0}
#define shiftcrypto_bitbox02_InsertRemoveSDCardRequest_init_zero {_shiftcrypto_bitbox02_InsertRemoveSDCardRequest_SDCardAction_MIN}
#define shiftcrypto_bitbox02_ResetRequest_init_zero {0}
#define shiftcrypto_bitbox02_SetDeviceLanguageRequest_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_SetDeviceNameRequest_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_SetPasswordRequest_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_ChangePasswordRequest_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define shiftcrypto_bitbox02_CheckSDCardResponse_inserted_tag 1
#define shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth_firmware_hash_tag 1
#define shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth_firmware_version_tag 2
#define shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth_enabled_tag 3
#define shiftcrypto_bitbox02_DeviceInfoResponse_name_tag 1
#define shiftcrypto_bitbox02_DeviceInfoResponse_initialized_tag 2
#define shiftcrypto_bitbox02_DeviceInfoResponse_version_tag 3
#define shiftcrypto_bitbox02_DeviceInfoResponse_mnemonic_passphrase_enabled_tag 4
#define shiftcrypto_bitbox02_DeviceInfoResponse_monotonic_increments_remaining_tag 5
#define shiftcrypto_bitbox02_DeviceInfoResponse_securechip_model_tag 6
#define shiftcrypto_bitbox02_DeviceInfoResponse_bluetooth_tag 7
#define shiftcrypto_bitbox02_DeviceInfoResponse_password_stretching_algo_tag 8
#define shiftcrypto_bitbox02_InsertRemoveSDCardRequest_action_tag 1
#define shiftcrypto_bitbox02_SetDeviceLanguageRequest_language_tag 1
#define shiftcrypto_bitbox02_SetDeviceNameRequest_name_tag 1
#define shiftcrypto_bitbox02_SetPasswordRequest_entropy_tag 1

/* Struct field encoding specification for nanopb */
#define shiftcrypto_bitbox02_CheckSDCardRequest_FIELDLIST(X, a) \

#define shiftcrypto_bitbox02_CheckSDCardRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_CheckSDCardRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_CheckSDCardResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     inserted,          1)
#define shiftcrypto_bitbox02_CheckSDCardResponse_CALLBACK NULL
#define shiftcrypto_bitbox02_CheckSDCardResponse_DEFAULT NULL

#define shiftcrypto_bitbox02_DeviceInfoRequest_FIELDLIST(X, a) \

#define shiftcrypto_bitbox02_DeviceInfoRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_DeviceInfoRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_DeviceInfoResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, BOOL,     initialized,       2) \
X(a, STATIC,   SINGULAR, STRING,   version,           3) \
X(a, STATIC,   SINGULAR, BOOL,     mnemonic_passphrase_enabled,   4) \
X(a, STATIC,   SINGULAR, UINT32,   monotonic_increments_remaining,   5) \
X(a, STATIC,   SINGULAR, STRING,   securechip_model,   6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bluetooth,         7) \
X(a, STATIC,   SINGULAR, STRING,   password_stretching_algo,   8)
#define shiftcrypto_bitbox02_DeviceInfoResponse_CALLBACK NULL
#define shiftcrypto_bitbox02_DeviceInfoResponse_DEFAULT NULL
#define shiftcrypto_bitbox02_DeviceInfoResponse_bluetooth_MSGTYPE shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth

#define shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    firmware_hash,     1) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   2) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           3)
#define shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth_CALLBACK NULL
#define shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth_DEFAULT NULL

#define shiftcrypto_bitbox02_InsertRemoveSDCardRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1)
#define shiftcrypto_bitbox02_InsertRemoveSDCardRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_InsertRemoveSDCardRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_ResetRequest_FIELDLIST(X, a) \

#define shiftcrypto_bitbox02_ResetRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_ResetRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_SetDeviceLanguageRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   language,          1)
#define shiftcrypto_bitbox02_SetDeviceLanguageRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_SetDeviceLanguageRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_SetDeviceNameRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1)
#define shiftcrypto_bitbox02_SetDeviceNameRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_SetDeviceNameRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_SetPasswordRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    entropy,           1)
#define shiftcrypto_bitbox02_SetPasswordRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_SetPasswordRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_ChangePasswordRequest_FIELDLIST(X, a) \

#define shiftcrypto_bitbox02_ChangePasswordRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_ChangePasswordRequest_DEFAULT NULL

extern const pb_msgdesc_t shiftcrypto_bitbox02_CheckSDCardRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CheckSDCardResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_DeviceInfoRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_DeviceInfoResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_InsertRemoveSDCardRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ResetRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_SetDeviceLanguageRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_SetDeviceNameRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_SetPasswordRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ChangePasswordRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define shiftcrypto_bitbox02_CheckSDCardRequest_fields &shiftcrypto_bitbox02_CheckSDCardRequest_msg
#define shiftcrypto_bitbox02_CheckSDCardResponse_fields &shiftcrypto_bitbox02_CheckSDCardResponse_msg
#define shiftcrypto_bitbox02_DeviceInfoRequest_fields &shiftcrypto_bitbox02_DeviceInfoRequest_msg
#define shiftcrypto_bitbox02_DeviceInfoResponse_fields &shiftcrypto_bitbox02_DeviceInfoResponse_msg
#define shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth_fields &shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth_msg
#define shiftcrypto_bitbox02_InsertRemoveSDCardRequest_fields &shiftcrypto_bitbox02_InsertRemoveSDCardRequest_msg
#define shiftcrypto_bitbox02_ResetRequest_fields &shiftcrypto_bitbox02_ResetRequest_msg
#define shiftcrypto_bitbox02_SetDeviceLanguageRequest_fields &shiftcrypto_bitbox02_SetDeviceLanguageRequest_msg
#define shiftcrypto_bitbox02_SetDeviceNameRequest_fields &shiftcrypto_bitbox02_SetDeviceNameRequest_msg
#define shiftcrypto_bitbox02_SetPasswordRequest_fields &shiftcrypto_bitbox02_SetPasswordRequest_msg
#define shiftcrypto_bitbox02_ChangePasswordRequest_fields &shiftcrypto_bitbox02_ChangePasswordRequest_msg

/* Maximum encoded size of messages (where known) */
/* shiftcrypto_bitbox02_SetDeviceLanguageRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_SetDeviceNameRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_SetPasswordRequest_size depends on runtime parameters */
#define SHIFTCRYPTO_BITBOX02_BITBOX02_SYSTEM_PB_H_MAX_SIZE shiftcrypto_bitbox02_DeviceInfoResponse_size
#define shiftcrypto_bitbox02_ChangePasswordRequest_size 0
#define shiftcrypto_bitbox02_CheckSDCardRequest_size 0
#define shiftcrypto_bitbox02_CheckSDCardResponse_size 2
#define shiftcrypto_bitbox02_DeviceInfoRequest_size 0
#define shiftcrypto_bitbox02_DeviceInfoResponse_Bluetooth_size 70
#define shiftcrypto_bitbox02_DeviceInfoResponse_size 282
#define shiftcrypto_bitbox02_InsertRemoveSDCardRequest_size 2
#define shiftcrypto_bitbox02_ResetRequest_size   0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
