/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "bluetooth.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(shiftcrypto_bitbox02_BluetoothToggleEnabledRequest, shiftcrypto_bitbox02_BluetoothToggleEnabledRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_BluetoothUpgradeInitRequest, shiftcrypto_bitbox02_BluetoothUpgradeInitRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_BluetoothChunkRequest, shiftcrypto_bitbox02_BluetoothChunkRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_BluetoothSuccess, shiftcrypto_bitbox02_BluetoothSuccess, AUTO)


PB_BIND(shiftcrypto_bitbox02_BluetoothRequestChunkResponse, shiftcrypto_bitbox02_BluetoothRequestChunkResponse, AUTO)


PB_BIND(shiftcrypto_bitbox02_BluetoothRequest, shiftcrypto_bitbox02_BluetoothRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_BluetoothResponse, shiftcrypto_bitbox02_BluetoothResponse, AUTO)



