/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SHIFTCRYPTO_BITBOX02_BLUETOOTH_PB_H_INCLUDED
#define PB_SHIFTCRYPTO_BITBOX02_BLUETOOTH_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _shiftcrypto_bitbox02_BluetoothToggleEnabledRequest {
    char dummy_field;
} shiftcrypto_bitbox02_BluetoothToggleEnabledRequest;

typedef struct _shiftcrypto_bitbox02_BluetoothUpgradeInitRequest {
    uint32_t firmware_length;
} shiftcrypto_bitbox02_BluetoothUpgradeInitRequest;

typedef struct _shiftcrypto_bitbox02_BluetoothChunkRequest {
    pb_callback_t data;
} shiftcrypto_bitbox02_BluetoothChunkRequest;

typedef struct _shiftcrypto_bitbox02_BluetoothSuccess {
    char dummy_field;
} shiftcrypto_bitbox02_BluetoothSuccess;

typedef struct _shiftcrypto_bitbox02_BluetoothRequestChunkResponse {
    uint32_t offset;
    uint32_t length;
} shiftcrypto_bitbox02_BluetoothRequestChunkResponse;

typedef struct _shiftcrypto_bitbox02_BluetoothRequest {
    pb_size_t which_request;
    union {
        shiftcrypto_bitbox02_BluetoothUpgradeInitRequest upgrade_init;
        shiftcrypto_bitbox02_BluetoothChunkRequest chunk;
        shiftcrypto_bitbox02_BluetoothToggleEnabledRequest toggle_enabled;
    } request;
} shiftcrypto_bitbox02_BluetoothRequest;

typedef struct _shiftcrypto_bitbox02_BluetoothResponse {
    pb_size_t which_response;
    union {
        shiftcrypto_bitbox02_BluetoothSuccess success;
        shiftcrypto_bitbox02_BluetoothRequestChunkResponse request_chunk;
    } response;
} shiftcrypto_bitbox02_BluetoothResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define shiftcrypto_bitbox02_BluetoothToggleEnabledRequest_init_default {0}
#define shiftcrypto_bitbox02_BluetoothUpgradeInitRequest_init_default {0}
#define shiftcrypto_bitbox02_BluetoothChunkRequest_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BluetoothSuccess_init_default {0}
#define shiftcrypto_bitbox02_BluetoothRequestChunkResponse_init_default {0, 0}
#define shiftcrypto_bitbox02_BluetoothRequest_init_default {0, {shiftcrypto_bitbox02_BluetoothUpgradeInitRequest_init_default}}
#define shiftcrypto_bitbox02_BluetoothResponse_init_default {0, {shiftcrypto_bitbox02_BluetoothSuccess_init_default}}
#define shiftcrypto_bitbox02_BluetoothToggleEnabledRequest_init_zero {0}
#define shiftcrypto_bitbox02_BluetoothUpgradeInitRequest_init_zero {0}
#define shiftcrypto_bitbox02_BluetoothChunkRequest_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BluetoothSuccess_init_zero {0}
#define shiftcrypto_bitbox02_BluetoothRequestChunkResponse_init_zero {0, 0}
#define shiftcrypto_bitbox02_BluetoothRequest_init_zero {0, {shiftcrypto_bitbox02_BluetoothUpgradeInitRequest_init_zero}}
#define shiftcrypto_bitbox02_BluetoothResponse_init_zero {0, {shiftcrypto_bitbox02_BluetoothSuccess_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define shiftcrypto_bitbox02_BluetoothUpgradeInitRequest_firmware_length_tag 1
#define shiftcrypto_bitbox02_BluetoothChunkRequest_data_tag 1
#define shiftcrypto_bitbox02_BluetoothRequestChunkResponse_offset_tag 1
#define shiftcrypto_bitbox02_BluetoothRequestChunkResponse_length_tag 2
#define shiftcrypto_bitbox02_BluetoothRequest_upgrade_init_tag 1
#define shiftcrypto_bitbox02_BluetoothRequest_chunk_tag 2
#define shiftcrypto_bitbox02_BluetoothRequest_toggle_enabled_tag 3
#define shiftcrypto_bitbox02_BluetoothResponse_success_tag 1
#define shiftcrypto_bitbox02_BluetoothResponse_request_chunk_tag 2

/* Struct field encoding specification for nanopb */
#define shiftcrypto_bitbox02_BluetoothToggleEnabledRequest_FIELDLIST(X, a) \

#define shiftcrypto_bitbox02_BluetoothToggleEnabledRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_BluetoothToggleEnabledRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_BluetoothUpgradeInitRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   firmware_length,   1)
#define shiftcrypto_bitbox02_BluetoothUpgradeInitRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_BluetoothUpgradeInitRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_BluetoothChunkRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              1)
#define shiftcrypto_bitbox02_BluetoothChunkRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BluetoothChunkRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_BluetoothSuccess_FIELDLIST(X, a) \

#define shiftcrypto_bitbox02_BluetoothSuccess_CALLBACK NULL
#define shiftcrypto_bitbox02_BluetoothSuccess_DEFAULT NULL

#define shiftcrypto_bitbox02_BluetoothRequestChunkResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            1) \
X(a, STATIC,   SINGULAR, UINT32,   length,            2)
#define shiftcrypto_bitbox02_BluetoothRequestChunkResponse_CALLBACK NULL
#define shiftcrypto_bitbox02_BluetoothRequestChunkResponse_DEFAULT NULL

#define shiftcrypto_bitbox02_BluetoothRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,upgrade_init,request.upgrade_init),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,chunk,request.chunk),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,toggle_enabled,request.toggle_enabled),   3)
#define shiftcrypto_bitbox02_BluetoothRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_BluetoothRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_BluetoothRequest_request_upgrade_init_MSGTYPE shiftcrypto_bitbox02_BluetoothUpgradeInitRequest
#define shiftcrypto_bitbox02_BluetoothRequest_request_chunk_MSGTYPE shiftcrypto_bitbox02_BluetoothChunkRequest
#define shiftcrypto_bitbox02_BluetoothRequest_request_toggle_enabled_MSGTYPE shiftcrypto_bitbox02_BluetoothToggleEnabledRequest

#define shiftcrypto_bitbox02_BluetoothResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,success,response.success),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,request_chunk,response.request_chunk),   2)
#define shiftcrypto_bitbox02_BluetoothResponse_CALLBACK NULL
#define shiftcrypto_bitbox02_BluetoothResponse_DEFAULT NULL
#define shiftcrypto_bitbox02_BluetoothResponse_response_success_MSGTYPE shiftcrypto_bitbox02_BluetoothSuccess
#define shiftcrypto_bitbox02_BluetoothResponse_response_request_chunk_MSGTYPE shiftcrypto_bitbox02_BluetoothRequestChunkResponse

extern const pb_msgdesc_t shiftcrypto_bitbox02_BluetoothToggleEnabledRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BluetoothUpgradeInitRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BluetoothChunkRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BluetoothSuccess_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BluetoothRequestChunkResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BluetoothRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BluetoothResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define shiftcrypto_bitbox02_BluetoothToggleEnabledRequest_fields &shiftcrypto_bitbox02_BluetoothToggleEnabledRequest_msg
#define shiftcrypto_bitbox02_BluetoothUpgradeInitRequest_fields &shiftcrypto_bitbox02_BluetoothUpgradeInitRequest_msg
#define shiftcrypto_bitbox02_BluetoothChunkRequest_fields &shiftcrypto_bitbox02_BluetoothChunkRequest_msg
#define shiftcrypto_bitbox02_BluetoothSuccess_fields &shiftcrypto_bitbox02_BluetoothSuccess_msg
#define shiftcrypto_bitbox02_BluetoothRequestChunkResponse_fields &shiftcrypto_bitbox02_BluetoothRequestChunkResponse_msg
#define shiftcrypto_bitbox02_BluetoothRequest_fields &shiftcrypto_bitbox02_BluetoothRequest_msg
#define shiftcrypto_bitbox02_BluetoothResponse_fields &shiftcrypto_bitbox02_BluetoothResponse_msg

/* Maximum encoded size of messages (where known) */
/* shiftcrypto_bitbox02_BluetoothChunkRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BluetoothRequest_size depends on runtime parameters */
#define SHIFTCRYPTO_BITBOX02_BLUETOOTH_PB_H_MAX_SIZE shiftcrypto_bitbox02_BluetoothResponse_size
#define shiftcrypto_bitbox02_BluetoothRequestChunkResponse_size 12
#define shiftcrypto_bitbox02_BluetoothResponse_size 14
#define shiftcrypto_bitbox02_BluetoothSuccess_size 0
#define shiftcrypto_bitbox02_BluetoothToggleEnabledRequest_size 0
#define shiftcrypto_bitbox02_BluetoothUpgradeInitRequest_size 6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
