/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SHIFTCRYPTO_BITBOX02_BTC_PB_H_INCLUDED
#define PB_SHIFTCRYPTO_BITBOX02_BTC_PB_H_INCLUDED
#include <pb.h>
#include "common.pb.h"
#include "antiklepto.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _shiftcrypto_bitbox02_BTCCoin {
    shiftcrypto_bitbox02_BTCCoin_BTC = 0,
    shiftcrypto_bitbox02_BTCCoin_TBTC = 1,
    shiftcrypto_bitbox02_BTCCoin_LTC = 2,
    shiftcrypto_bitbox02_BTCCoin_TLTC = 3,
    /* Regtest */
    shiftcrypto_bitbox02_BTCCoin_RBTC = 4
} shiftcrypto_bitbox02_BTCCoin;

typedef enum _shiftcrypto_bitbox02_BTCOutputType {
    shiftcrypto_bitbox02_BTCOutputType_UNKNOWN = 0,
    shiftcrypto_bitbox02_BTCOutputType_P2PKH = 1,
    shiftcrypto_bitbox02_BTCOutputType_P2SH = 2,
    shiftcrypto_bitbox02_BTCOutputType_P2WPKH = 3,
    shiftcrypto_bitbox02_BTCOutputType_P2WSH = 4,
    shiftcrypto_bitbox02_BTCOutputType_P2TR = 5,
    shiftcrypto_bitbox02_BTCOutputType_OP_RETURN = 6
} shiftcrypto_bitbox02_BTCOutputType;

/* SimpleType is a "simple" script: one public key, no additional inputs. */
typedef enum _shiftcrypto_bitbox02_BTCScriptConfig_SimpleType {
    shiftcrypto_bitbox02_BTCScriptConfig_SimpleType_P2WPKH_P2SH = 0,
    shiftcrypto_bitbox02_BTCScriptConfig_SimpleType_P2WPKH = 1,
    shiftcrypto_bitbox02_BTCScriptConfig_SimpleType_P2TR = 2
} shiftcrypto_bitbox02_BTCScriptConfig_SimpleType;

typedef enum _shiftcrypto_bitbox02_BTCScriptConfig_Multisig_ScriptType {
    shiftcrypto_bitbox02_BTCScriptConfig_Multisig_ScriptType_P2WSH = 0, /* native segwit v0 multisig (bech32 addresses) */
    shiftcrypto_bitbox02_BTCScriptConfig_Multisig_ScriptType_P2WSH_P2SH = 1 /* wrapped segwit for legacy address compatibility */
} shiftcrypto_bitbox02_BTCScriptConfig_Multisig_ScriptType;

typedef enum _shiftcrypto_bitbox02_BTCPubRequest_XPubType {
    shiftcrypto_bitbox02_BTCPubRequest_XPubType_TPUB = 0,
    shiftcrypto_bitbox02_BTCPubRequest_XPubType_XPUB = 1,
    shiftcrypto_bitbox02_BTCPubRequest_XPubType_YPUB = 2,
    shiftcrypto_bitbox02_BTCPubRequest_XPubType_ZPUB = 3, /* zpub */
    shiftcrypto_bitbox02_BTCPubRequest_XPubType_VPUB = 4, /* vpub */
    shiftcrypto_bitbox02_BTCPubRequest_XPubType_UPUB = 5,
    shiftcrypto_bitbox02_BTCPubRequest_XPubType_CAPITAL_VPUB = 6, /* Vpub */
    shiftcrypto_bitbox02_BTCPubRequest_XPubType_CAPITAL_ZPUB = 7, /* Zpub */
    shiftcrypto_bitbox02_BTCPubRequest_XPubType_CAPITAL_UPUB = 8, /* Upub */
    shiftcrypto_bitbox02_BTCPubRequest_XPubType_CAPITAL_YPUB = 9 /* Ypub */
} shiftcrypto_bitbox02_BTCPubRequest_XPubType;

typedef enum _shiftcrypto_bitbox02_BTCXpubsRequest_XPubType {
    shiftcrypto_bitbox02_BTCXpubsRequest_XPubType_UNKNOWN = 0,
    shiftcrypto_bitbox02_BTCXpubsRequest_XPubType_XPUB = 1,
    shiftcrypto_bitbox02_BTCXpubsRequest_XPubType_TPUB = 2
} shiftcrypto_bitbox02_BTCXpubsRequest_XPubType;

typedef enum _shiftcrypto_bitbox02_BTCSignInitRequest_FormatUnit {
    /* According to `coin` (BTC, LTC, etc.). */
    shiftcrypto_bitbox02_BTCSignInitRequest_FormatUnit_DEFAULT = 0,
    /* Only valid for BTC/TBTC, formats as "sat"/"tsat". */
    shiftcrypto_bitbox02_BTCSignInitRequest_FormatUnit_SAT = 1
} shiftcrypto_bitbox02_BTCSignInitRequest_FormatUnit;

typedef enum _shiftcrypto_bitbox02_BTCSignNextResponse_Type {
    shiftcrypto_bitbox02_BTCSignNextResponse_Type_INPUT = 0,
    shiftcrypto_bitbox02_BTCSignNextResponse_Type_OUTPUT = 1,
    shiftcrypto_bitbox02_BTCSignNextResponse_Type_DONE = 2,
    /* For the previous transaction at input `index`. */
    shiftcrypto_bitbox02_BTCSignNextResponse_Type_PREVTX_INIT = 3,
    shiftcrypto_bitbox02_BTCSignNextResponse_Type_PREVTX_INPUT = 4,
    shiftcrypto_bitbox02_BTCSignNextResponse_Type_PREVTX_OUTPUT = 5,
    shiftcrypto_bitbox02_BTCSignNextResponse_Type_HOST_NONCE = 6,
    shiftcrypto_bitbox02_BTCSignNextResponse_Type_PAYMENT_REQUEST = 7
} shiftcrypto_bitbox02_BTCSignNextResponse_Type;

typedef enum _shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_XPubType {
    /* Automatically choose to match Electrum's xpub format (e.g. Zpub/Vpub for p2wsh multisig mainnet/testnet). */
    shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_XPubType_AUTO_ELECTRUM = 0,
    /* Always xpub for mainnets, tpub for testnets. */
    shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_XPubType_AUTO_XPUB_TPUB = 1
} shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_XPubType;

/* Struct definitions */
typedef struct _shiftcrypto_bitbox02_BTCScriptConfig_Multisig {
    uint32_t threshold;
    /* xpubs are acount-level xpubs. Addresses are going to be derived from it using: `m/<change>/<receive>`.
 The number of xpubs defines the number of cosigners. */
    pb_callback_t xpubs;
    /* Index to the xpub of our keystore in xpubs. The keypath to it is provided via
 BTCPubRequest/BTCSignInit. */
    uint32_t our_xpub_index;
    shiftcrypto_bitbox02_BTCScriptConfig_Multisig_ScriptType script_type;
} shiftcrypto_bitbox02_BTCScriptConfig_Multisig;

/* A policy as specified by 'Wallet policies':
 https://github.com/bitcoin/bips/pull/1389 */
typedef struct _shiftcrypto_bitbox02_BTCScriptConfig_Policy {
    pb_callback_t policy;
    pb_callback_t keys;
} shiftcrypto_bitbox02_BTCScriptConfig_Policy;

typedef struct _shiftcrypto_bitbox02_BTCScriptConfig {
    pb_size_t which_config;
    union {
        shiftcrypto_bitbox02_BTCScriptConfig_SimpleType simple_type;
        shiftcrypto_bitbox02_BTCScriptConfig_Multisig multisig;
        shiftcrypto_bitbox02_BTCScriptConfig_Policy policy;
    } config;
} shiftcrypto_bitbox02_BTCScriptConfig;

typedef struct _shiftcrypto_bitbox02_BTCPubRequest {
    shiftcrypto_bitbox02_BTCCoin coin;
    pb_size_t keypath_count;
    uint32_t keypath[32];
    pb_size_t which_output;
    union {
        shiftcrypto_bitbox02_BTCPubRequest_XPubType xpub_type;
        shiftcrypto_bitbox02_BTCScriptConfig script_config;
    } output;
    bool display;
} shiftcrypto_bitbox02_BTCPubRequest;

typedef struct _shiftcrypto_bitbox02_BTCXpubsRequest {
    shiftcrypto_bitbox02_BTCCoin coin;
    shiftcrypto_bitbox02_BTCXpubsRequest_XPubType xpub_type;
    pb_callback_t keypaths;
} shiftcrypto_bitbox02_BTCXpubsRequest;

typedef struct _shiftcrypto_bitbox02_BTCScriptConfigWithKeypath {
    bool has_script_config;
    shiftcrypto_bitbox02_BTCScriptConfig script_config;
    pb_size_t keypath_count;
    uint32_t keypath[32];
} shiftcrypto_bitbox02_BTCScriptConfigWithKeypath;

typedef struct _shiftcrypto_bitbox02_BTCSignInitRequest {
    shiftcrypto_bitbox02_BTCCoin coin;
    /* used script configs in inputs and changes */
    pb_callback_t script_configs;
    uint32_t version; /* must be 1 or 2 */
    uint32_t num_inputs;
    uint32_t num_outputs;
    uint32_t locktime; /* must be <500000000 */
    shiftcrypto_bitbox02_BTCSignInitRequest_FormatUnit format_unit;
    bool contains_silent_payment_outputs;
    /* used script configs for outputs that send to an address of the same keystore, but not
 necessarily the same account (as defined by `script_configs` above). */
    pb_callback_t output_script_configs;
} shiftcrypto_bitbox02_BTCSignInitRequest;

typedef PB_BYTES_ARRAY_T(64) shiftcrypto_bitbox02_BTCSignNextResponse_signature_t;
typedef struct _shiftcrypto_bitbox02_BTCSignNextResponse {
    shiftcrypto_bitbox02_BTCSignNextResponse_Type type;
    /* index of the current input or output */
    uint32_t index;
    bool has_signature; /* only as a response to BTCSignInputRequest */
    /* 64 bytes (32 bytes big endian R, 32 bytes big endian S). Only if has_signature is true. */
    shiftcrypto_bitbox02_BTCSignNextResponse_signature_t signature;
    /* Previous tx's input/output index in case of PREV_INPUT or PREV_OUTPUT, for the input at `index`. */
    uint32_t prev_index;
    bool has_anti_klepto_signer_commitment;
    shiftcrypto_bitbox02_AntiKleptoSignerCommitment anti_klepto_signer_commitment;
    /* Generated output. The host *must* verify its correctness using `silent_payment_dleq_proof`. */
    pb_callback_t generated_output_pkscript;
    pb_callback_t silent_payment_dleq_proof;
} shiftcrypto_bitbox02_BTCSignNextResponse;

typedef PB_BYTES_ARRAY_T(32) shiftcrypto_bitbox02_BTCSignInputRequest_prevOutHash_t;
typedef struct _shiftcrypto_bitbox02_BTCSignInputRequest {
    shiftcrypto_bitbox02_BTCSignInputRequest_prevOutHash_t prevOutHash;
    uint32_t prevOutIndex;
    uint64_t prevOutValue;
    uint32_t sequence; /* must be 0xffffffff-2, 0xffffffff-1 or 0xffffffff */
    pb_size_t keypath_count;
    uint32_t keypath[32]; /* all inputs must be ours. */
    /* References a script config from BTCSignInitRequest */
    uint32_t script_config_index;
    bool has_host_nonce_commitment;
    shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment host_nonce_commitment;
} shiftcrypto_bitbox02_BTCSignInputRequest;

/* https://github.com/bitcoin/bips/blob/master/bip-0352.mediawiki */
typedef struct _shiftcrypto_bitbox02_BTCSignOutputRequest_SilentPayment {
    pb_callback_t address;
} shiftcrypto_bitbox02_BTCSignOutputRequest_SilentPayment;

typedef struct _shiftcrypto_bitbox02_BTCSignOutputRequest {
    bool ours;
    shiftcrypto_bitbox02_BTCOutputType type; /* if ours is false */
    /* 20 bytes for p2pkh, p2sh, pw2wpkh. 32 bytes for p2wsh. */
    uint64_t value;
    pb_callback_t payload; /* if ours is false. Renamed from `hash`. */
    pb_size_t keypath_count;
    uint32_t keypath[32]; /* if ours is true */
    /* If ours is true and `output_script_config_index` is absent. References a script config from
 BTCSignInitRequest. This allows change output identification and allows us to identify
 non-change outputs to the same account, so we can display this info to the user. */
    uint32_t script_config_index;
    bool has_payment_request_index;
    uint32_t payment_request_index;
    /* If provided, `type` and `payload` is ignored. The generated output pkScript is returned in
 BTCSignNextResponse. `contains_silent_payment_outputs` in the init request must be true. */
    bool has_silent_payment;
    shiftcrypto_bitbox02_BTCSignOutputRequest_SilentPayment silent_payment;
    /* If ours is true. If set, `script_config_index` is ignored. References an output script config
 from BTCSignInitRequest. This enables verification that an output belongs to the same keystore,
 even if it is from a different account than we spend from, allowing us to display this info to
 the user. */
    bool has_output_script_config_index;
    uint32_t output_script_config_index;
} shiftcrypto_bitbox02_BTCSignOutputRequest;

typedef struct _shiftcrypto_bitbox02_BTCScriptConfigRegistration {
    shiftcrypto_bitbox02_BTCCoin coin;
    bool has_script_config;
    shiftcrypto_bitbox02_BTCScriptConfig script_config;
    /* Unused for policy registrations. */
    pb_size_t keypath_count;
    uint32_t keypath[32];
} shiftcrypto_bitbox02_BTCScriptConfigRegistration;

typedef struct _shiftcrypto_bitbox02_BTCSuccess {
    char dummy_field;
} shiftcrypto_bitbox02_BTCSuccess;

typedef struct _shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest {
    bool has_registration;
    shiftcrypto_bitbox02_BTCScriptConfigRegistration registration;
} shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest;

typedef struct _shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredResponse {
    bool is_registered;
} shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredResponse;

typedef struct _shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest {
    bool has_registration;
    shiftcrypto_bitbox02_BTCScriptConfigRegistration registration;
    /* If empty, the name is entered on the device instead. */
    char name[31];
    shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_XPubType xpub_type;
} shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest;

typedef struct _shiftcrypto_bitbox02_BTCPrevTxInitRequest {
    uint32_t version;
    uint32_t num_inputs;
    uint32_t num_outputs;
    uint32_t locktime;
} shiftcrypto_bitbox02_BTCPrevTxInitRequest;

typedef PB_BYTES_ARRAY_T(32) shiftcrypto_bitbox02_BTCPrevTxInputRequest_prev_out_hash_t;
typedef struct _shiftcrypto_bitbox02_BTCPrevTxInputRequest {
    shiftcrypto_bitbox02_BTCPrevTxInputRequest_prev_out_hash_t prev_out_hash;
    uint32_t prev_out_index;
    pb_callback_t signature_script;
    uint32_t sequence;
} shiftcrypto_bitbox02_BTCPrevTxInputRequest;

typedef struct _shiftcrypto_bitbox02_BTCPrevTxOutputRequest {
    uint64_t value;
    pb_callback_t pubkey_script;
} shiftcrypto_bitbox02_BTCPrevTxOutputRequest;

typedef struct _shiftcrypto_bitbox02_BTCPaymentRequestRequest {
    pb_callback_t recipient_name;
    pb_callback_t memos;
    pb_callback_t nonce;
    uint64_t total_amount;
    pb_callback_t signature;
} shiftcrypto_bitbox02_BTCPaymentRequestRequest;

typedef struct _shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_TextMemo {
    pb_callback_t note;
} shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_TextMemo;

/* Derivation info for verifying address ownership.
 NOT part of the SLIP-24 sighash. */
typedef struct _shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_EthAddressDerivation {
    pb_callback_t keypath; /* Keypath to the address */
} shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_EthAddressDerivation;

typedef struct _shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_BtcAddressDerivation {
    /* Script config + keypath are needed to derive BTC/LTC-family addresses. */
    bool has_script_config;
    shiftcrypto_bitbox02_BTCScriptConfigWithKeypath script_config;
} shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_BtcAddressDerivation;

typedef struct _shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo {
    uint32_t coin_type; /* SLIP-44 coin type */
    pb_callback_t amount; /* Human-readable amount (e.g. "0.25 ETH") */
    pb_callback_t address; /* Address to send the purchased coins to */
    pb_size_t which_address_derivation;
    union {
        shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_EthAddressDerivation eth;
        shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_BtcAddressDerivation btc;
    } address_derivation;
} shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo;

typedef struct _shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo {
    pb_size_t which_memo;
    union {
        shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_TextMemo text_memo;
        shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo coin_purchase_memo;
    } memo;
} shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo;

typedef struct _shiftcrypto_bitbox02_BTCSignMessageRequest {
    shiftcrypto_bitbox02_BTCCoin coin;
    bool has_script_config;
    shiftcrypto_bitbox02_BTCScriptConfigWithKeypath script_config;
    pb_callback_t msg;
    bool has_host_nonce_commitment;
    shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment host_nonce_commitment;
} shiftcrypto_bitbox02_BTCSignMessageRequest;

typedef PB_BYTES_ARRAY_T(65) shiftcrypto_bitbox02_BTCSignMessageResponse_signature_t;
typedef struct _shiftcrypto_bitbox02_BTCSignMessageResponse {
    /* 65 bytes (32 bytes big endian R, 32 bytes big endian S, 1 recid). */
    shiftcrypto_bitbox02_BTCSignMessageResponse_signature_t signature;
} shiftcrypto_bitbox02_BTCSignMessageResponse;

typedef struct _shiftcrypto_bitbox02_BTCRequest {
    pb_size_t which_request;
    union {
        shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest is_script_config_registered;
        shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest register_script_config;
        shiftcrypto_bitbox02_BTCPrevTxInitRequest prevtx_init;
        shiftcrypto_bitbox02_BTCPrevTxInputRequest prevtx_input;
        shiftcrypto_bitbox02_BTCPrevTxOutputRequest prevtx_output;
        shiftcrypto_bitbox02_BTCSignMessageRequest sign_message;
        shiftcrypto_bitbox02_AntiKleptoSignatureRequest antiklepto_signature;
        shiftcrypto_bitbox02_BTCPaymentRequestRequest payment_request;
        shiftcrypto_bitbox02_BTCXpubsRequest xpubs;
    } request;
} shiftcrypto_bitbox02_BTCRequest;

typedef struct _shiftcrypto_bitbox02_BTCResponse {
    pb_size_t which_response;
    union {
        shiftcrypto_bitbox02_BTCSuccess success;
        shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredResponse is_script_config_registered;
        shiftcrypto_bitbox02_BTCSignNextResponse sign_next;
        shiftcrypto_bitbox02_BTCSignMessageResponse sign_message;
        shiftcrypto_bitbox02_AntiKleptoSignerCommitment antiklepto_signer_commitment;
        shiftcrypto_bitbox02_PubsResponse pubs;
    } response;
} shiftcrypto_bitbox02_BTCResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _shiftcrypto_bitbox02_BTCCoin_MIN shiftcrypto_bitbox02_BTCCoin_BTC
#define _shiftcrypto_bitbox02_BTCCoin_MAX shiftcrypto_bitbox02_BTCCoin_RBTC
#define _shiftcrypto_bitbox02_BTCCoin_ARRAYSIZE ((shiftcrypto_bitbox02_BTCCoin)(shiftcrypto_bitbox02_BTCCoin_RBTC+1))

#define _shiftcrypto_bitbox02_BTCOutputType_MIN shiftcrypto_bitbox02_BTCOutputType_UNKNOWN
#define _shiftcrypto_bitbox02_BTCOutputType_MAX shiftcrypto_bitbox02_BTCOutputType_OP_RETURN
#define _shiftcrypto_bitbox02_BTCOutputType_ARRAYSIZE ((shiftcrypto_bitbox02_BTCOutputType)(shiftcrypto_bitbox02_BTCOutputType_OP_RETURN+1))

#define _shiftcrypto_bitbox02_BTCScriptConfig_SimpleType_MIN shiftcrypto_bitbox02_BTCScriptConfig_SimpleType_P2WPKH_P2SH
#define _shiftcrypto_bitbox02_BTCScriptConfig_SimpleType_MAX shiftcrypto_bitbox02_BTCScriptConfig_SimpleType_P2TR
#define _shiftcrypto_bitbox02_BTCScriptConfig_SimpleType_ARRAYSIZE ((shiftcrypto_bitbox02_BTCScriptConfig_SimpleType)(shiftcrypto_bitbox02_BTCScriptConfig_SimpleType_P2TR+1))

#define _shiftcrypto_bitbox02_BTCScriptConfig_Multisig_ScriptType_MIN shiftcrypto_bitbox02_BTCScriptConfig_Multisig_ScriptType_P2WSH
#define _shiftcrypto_bitbox02_BTCScriptConfig_Multisig_ScriptType_MAX shiftcrypto_bitbox02_BTCScriptConfig_Multisig_ScriptType_P2WSH_P2SH
#define _shiftcrypto_bitbox02_BTCScriptConfig_Multisig_ScriptType_ARRAYSIZE ((shiftcrypto_bitbox02_BTCScriptConfig_Multisig_ScriptType)(shiftcrypto_bitbox02_BTCScriptConfig_Multisig_ScriptType_P2WSH_P2SH+1))

#define _shiftcrypto_bitbox02_BTCPubRequest_XPubType_MIN shiftcrypto_bitbox02_BTCPubRequest_XPubType_TPUB
#define _shiftcrypto_bitbox02_BTCPubRequest_XPubType_MAX shiftcrypto_bitbox02_BTCPubRequest_XPubType_CAPITAL_YPUB
#define _shiftcrypto_bitbox02_BTCPubRequest_XPubType_ARRAYSIZE ((shiftcrypto_bitbox02_BTCPubRequest_XPubType)(shiftcrypto_bitbox02_BTCPubRequest_XPubType_CAPITAL_YPUB+1))

#define _shiftcrypto_bitbox02_BTCXpubsRequest_XPubType_MIN shiftcrypto_bitbox02_BTCXpubsRequest_XPubType_UNKNOWN
#define _shiftcrypto_bitbox02_BTCXpubsRequest_XPubType_MAX shiftcrypto_bitbox02_BTCXpubsRequest_XPubType_TPUB
#define _shiftcrypto_bitbox02_BTCXpubsRequest_XPubType_ARRAYSIZE ((shiftcrypto_bitbox02_BTCXpubsRequest_XPubType)(shiftcrypto_bitbox02_BTCXpubsRequest_XPubType_TPUB+1))

#define _shiftcrypto_bitbox02_BTCSignInitRequest_FormatUnit_MIN shiftcrypto_bitbox02_BTCSignInitRequest_FormatUnit_DEFAULT
#define _shiftcrypto_bitbox02_BTCSignInitRequest_FormatUnit_MAX shiftcrypto_bitbox02_BTCSignInitRequest_FormatUnit_SAT
#define _shiftcrypto_bitbox02_BTCSignInitRequest_FormatUnit_ARRAYSIZE ((shiftcrypto_bitbox02_BTCSignInitRequest_FormatUnit)(shiftcrypto_bitbox02_BTCSignInitRequest_FormatUnit_SAT+1))

#define _shiftcrypto_bitbox02_BTCSignNextResponse_Type_MIN shiftcrypto_bitbox02_BTCSignNextResponse_Type_INPUT
#define _shiftcrypto_bitbox02_BTCSignNextResponse_Type_MAX shiftcrypto_bitbox02_BTCSignNextResponse_Type_PAYMENT_REQUEST
#define _shiftcrypto_bitbox02_BTCSignNextResponse_Type_ARRAYSIZE ((shiftcrypto_bitbox02_BTCSignNextResponse_Type)(shiftcrypto_bitbox02_BTCSignNextResponse_Type_PAYMENT_REQUEST+1))

#define _shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_XPubType_MIN shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_XPubType_AUTO_ELECTRUM
#define _shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_XPubType_MAX shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_XPubType_AUTO_XPUB_TPUB
#define _shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_XPubType_ARRAYSIZE ((shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_XPubType)(shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_XPubType_AUTO_XPUB_TPUB+1))

#define shiftcrypto_bitbox02_BTCScriptConfig_config_simple_type_ENUMTYPE shiftcrypto_bitbox02_BTCScriptConfig_SimpleType

#define shiftcrypto_bitbox02_BTCScriptConfig_Multisig_script_type_ENUMTYPE shiftcrypto_bitbox02_BTCScriptConfig_Multisig_ScriptType


#define shiftcrypto_bitbox02_BTCPubRequest_coin_ENUMTYPE shiftcrypto_bitbox02_BTCCoin
#define shiftcrypto_bitbox02_BTCPubRequest_output_xpub_type_ENUMTYPE shiftcrypto_bitbox02_BTCPubRequest_XPubType

#define shiftcrypto_bitbox02_BTCXpubsRequest_coin_ENUMTYPE shiftcrypto_bitbox02_BTCCoin
#define shiftcrypto_bitbox02_BTCXpubsRequest_xpub_type_ENUMTYPE shiftcrypto_bitbox02_BTCXpubsRequest_XPubType


#define shiftcrypto_bitbox02_BTCSignInitRequest_coin_ENUMTYPE shiftcrypto_bitbox02_BTCCoin
#define shiftcrypto_bitbox02_BTCSignInitRequest_format_unit_ENUMTYPE shiftcrypto_bitbox02_BTCSignInitRequest_FormatUnit

#define shiftcrypto_bitbox02_BTCSignNextResponse_type_ENUMTYPE shiftcrypto_bitbox02_BTCSignNextResponse_Type


#define shiftcrypto_bitbox02_BTCSignOutputRequest_type_ENUMTYPE shiftcrypto_bitbox02_BTCOutputType


#define shiftcrypto_bitbox02_BTCScriptConfigRegistration_coin_ENUMTYPE shiftcrypto_bitbox02_BTCCoin




#define shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_xpub_type_ENUMTYPE shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_XPubType










#define shiftcrypto_bitbox02_BTCSignMessageRequest_coin_ENUMTYPE shiftcrypto_bitbox02_BTCCoin





/* Initializer values for message structs */
#define shiftcrypto_bitbox02_BTCScriptConfig_init_default {0, {_shiftcrypto_bitbox02_BTCScriptConfig_SimpleType_MIN}}
#define shiftcrypto_bitbox02_BTCScriptConfig_Multisig_init_default {0, {{NULL}, NULL}, 0, _shiftcrypto_bitbox02_BTCScriptConfig_Multisig_ScriptType_MIN}
#define shiftcrypto_bitbox02_BTCScriptConfig_Policy_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCPubRequest_init_default {_shiftcrypto_bitbox02_BTCCoin_MIN, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {_shiftcrypto_bitbox02_BTCPubRequest_XPubType_MIN}, 0}
#define shiftcrypto_bitbox02_BTCXpubsRequest_init_default {_shiftcrypto_bitbox02_BTCCoin_MIN, _shiftcrypto_bitbox02_BTCXpubsRequest_XPubType_MIN, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCScriptConfigWithKeypath_init_default {false, shiftcrypto_bitbox02_BTCScriptConfig_init_default, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define shiftcrypto_bitbox02_BTCSignInitRequest_init_default {_shiftcrypto_bitbox02_BTCCoin_MIN, {{NULL}, NULL}, 0, 0, 0, 0, _shiftcrypto_bitbox02_BTCSignInitRequest_FormatUnit_MIN, 0, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCSignNextResponse_init_default {_shiftcrypto_bitbox02_BTCSignNextResponse_Type_MIN, 0, 0, {0, {0}}, 0, false, shiftcrypto_bitbox02_AntiKleptoSignerCommitment_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCSignInputRequest_init_default {{0, {0}}, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, false, shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_init_default}
#define shiftcrypto_bitbox02_BTCSignOutputRequest_init_default {0, _shiftcrypto_bitbox02_BTCOutputType_MIN, 0, {{NULL}, NULL}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, false, 0, false, shiftcrypto_bitbox02_BTCSignOutputRequest_SilentPayment_init_default, false, 0}
#define shiftcrypto_bitbox02_BTCSignOutputRequest_SilentPayment_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCScriptConfigRegistration_init_default {_shiftcrypto_bitbox02_BTCCoin_MIN, false, shiftcrypto_bitbox02_BTCScriptConfig_init_default, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define shiftcrypto_bitbox02_BTCSuccess_init_default {0}
#define shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest_init_default {false, shiftcrypto_bitbox02_BTCScriptConfigRegistration_init_default}
#define shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredResponse_init_default {0}
#define shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_init_default {false, shiftcrypto_bitbox02_BTCScriptConfigRegistration_init_default, "", _shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_XPubType_MIN}
#define shiftcrypto_bitbox02_BTCPrevTxInitRequest_init_default {0, 0, 0, 0}
#define shiftcrypto_bitbox02_BTCPrevTxInputRequest_init_default {{0, {0}}, 0, {{NULL}, NULL}, 0}
#define shiftcrypto_bitbox02_BTCPrevTxOutputRequest_init_default {0, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_init_default {0, {shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_TextMemo_init_default}}
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_TextMemo_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, {shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_EthAddressDerivation_init_default}}
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_EthAddressDerivation_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_BtcAddressDerivation_init_default {false, shiftcrypto_bitbox02_BTCScriptConfigWithKeypath_init_default}
#define shiftcrypto_bitbox02_BTCSignMessageRequest_init_default {_shiftcrypto_bitbox02_BTCCoin_MIN, false, shiftcrypto_bitbox02_BTCScriptConfigWithKeypath_init_default, {{NULL}, NULL}, false, shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_init_default}
#define shiftcrypto_bitbox02_BTCSignMessageResponse_init_default {{0, {0}}}
#define shiftcrypto_bitbox02_BTCRequest_init_default {0, {shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest_init_default}}
#define shiftcrypto_bitbox02_BTCResponse_init_default {0, {shiftcrypto_bitbox02_BTCSuccess_init_default}}
#define shiftcrypto_bitbox02_BTCScriptConfig_init_zero {0, {_shiftcrypto_bitbox02_BTCScriptConfig_SimpleType_MIN}}
#define shiftcrypto_bitbox02_BTCScriptConfig_Multisig_init_zero {0, {{NULL}, NULL}, 0, _shiftcrypto_bitbox02_BTCScriptConfig_Multisig_ScriptType_MIN}
#define shiftcrypto_bitbox02_BTCScriptConfig_Policy_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCPubRequest_init_zero {_shiftcrypto_bitbox02_BTCCoin_MIN, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {_shiftcrypto_bitbox02_BTCPubRequest_XPubType_MIN}, 0}
#define shiftcrypto_bitbox02_BTCXpubsRequest_init_zero {_shiftcrypto_bitbox02_BTCCoin_MIN, _shiftcrypto_bitbox02_BTCXpubsRequest_XPubType_MIN, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCScriptConfigWithKeypath_init_zero {false, shiftcrypto_bitbox02_BTCScriptConfig_init_zero, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define shiftcrypto_bitbox02_BTCSignInitRequest_init_zero {_shiftcrypto_bitbox02_BTCCoin_MIN, {{NULL}, NULL}, 0, 0, 0, 0, _shiftcrypto_bitbox02_BTCSignInitRequest_FormatUnit_MIN, 0, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCSignNextResponse_init_zero {_shiftcrypto_bitbox02_BTCSignNextResponse_Type_MIN, 0, 0, {0, {0}}, 0, false, shiftcrypto_bitbox02_AntiKleptoSignerCommitment_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCSignInputRequest_init_zero {{0, {0}}, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, false, shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_init_zero}
#define shiftcrypto_bitbox02_BTCSignOutputRequest_init_zero {0, _shiftcrypto_bitbox02_BTCOutputType_MIN, 0, {{NULL}, NULL}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, false, 0, false, shiftcrypto_bitbox02_BTCSignOutputRequest_SilentPayment_init_zero, false, 0}
#define shiftcrypto_bitbox02_BTCSignOutputRequest_SilentPayment_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCScriptConfigRegistration_init_zero {_shiftcrypto_bitbox02_BTCCoin_MIN, false, shiftcrypto_bitbox02_BTCScriptConfig_init_zero, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define shiftcrypto_bitbox02_BTCSuccess_init_zero {0}
#define shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest_init_zero {false, shiftcrypto_bitbox02_BTCScriptConfigRegistration_init_zero}
#define shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredResponse_init_zero {0}
#define shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_init_zero {false, shiftcrypto_bitbox02_BTCScriptConfigRegistration_init_zero, "", _shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_XPubType_MIN}
#define shiftcrypto_bitbox02_BTCPrevTxInitRequest_init_zero {0, 0, 0, 0}
#define shiftcrypto_bitbox02_BTCPrevTxInputRequest_init_zero {{0, {0}}, 0, {{NULL}, NULL}, 0}
#define shiftcrypto_bitbox02_BTCPrevTxOutputRequest_init_zero {0, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_init_zero {0, {shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_TextMemo_init_zero}}
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_TextMemo_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_init_zero {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, {shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_EthAddressDerivation_init_zero}}
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_EthAddressDerivation_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_BtcAddressDerivation_init_zero {false, shiftcrypto_bitbox02_BTCScriptConfigWithKeypath_init_zero}
#define shiftcrypto_bitbox02_BTCSignMessageRequest_init_zero {_shiftcrypto_bitbox02_BTCCoin_MIN, false, shiftcrypto_bitbox02_BTCScriptConfigWithKeypath_init_zero, {{NULL}, NULL}, false, shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_init_zero}
#define shiftcrypto_bitbox02_BTCSignMessageResponse_init_zero {{0, {0}}}
#define shiftcrypto_bitbox02_BTCRequest_init_zero {0, {shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest_init_zero}}
#define shiftcrypto_bitbox02_BTCResponse_init_zero {0, {shiftcrypto_bitbox02_BTCSuccess_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define shiftcrypto_bitbox02_BTCScriptConfig_Multisig_threshold_tag 1
#define shiftcrypto_bitbox02_BTCScriptConfig_Multisig_xpubs_tag 2
#define shiftcrypto_bitbox02_BTCScriptConfig_Multisig_our_xpub_index_tag 3
#define shiftcrypto_bitbox02_BTCScriptConfig_Multisig_script_type_tag 4
#define shiftcrypto_bitbox02_BTCScriptConfig_Policy_policy_tag 1
#define shiftcrypto_bitbox02_BTCScriptConfig_Policy_keys_tag 2
#define shiftcrypto_bitbox02_BTCScriptConfig_simple_type_tag 1
#define shiftcrypto_bitbox02_BTCScriptConfig_multisig_tag 2
#define shiftcrypto_bitbox02_BTCScriptConfig_policy_tag 3
#define shiftcrypto_bitbox02_BTCPubRequest_coin_tag 1
#define shiftcrypto_bitbox02_BTCPubRequest_keypath_tag 2
#define shiftcrypto_bitbox02_BTCPubRequest_xpub_type_tag 3
#define shiftcrypto_bitbox02_BTCPubRequest_script_config_tag 4
#define shiftcrypto_bitbox02_BTCPubRequest_display_tag 5
#define shiftcrypto_bitbox02_BTCXpubsRequest_coin_tag 1
#define shiftcrypto_bitbox02_BTCXpubsRequest_xpub_type_tag 2
#define shiftcrypto_bitbox02_BTCXpubsRequest_keypaths_tag 3
#define shiftcrypto_bitbox02_BTCScriptConfigWithKeypath_script_config_tag 2
#define shiftcrypto_bitbox02_BTCScriptConfigWithKeypath_keypath_tag 3
#define shiftcrypto_bitbox02_BTCSignInitRequest_coin_tag 1
#define shiftcrypto_bitbox02_BTCSignInitRequest_script_configs_tag 2
#define shiftcrypto_bitbox02_BTCSignInitRequest_version_tag 4
#define shiftcrypto_bitbox02_BTCSignInitRequest_num_inputs_tag 5
#define shiftcrypto_bitbox02_BTCSignInitRequest_num_outputs_tag 6
#define shiftcrypto_bitbox02_BTCSignInitRequest_locktime_tag 7
#define shiftcrypto_bitbox02_BTCSignInitRequest_format_unit_tag 8
#define shiftcrypto_bitbox02_BTCSignInitRequest_contains_silent_payment_outputs_tag 9
#define shiftcrypto_bitbox02_BTCSignInitRequest_output_script_configs_tag 10
#define shiftcrypto_bitbox02_BTCSignNextResponse_type_tag 1
#define shiftcrypto_bitbox02_BTCSignNextResponse_index_tag 2
#define shiftcrypto_bitbox02_BTCSignNextResponse_has_signature_tag 3
#define shiftcrypto_bitbox02_BTCSignNextResponse_signature_tag 4
#define shiftcrypto_bitbox02_BTCSignNextResponse_prev_index_tag 5
#define shiftcrypto_bitbox02_BTCSignNextResponse_anti_klepto_signer_commitment_tag 6
#define shiftcrypto_bitbox02_BTCSignNextResponse_generated_output_pkscript_tag 7
#define shiftcrypto_bitbox02_BTCSignNextResponse_silent_payment_dleq_proof_tag 8
#define shiftcrypto_bitbox02_BTCSignInputRequest_prevOutHash_tag 1
#define shiftcrypto_bitbox02_BTCSignInputRequest_prevOutIndex_tag 2
#define shiftcrypto_bitbox02_BTCSignInputRequest_prevOutValue_tag 3
#define shiftcrypto_bitbox02_BTCSignInputRequest_sequence_tag 4
#define shiftcrypto_bitbox02_BTCSignInputRequest_keypath_tag 6
#define shiftcrypto_bitbox02_BTCSignInputRequest_script_config_index_tag 7
#define shiftcrypto_bitbox02_BTCSignInputRequest_host_nonce_commitment_tag 8
#define shiftcrypto_bitbox02_BTCSignOutputRequest_SilentPayment_address_tag 1
#define shiftcrypto_bitbox02_BTCSignOutputRequest_ours_tag 1
#define shiftcrypto_bitbox02_BTCSignOutputRequest_type_tag 2
#define shiftcrypto_bitbox02_BTCSignOutputRequest_value_tag 3
#define shiftcrypto_bitbox02_BTCSignOutputRequest_payload_tag 4
#define shiftcrypto_bitbox02_BTCSignOutputRequest_keypath_tag 5
#define shiftcrypto_bitbox02_BTCSignOutputRequest_script_config_index_tag 6
#define shiftcrypto_bitbox02_BTCSignOutputRequest_payment_request_index_tag 7
#define shiftcrypto_bitbox02_BTCSignOutputRequest_silent_payment_tag 8
#define shiftcrypto_bitbox02_BTCSignOutputRequest_output_script_config_index_tag 9
#define shiftcrypto_bitbox02_BTCScriptConfigRegistration_coin_tag 1
#define shiftcrypto_bitbox02_BTCScriptConfigRegistration_script_config_tag 2
#define shiftcrypto_bitbox02_BTCScriptConfigRegistration_keypath_tag 3
#define shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest_registration_tag 1
#define shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredResponse_is_registered_tag 1
#define shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_registration_tag 1
#define shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_name_tag 2
#define shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_xpub_type_tag 3
#define shiftcrypto_bitbox02_BTCPrevTxInitRequest_version_tag 1
#define shiftcrypto_bitbox02_BTCPrevTxInitRequest_num_inputs_tag 2
#define shiftcrypto_bitbox02_BTCPrevTxInitRequest_num_outputs_tag 3
#define shiftcrypto_bitbox02_BTCPrevTxInitRequest_locktime_tag 4
#define shiftcrypto_bitbox02_BTCPrevTxInputRequest_prev_out_hash_tag 1
#define shiftcrypto_bitbox02_BTCPrevTxInputRequest_prev_out_index_tag 2
#define shiftcrypto_bitbox02_BTCPrevTxInputRequest_signature_script_tag 3
#define shiftcrypto_bitbox02_BTCPrevTxInputRequest_sequence_tag 4
#define shiftcrypto_bitbox02_BTCPrevTxOutputRequest_value_tag 1
#define shiftcrypto_bitbox02_BTCPrevTxOutputRequest_pubkey_script_tag 2
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_recipient_name_tag 1
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_memos_tag 2
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_nonce_tag 3
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_total_amount_tag 4
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_signature_tag 5
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_TextMemo_note_tag 1
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_EthAddressDerivation_keypath_tag 1
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_BtcAddressDerivation_script_config_tag 1
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_coin_type_tag 1
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_amount_tag 2
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_address_tag 3
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_eth_tag 4
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_btc_tag 5
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_text_memo_tag 1
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_coin_purchase_memo_tag 2
#define shiftcrypto_bitbox02_BTCSignMessageRequest_coin_tag 1
#define shiftcrypto_bitbox02_BTCSignMessageRequest_script_config_tag 2
#define shiftcrypto_bitbox02_BTCSignMessageRequest_msg_tag 3
#define shiftcrypto_bitbox02_BTCSignMessageRequest_host_nonce_commitment_tag 4
#define shiftcrypto_bitbox02_BTCSignMessageResponse_signature_tag 1
#define shiftcrypto_bitbox02_BTCRequest_is_script_config_registered_tag 1
#define shiftcrypto_bitbox02_BTCRequest_register_script_config_tag 2
#define shiftcrypto_bitbox02_BTCRequest_prevtx_init_tag 3
#define shiftcrypto_bitbox02_BTCRequest_prevtx_input_tag 4
#define shiftcrypto_bitbox02_BTCRequest_prevtx_output_tag 5
#define shiftcrypto_bitbox02_BTCRequest_sign_message_tag 6
#define shiftcrypto_bitbox02_BTCRequest_antiklepto_signature_tag 7
#define shiftcrypto_bitbox02_BTCRequest_payment_request_tag 8
#define shiftcrypto_bitbox02_BTCRequest_xpubs_tag 9
#define shiftcrypto_bitbox02_BTCResponse_success_tag 1
#define shiftcrypto_bitbox02_BTCResponse_is_script_config_registered_tag 2
#define shiftcrypto_bitbox02_BTCResponse_sign_next_tag 3
#define shiftcrypto_bitbox02_BTCResponse_sign_message_tag 4
#define shiftcrypto_bitbox02_BTCResponse_antiklepto_signer_commitment_tag 5
#define shiftcrypto_bitbox02_BTCResponse_pubs_tag 6

/* Struct field encoding specification for nanopb */
#define shiftcrypto_bitbox02_BTCScriptConfig_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UENUM,    (config,simple_type,config.simple_type),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config,multisig,config.multisig),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config,policy,config.policy),   3)
#define shiftcrypto_bitbox02_BTCScriptConfig_CALLBACK NULL
#define shiftcrypto_bitbox02_BTCScriptConfig_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCScriptConfig_config_multisig_MSGTYPE shiftcrypto_bitbox02_BTCScriptConfig_Multisig
#define shiftcrypto_bitbox02_BTCScriptConfig_config_policy_MSGTYPE shiftcrypto_bitbox02_BTCScriptConfig_Policy

#define shiftcrypto_bitbox02_BTCScriptConfig_Multisig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   threshold,         1) \
X(a, CALLBACK, REPEATED, MESSAGE,  xpubs,             2) \
X(a, STATIC,   SINGULAR, UINT32,   our_xpub_index,    3) \
X(a, STATIC,   SINGULAR, UENUM,    script_type,       4)
#define shiftcrypto_bitbox02_BTCScriptConfig_Multisig_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BTCScriptConfig_Multisig_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCScriptConfig_Multisig_xpubs_MSGTYPE shiftcrypto_bitbox02_XPub

#define shiftcrypto_bitbox02_BTCScriptConfig_Policy_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   policy,            1) \
X(a, CALLBACK, REPEATED, MESSAGE,  keys,              2)
#define shiftcrypto_bitbox02_BTCScriptConfig_Policy_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BTCScriptConfig_Policy_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCScriptConfig_Policy_keys_MSGTYPE shiftcrypto_bitbox02_KeyOriginInfo

#define shiftcrypto_bitbox02_BTCPubRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    coin,              1) \
X(a, STATIC,   REPEATED, UINT32,   keypath,           2) \
X(a, STATIC,   ONEOF,    UENUM,    (output,xpub_type,output.xpub_type),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (output,script_config,output.script_config),   4) \
X(a, STATIC,   SINGULAR, BOOL,     display,           5)
#define shiftcrypto_bitbox02_BTCPubRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_BTCPubRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCPubRequest_output_script_config_MSGTYPE shiftcrypto_bitbox02_BTCScriptConfig

#define shiftcrypto_bitbox02_BTCXpubsRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    coin,              1) \
X(a, STATIC,   SINGULAR, UENUM,    xpub_type,         2) \
X(a, CALLBACK, REPEATED, MESSAGE,  keypaths,          3)
#define shiftcrypto_bitbox02_BTCXpubsRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BTCXpubsRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCXpubsRequest_keypaths_MSGTYPE shiftcrypto_bitbox02_Keypath

#define shiftcrypto_bitbox02_BTCScriptConfigWithKeypath_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  script_config,     2) \
X(a, STATIC,   REPEATED, UINT32,   keypath,           3)
#define shiftcrypto_bitbox02_BTCScriptConfigWithKeypath_CALLBACK NULL
#define shiftcrypto_bitbox02_BTCScriptConfigWithKeypath_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCScriptConfigWithKeypath_script_config_MSGTYPE shiftcrypto_bitbox02_BTCScriptConfig

#define shiftcrypto_bitbox02_BTCSignInitRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    coin,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  script_configs,    2) \
X(a, STATIC,   SINGULAR, UINT32,   version,           4) \
X(a, STATIC,   SINGULAR, UINT32,   num_inputs,        5) \
X(a, STATIC,   SINGULAR, UINT32,   num_outputs,       6) \
X(a, STATIC,   SINGULAR, UINT32,   locktime,          7) \
X(a, STATIC,   SINGULAR, UENUM,    format_unit,       8) \
X(a, STATIC,   SINGULAR, BOOL,     contains_silent_payment_outputs,   9) \
X(a, CALLBACK, REPEATED, MESSAGE,  output_script_configs,  10)
#define shiftcrypto_bitbox02_BTCSignInitRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BTCSignInitRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCSignInitRequest_script_configs_MSGTYPE shiftcrypto_bitbox02_BTCScriptConfigWithKeypath
#define shiftcrypto_bitbox02_BTCSignInitRequest_output_script_configs_MSGTYPE shiftcrypto_bitbox02_BTCScriptConfigWithKeypath

#define shiftcrypto_bitbox02_BTCSignNextResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   index,             2) \
X(a, STATIC,   SINGULAR, BOOL,     has_signature,     3) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         4) \
X(a, STATIC,   SINGULAR, UINT32,   prev_index,        5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  anti_klepto_signer_commitment,   6) \
X(a, CALLBACK, SINGULAR, BYTES,    generated_output_pkscript,   7) \
X(a, CALLBACK, SINGULAR, BYTES,    silent_payment_dleq_proof,   8)
#define shiftcrypto_bitbox02_BTCSignNextResponse_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BTCSignNextResponse_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCSignNextResponse_anti_klepto_signer_commitment_MSGTYPE shiftcrypto_bitbox02_AntiKleptoSignerCommitment

#define shiftcrypto_bitbox02_BTCSignInputRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    prevOutHash,       1) \
X(a, STATIC,   SINGULAR, UINT32,   prevOutIndex,      2) \
X(a, STATIC,   SINGULAR, UINT64,   prevOutValue,      3) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          4) \
X(a, STATIC,   REPEATED, UINT32,   keypath,           6) \
X(a, STATIC,   SINGULAR, UINT32,   script_config_index,   7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  host_nonce_commitment,   8)
#define shiftcrypto_bitbox02_BTCSignInputRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_BTCSignInputRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCSignInputRequest_host_nonce_commitment_MSGTYPE shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment

#define shiftcrypto_bitbox02_BTCSignOutputRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     ours,              1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2) \
X(a, STATIC,   SINGULAR, UINT64,   value,             3) \
X(a, CALLBACK, SINGULAR, BYTES,    payload,           4) \
X(a, STATIC,   REPEATED, UINT32,   keypath,           5) \
X(a, STATIC,   SINGULAR, UINT32,   script_config_index,   6) \
X(a, STATIC,   OPTIONAL, UINT32,   payment_request_index,   7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  silent_payment,    8) \
X(a, STATIC,   OPTIONAL, UINT32,   output_script_config_index,   9)
#define shiftcrypto_bitbox02_BTCSignOutputRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BTCSignOutputRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCSignOutputRequest_silent_payment_MSGTYPE shiftcrypto_bitbox02_BTCSignOutputRequest_SilentPayment

#define shiftcrypto_bitbox02_BTCSignOutputRequest_SilentPayment_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   address,           1)
#define shiftcrypto_bitbox02_BTCSignOutputRequest_SilentPayment_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BTCSignOutputRequest_SilentPayment_DEFAULT NULL

#define shiftcrypto_bitbox02_BTCScriptConfigRegistration_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    coin,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  script_config,     2) \
X(a, STATIC,   REPEATED, UINT32,   keypath,           3)
#define shiftcrypto_bitbox02_BTCScriptConfigRegistration_CALLBACK NULL
#define shiftcrypto_bitbox02_BTCScriptConfigRegistration_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCScriptConfigRegistration_script_config_MSGTYPE shiftcrypto_bitbox02_BTCScriptConfig

#define shiftcrypto_bitbox02_BTCSuccess_FIELDLIST(X, a) \

#define shiftcrypto_bitbox02_BTCSuccess_CALLBACK NULL
#define shiftcrypto_bitbox02_BTCSuccess_DEFAULT NULL

#define shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  registration,      1)
#define shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest_registration_MSGTYPE shiftcrypto_bitbox02_BTCScriptConfigRegistration

#define shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     is_registered,     1)
#define shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredResponse_CALLBACK NULL
#define shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredResponse_DEFAULT NULL

#define shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  registration,      1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, UENUM,    xpub_type,         3)
#define shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_registration_MSGTYPE shiftcrypto_bitbox02_BTCScriptConfigRegistration

#define shiftcrypto_bitbox02_BTCPrevTxInitRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   version,           1) \
X(a, STATIC,   SINGULAR, UINT32,   num_inputs,        2) \
X(a, STATIC,   SINGULAR, UINT32,   num_outputs,       3) \
X(a, STATIC,   SINGULAR, UINT32,   locktime,          4)
#define shiftcrypto_bitbox02_BTCPrevTxInitRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_BTCPrevTxInitRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_BTCPrevTxInputRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    prev_out_hash,     1) \
X(a, STATIC,   SINGULAR, UINT32,   prev_out_index,    2) \
X(a, CALLBACK, SINGULAR, BYTES,    signature_script,   3) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          4)
#define shiftcrypto_bitbox02_BTCPrevTxInputRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BTCPrevTxInputRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_BTCPrevTxOutputRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   value,             1) \
X(a, CALLBACK, SINGULAR, BYTES,    pubkey_script,     2)
#define shiftcrypto_bitbox02_BTCPrevTxOutputRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BTCPrevTxOutputRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   recipient_name,    1) \
X(a, CALLBACK, REPEATED, MESSAGE,  memos,             2) \
X(a, CALLBACK, SINGULAR, BYTES,    nonce,             3) \
X(a, STATIC,   SINGULAR, UINT64,   total_amount,      4) \
X(a, CALLBACK, SINGULAR, BYTES,    signature,         5)
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_memos_MSGTYPE shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo

#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (memo,text_memo,memo.text_memo),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (memo,coin_purchase_memo,memo.coin_purchase_memo),   2)
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CALLBACK NULL
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_memo_text_memo_MSGTYPE shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_TextMemo
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_memo_coin_purchase_memo_MSGTYPE shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo

#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_TextMemo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   note,              1)
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_TextMemo_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_TextMemo_DEFAULT NULL

#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   coin_type,         1) \
X(a, CALLBACK, SINGULAR, STRING,   amount,            2) \
X(a, CALLBACK, SINGULAR, STRING,   address,           3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (address_derivation,eth,address_derivation.eth),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (address_derivation,btc,address_derivation.btc),   5)
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_address_derivation_eth_MSGTYPE shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_EthAddressDerivation
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_address_derivation_btc_MSGTYPE shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_BtcAddressDerivation

#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_EthAddressDerivation_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   keypath,           1)
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_EthAddressDerivation_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_EthAddressDerivation_DEFAULT NULL

#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_BtcAddressDerivation_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  script_config,     1)
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_BtcAddressDerivation_CALLBACK NULL
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_BtcAddressDerivation_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_BtcAddressDerivation_script_config_MSGTYPE shiftcrypto_bitbox02_BTCScriptConfigWithKeypath

#define shiftcrypto_bitbox02_BTCSignMessageRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    coin,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  script_config,     2) \
X(a, CALLBACK, SINGULAR, BYTES,    msg,               3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  host_nonce_commitment,   4)
#define shiftcrypto_bitbox02_BTCSignMessageRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BTCSignMessageRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCSignMessageRequest_script_config_MSGTYPE shiftcrypto_bitbox02_BTCScriptConfigWithKeypath
#define shiftcrypto_bitbox02_BTCSignMessageRequest_host_nonce_commitment_MSGTYPE shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment

#define shiftcrypto_bitbox02_BTCSignMessageResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         1)
#define shiftcrypto_bitbox02_BTCSignMessageResponse_CALLBACK NULL
#define shiftcrypto_bitbox02_BTCSignMessageResponse_DEFAULT NULL

#define shiftcrypto_bitbox02_BTCRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,is_script_config_registered,request.is_script_config_registered),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,register_script_config,request.register_script_config),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,prevtx_init,request.prevtx_init),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,prevtx_input,request.prevtx_input),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,prevtx_output,request.prevtx_output),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,sign_message,request.sign_message),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,antiklepto_signature,request.antiklepto_signature),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,payment_request,request.payment_request),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,xpubs,request.xpubs),   9)
#define shiftcrypto_bitbox02_BTCRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_BTCRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCRequest_request_is_script_config_registered_MSGTYPE shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest
#define shiftcrypto_bitbox02_BTCRequest_request_register_script_config_MSGTYPE shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest
#define shiftcrypto_bitbox02_BTCRequest_request_prevtx_init_MSGTYPE shiftcrypto_bitbox02_BTCPrevTxInitRequest
#define shiftcrypto_bitbox02_BTCRequest_request_prevtx_input_MSGTYPE shiftcrypto_bitbox02_BTCPrevTxInputRequest
#define shiftcrypto_bitbox02_BTCRequest_request_prevtx_output_MSGTYPE shiftcrypto_bitbox02_BTCPrevTxOutputRequest
#define shiftcrypto_bitbox02_BTCRequest_request_sign_message_MSGTYPE shiftcrypto_bitbox02_BTCSignMessageRequest
#define shiftcrypto_bitbox02_BTCRequest_request_antiklepto_signature_MSGTYPE shiftcrypto_bitbox02_AntiKleptoSignatureRequest
#define shiftcrypto_bitbox02_BTCRequest_request_payment_request_MSGTYPE shiftcrypto_bitbox02_BTCPaymentRequestRequest
#define shiftcrypto_bitbox02_BTCRequest_request_xpubs_MSGTYPE shiftcrypto_bitbox02_BTCXpubsRequest

#define shiftcrypto_bitbox02_BTCResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,success,response.success),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,is_script_config_registered,response.is_script_config_registered),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,sign_next,response.sign_next),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,sign_message,response.sign_message),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,antiklepto_signer_commitment,response.antiklepto_signer_commitment),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,pubs,response.pubs),   6)
#define shiftcrypto_bitbox02_BTCResponse_CALLBACK NULL
#define shiftcrypto_bitbox02_BTCResponse_DEFAULT NULL
#define shiftcrypto_bitbox02_BTCResponse_response_success_MSGTYPE shiftcrypto_bitbox02_BTCSuccess
#define shiftcrypto_bitbox02_BTCResponse_response_is_script_config_registered_MSGTYPE shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredResponse
#define shiftcrypto_bitbox02_BTCResponse_response_sign_next_MSGTYPE shiftcrypto_bitbox02_BTCSignNextResponse
#define shiftcrypto_bitbox02_BTCResponse_response_sign_message_MSGTYPE shiftcrypto_bitbox02_BTCSignMessageResponse
#define shiftcrypto_bitbox02_BTCResponse_response_antiklepto_signer_commitment_MSGTYPE shiftcrypto_bitbox02_AntiKleptoSignerCommitment
#define shiftcrypto_bitbox02_BTCResponse_response_pubs_MSGTYPE shiftcrypto_bitbox02_PubsResponse

extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCScriptConfig_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCScriptConfig_Multisig_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCScriptConfig_Policy_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCPubRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCXpubsRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCScriptConfigWithKeypath_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCSignInitRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCSignNextResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCSignInputRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCSignOutputRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCSignOutputRequest_SilentPayment_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCScriptConfigRegistration_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCSuccess_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCPrevTxInitRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCPrevTxInputRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCPrevTxOutputRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCPaymentRequestRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_TextMemo_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_EthAddressDerivation_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_BtcAddressDerivation_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCSignMessageRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCSignMessageResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BTCResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define shiftcrypto_bitbox02_BTCScriptConfig_fields &shiftcrypto_bitbox02_BTCScriptConfig_msg
#define shiftcrypto_bitbox02_BTCScriptConfig_Multisig_fields &shiftcrypto_bitbox02_BTCScriptConfig_Multisig_msg
#define shiftcrypto_bitbox02_BTCScriptConfig_Policy_fields &shiftcrypto_bitbox02_BTCScriptConfig_Policy_msg
#define shiftcrypto_bitbox02_BTCPubRequest_fields &shiftcrypto_bitbox02_BTCPubRequest_msg
#define shiftcrypto_bitbox02_BTCXpubsRequest_fields &shiftcrypto_bitbox02_BTCXpubsRequest_msg
#define shiftcrypto_bitbox02_BTCScriptConfigWithKeypath_fields &shiftcrypto_bitbox02_BTCScriptConfigWithKeypath_msg
#define shiftcrypto_bitbox02_BTCSignInitRequest_fields &shiftcrypto_bitbox02_BTCSignInitRequest_msg
#define shiftcrypto_bitbox02_BTCSignNextResponse_fields &shiftcrypto_bitbox02_BTCSignNextResponse_msg
#define shiftcrypto_bitbox02_BTCSignInputRequest_fields &shiftcrypto_bitbox02_BTCSignInputRequest_msg
#define shiftcrypto_bitbox02_BTCSignOutputRequest_fields &shiftcrypto_bitbox02_BTCSignOutputRequest_msg
#define shiftcrypto_bitbox02_BTCSignOutputRequest_SilentPayment_fields &shiftcrypto_bitbox02_BTCSignOutputRequest_SilentPayment_msg
#define shiftcrypto_bitbox02_BTCScriptConfigRegistration_fields &shiftcrypto_bitbox02_BTCScriptConfigRegistration_msg
#define shiftcrypto_bitbox02_BTCSuccess_fields &shiftcrypto_bitbox02_BTCSuccess_msg
#define shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest_fields &shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest_msg
#define shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredResponse_fields &shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredResponse_msg
#define shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_fields &shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_msg
#define shiftcrypto_bitbox02_BTCPrevTxInitRequest_fields &shiftcrypto_bitbox02_BTCPrevTxInitRequest_msg
#define shiftcrypto_bitbox02_BTCPrevTxInputRequest_fields &shiftcrypto_bitbox02_BTCPrevTxInputRequest_msg
#define shiftcrypto_bitbox02_BTCPrevTxOutputRequest_fields &shiftcrypto_bitbox02_BTCPrevTxOutputRequest_msg
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_fields &shiftcrypto_bitbox02_BTCPaymentRequestRequest_msg
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_fields &shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_msg
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_TextMemo_fields &shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_TextMemo_msg
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_fields &shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_msg
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_EthAddressDerivation_fields &shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_EthAddressDerivation_msg
#define shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_BtcAddressDerivation_fields &shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_BtcAddressDerivation_msg
#define shiftcrypto_bitbox02_BTCSignMessageRequest_fields &shiftcrypto_bitbox02_BTCSignMessageRequest_msg
#define shiftcrypto_bitbox02_BTCSignMessageResponse_fields &shiftcrypto_bitbox02_BTCSignMessageResponse_msg
#define shiftcrypto_bitbox02_BTCRequest_fields &shiftcrypto_bitbox02_BTCRequest_msg
#define shiftcrypto_bitbox02_BTCResponse_fields &shiftcrypto_bitbox02_BTCResponse_msg

/* Maximum encoded size of messages (where known) */
/* shiftcrypto_bitbox02_BTCScriptConfig_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCScriptConfig_Multisig_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCScriptConfig_Policy_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCPubRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCXpubsRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCScriptConfigWithKeypath_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCSignInitRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCSignNextResponse_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCSignOutputRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCSignOutputRequest_SilentPayment_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCScriptConfigRegistration_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCRegisterScriptConfigRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCPrevTxInputRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCPrevTxOutputRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCPaymentRequestRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_TextMemo_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_EthAddressDerivation_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCPaymentRequestRequest_Memo_CoinPurchaseMemo_BtcAddressDerivation_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCSignMessageRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BTCResponse_size depends on runtime parameters */
#define SHIFTCRYPTO_BITBOX02_BTC_PB_H_MAX_SIZE   shiftcrypto_bitbox02_BTCSignInputRequest_size
#define shiftcrypto_bitbox02_BTCIsScriptConfigRegisteredResponse_size 2
#define shiftcrypto_bitbox02_BTCPrevTxInitRequest_size 24
#define shiftcrypto_bitbox02_BTCSignInputRequest_size 291
#define shiftcrypto_bitbox02_BTCSignMessageResponse_size 67
#define shiftcrypto_bitbox02_BTCSuccess_size     0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
