/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SHIFTCRYPTO_BITBOX02_CARDANO_PB_H_INCLUDED
#define PB_SHIFTCRYPTO_BITBOX02_CARDANO_PB_H_INCLUDED
#include <pb.h>
#include "common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _shiftcrypto_bitbox02_CardanoNetwork {
    shiftcrypto_bitbox02_CardanoNetwork_CardanoMainnet = 0,
    shiftcrypto_bitbox02_CardanoNetwork_CardanoTestnet = 1
} shiftcrypto_bitbox02_CardanoNetwork;

typedef enum _shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType {
    shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType_KEY_HASH = 0,
    shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType_SCRIPT_HASH = 1,
    shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType_ALWAYS_ABSTAIN = 2,
    shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType_ALWAYS_NO_CONFIDENCE = 3
} shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType;

/* Struct definitions */
typedef struct _shiftcrypto_bitbox02_CardanoXpubsRequest {
    pb_callback_t keypaths;
} shiftcrypto_bitbox02_CardanoXpubsRequest;

typedef struct _shiftcrypto_bitbox02_CardanoXpubsResponse {
    pb_callback_t xpubs;
} shiftcrypto_bitbox02_CardanoXpubsResponse;

typedef struct _shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh {
    pb_callback_t keypath_payment;
    pb_callback_t keypath_stake;
} shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh;

typedef struct _shiftcrypto_bitbox02_CardanoScriptConfig {
    pb_size_t which_config;
    union {
        /* Shelley PaymentKeyHash & StakeKeyHash */
        shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh pkh_skh;
    } config;
} shiftcrypto_bitbox02_CardanoScriptConfig;

typedef struct _shiftcrypto_bitbox02_CardanoAddressRequest {
    shiftcrypto_bitbox02_CardanoNetwork network;
    bool display;
    bool has_script_config;
    shiftcrypto_bitbox02_CardanoScriptConfig script_config;
} shiftcrypto_bitbox02_CardanoAddressRequest;

/* Max allowed transaction size is 16384 bytes according to
 https://github.com/cardano-foundation/CIPs/blob/master/CIP-0009/CIP-0009.md. Unlike with BTC, we
 can fit the whole request in RAM and don't need to stream.

 See also: https://github.com/input-output-hk/cardano-ledger-specs/blob/d0aa86ded0b973b09b629e5aa62aa1e71364d088/eras/alonzo/test-suite/cddl-files/alonzo.cddl#L50 */
typedef struct _shiftcrypto_bitbox02_CardanoSignTransactionRequest {
    shiftcrypto_bitbox02_CardanoNetwork network;
    pb_callback_t inputs;
    pb_callback_t outputs;
    uint64_t fee;
    uint64_t ttl;
    pb_callback_t certificates;
    pb_callback_t withdrawals;
    uint64_t validity_interval_start;
    bool allow_zero_ttl; /* include ttl even if it is zero */
    /* Tag arrays in the transaction serialization with the 258 tag.
 See https://github.com/IntersectMBO/cardano-ledger/blob/6e2d37cc0f47bd02e89b4ce9f78b59c35c958e96/eras/conway/impl/cddl-files/extra.cddl#L5 */
    bool tag_cbor_sets;
} shiftcrypto_bitbox02_CardanoSignTransactionRequest;

typedef struct _shiftcrypto_bitbox02_CardanoSignTransactionRequest_Input {
    pb_callback_t keypath;
    pb_callback_t prev_out_hash;
    uint32_t prev_out_index;
} shiftcrypto_bitbox02_CardanoSignTransactionRequest_Input;

/* https://github.com/input-output-hk/cardano-ledger/blob/d0aa86ded0b973b09b629e5aa62aa1e71364d088/eras/alonzo/test-suite/cddl-files/alonzo.cddl#L358 */
typedef struct _shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup {
    pb_callback_t policy_id;
    pb_callback_t tokens;
} shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup;

typedef struct _shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_Token {
    pb_callback_t asset_name;
    /* Number of tokens transacted of this asset. */
    uint64_t value;
} shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_Token;

typedef struct _shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output {
    pb_callback_t encoded_address;
    uint64_t value;
    /* Optional. If provided, this is validated as a change output. */
    bool has_script_config;
    shiftcrypto_bitbox02_CardanoScriptConfig script_config;
    pb_callback_t asset_groups;
} shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output;

typedef struct _shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_StakeDelegation {
    pb_callback_t keypath;
    pb_callback_t pool_keyhash;
} shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_StakeDelegation;

typedef struct _shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation {
    /* keypath in this instance refers to stake credential */
    pb_callback_t keypath;
    shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType type;
    pb_callback_t drep_credhash;
} shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation;

/* See https://github.com/IntersectMBO/cardano-ledger/blob/cardano-ledger-conway-1.12.0.0/eras/conway/impl/cddl-files/conway.cddl#L273 */
typedef struct _shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate {
    pb_size_t which_cert;
    union {
        shiftcrypto_bitbox02_Keypath stake_registration;
        shiftcrypto_bitbox02_Keypath stake_deregistration;
        shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_StakeDelegation stake_delegation;
        shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation vote_delegation;
    } cert;
} shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate;

typedef struct _shiftcrypto_bitbox02_CardanoSignTransactionRequest_Withdrawal {
    pb_callback_t keypath;
    uint64_t value;
} shiftcrypto_bitbox02_CardanoSignTransactionRequest_Withdrawal;

typedef struct _shiftcrypto_bitbox02_CardanoSignTransactionResponse {
    pb_callback_t shelley_witnesses;
} shiftcrypto_bitbox02_CardanoSignTransactionResponse;

typedef struct _shiftcrypto_bitbox02_CardanoSignTransactionResponse_ShelleyWitness {
    pb_callback_t public_key;
    pb_callback_t signature;
} shiftcrypto_bitbox02_CardanoSignTransactionResponse_ShelleyWitness;

typedef struct _shiftcrypto_bitbox02_CardanoRequest {
    pb_size_t which_request;
    union {
        shiftcrypto_bitbox02_CardanoXpubsRequest xpubs;
        shiftcrypto_bitbox02_CardanoAddressRequest address;
        shiftcrypto_bitbox02_CardanoSignTransactionRequest sign_transaction;
    } request;
} shiftcrypto_bitbox02_CardanoRequest;

typedef struct _shiftcrypto_bitbox02_CardanoResponse {
    pb_size_t which_response;
    union {
        shiftcrypto_bitbox02_CardanoXpubsResponse xpubs;
        shiftcrypto_bitbox02_PubResponse pub;
        shiftcrypto_bitbox02_CardanoSignTransactionResponse sign_transaction;
    } response;
} shiftcrypto_bitbox02_CardanoResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _shiftcrypto_bitbox02_CardanoNetwork_MIN shiftcrypto_bitbox02_CardanoNetwork_CardanoMainnet
#define _shiftcrypto_bitbox02_CardanoNetwork_MAX shiftcrypto_bitbox02_CardanoNetwork_CardanoTestnet
#define _shiftcrypto_bitbox02_CardanoNetwork_ARRAYSIZE ((shiftcrypto_bitbox02_CardanoNetwork)(shiftcrypto_bitbox02_CardanoNetwork_CardanoTestnet+1))

#define _shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType_MIN shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType_KEY_HASH
#define _shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType_MAX shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType_ALWAYS_NO_CONFIDENCE
#define _shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType_ARRAYSIZE ((shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType)(shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType_ALWAYS_NO_CONFIDENCE+1))





#define shiftcrypto_bitbox02_CardanoAddressRequest_network_ENUMTYPE shiftcrypto_bitbox02_CardanoNetwork

#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_network_ENUMTYPE shiftcrypto_bitbox02_CardanoNetwork







#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_type_ENUMTYPE shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType







/* Initializer values for message structs */
#define shiftcrypto_bitbox02_CardanoXpubsRequest_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoXpubsResponse_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoScriptConfig_init_default {0, {shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh_init_default}}
#define shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoAddressRequest_init_default {_shiftcrypto_bitbox02_CardanoNetwork_MIN, 0, false, shiftcrypto_bitbox02_CardanoScriptConfig_init_default}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_init_default {_shiftcrypto_bitbox02_CardanoNetwork_MIN, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Input_init_default {{{NULL}, NULL}, {{NULL}, NULL}, 0}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_Token_init_default {{{NULL}, NULL}, 0}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output_init_default {{{NULL}, NULL}, 0, false, shiftcrypto_bitbox02_CardanoScriptConfig_init_default, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_init_default {0, {shiftcrypto_bitbox02_Keypath_init_default}}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_StakeDelegation_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_init_default {{{NULL}, NULL}, _shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType_MIN, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Withdrawal_init_default {{{NULL}, NULL}, 0}
#define shiftcrypto_bitbox02_CardanoSignTransactionResponse_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoSignTransactionResponse_ShelleyWitness_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoRequest_init_default {0, {shiftcrypto_bitbox02_CardanoXpubsRequest_init_default}}
#define shiftcrypto_bitbox02_CardanoResponse_init_default {0, {shiftcrypto_bitbox02_CardanoXpubsResponse_init_default}}
#define shiftcrypto_bitbox02_CardanoXpubsRequest_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoXpubsResponse_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoScriptConfig_init_zero {0, {shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh_init_zero}}
#define shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoAddressRequest_init_zero {_shiftcrypto_bitbox02_CardanoNetwork_MIN, 0, false, shiftcrypto_bitbox02_CardanoScriptConfig_init_zero}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_init_zero {_shiftcrypto_bitbox02_CardanoNetwork_MIN, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Input_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, 0}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_Token_init_zero {{{NULL}, NULL}, 0}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output_init_zero {{{NULL}, NULL}, 0, false, shiftcrypto_bitbox02_CardanoScriptConfig_init_zero, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_init_zero {0, {shiftcrypto_bitbox02_Keypath_init_zero}}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_StakeDelegation_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_init_zero {{{NULL}, NULL}, _shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CardanoDRepType_MIN, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Withdrawal_init_zero {{{NULL}, NULL}, 0}
#define shiftcrypto_bitbox02_CardanoSignTransactionResponse_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoSignTransactionResponse_ShelleyWitness_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_CardanoRequest_init_zero {0, {shiftcrypto_bitbox02_CardanoXpubsRequest_init_zero}}
#define shiftcrypto_bitbox02_CardanoResponse_init_zero {0, {shiftcrypto_bitbox02_CardanoXpubsResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define shiftcrypto_bitbox02_CardanoXpubsRequest_keypaths_tag 1
#define shiftcrypto_bitbox02_CardanoXpubsResponse_xpubs_tag 1
#define shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh_keypath_payment_tag 1
#define shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh_keypath_stake_tag 2
#define shiftcrypto_bitbox02_CardanoScriptConfig_pkh_skh_tag 1
#define shiftcrypto_bitbox02_CardanoAddressRequest_network_tag 1
#define shiftcrypto_bitbox02_CardanoAddressRequest_display_tag 2
#define shiftcrypto_bitbox02_CardanoAddressRequest_script_config_tag 3
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_network_tag 1
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_inputs_tag 2
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_outputs_tag 3
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_fee_tag 4
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_ttl_tag 5
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_certificates_tag 6
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_withdrawals_tag 7
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_validity_interval_start_tag 8
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_allow_zero_ttl_tag 9
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_tag_cbor_sets_tag 10
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Input_keypath_tag 1
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Input_prev_out_hash_tag 2
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Input_prev_out_index_tag 3
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_policy_id_tag 1
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_tokens_tag 2
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_Token_asset_name_tag 1
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_Token_value_tag 2
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output_encoded_address_tag 1
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output_value_tag 2
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output_script_config_tag 3
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output_asset_groups_tag 4
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_StakeDelegation_keypath_tag 1
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_StakeDelegation_pool_keyhash_tag 2
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_keypath_tag 1
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_type_tag 2
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_drep_credhash_tag 3
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_stake_registration_tag 1
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_stake_deregistration_tag 2
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_stake_delegation_tag 3
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_vote_delegation_tag 10
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Withdrawal_keypath_tag 1
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Withdrawal_value_tag 2
#define shiftcrypto_bitbox02_CardanoSignTransactionResponse_shelley_witnesses_tag 1
#define shiftcrypto_bitbox02_CardanoSignTransactionResponse_ShelleyWitness_public_key_tag 1
#define shiftcrypto_bitbox02_CardanoSignTransactionResponse_ShelleyWitness_signature_tag 2
#define shiftcrypto_bitbox02_CardanoRequest_xpubs_tag 1
#define shiftcrypto_bitbox02_CardanoRequest_address_tag 2
#define shiftcrypto_bitbox02_CardanoRequest_sign_transaction_tag 3
#define shiftcrypto_bitbox02_CardanoResponse_xpubs_tag 1
#define shiftcrypto_bitbox02_CardanoResponse_pub_tag 2
#define shiftcrypto_bitbox02_CardanoResponse_sign_transaction_tag 3

/* Struct field encoding specification for nanopb */
#define shiftcrypto_bitbox02_CardanoXpubsRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  keypaths,          1)
#define shiftcrypto_bitbox02_CardanoXpubsRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_CardanoXpubsRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_CardanoXpubsRequest_keypaths_MSGTYPE shiftcrypto_bitbox02_Keypath

#define shiftcrypto_bitbox02_CardanoXpubsResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, BYTES,    xpubs,             1)
#define shiftcrypto_bitbox02_CardanoXpubsResponse_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_CardanoXpubsResponse_DEFAULT NULL

#define shiftcrypto_bitbox02_CardanoScriptConfig_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config,pkh_skh,config.pkh_skh),   1)
#define shiftcrypto_bitbox02_CardanoScriptConfig_CALLBACK NULL
#define shiftcrypto_bitbox02_CardanoScriptConfig_DEFAULT NULL
#define shiftcrypto_bitbox02_CardanoScriptConfig_config_pkh_skh_MSGTYPE shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh

#define shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   keypath_payment,   1) \
X(a, CALLBACK, REPEATED, UINT32,   keypath_stake,     2)
#define shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh_DEFAULT NULL

#define shiftcrypto_bitbox02_CardanoAddressRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    network,           1) \
X(a, STATIC,   SINGULAR, BOOL,     display,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  script_config,     3)
#define shiftcrypto_bitbox02_CardanoAddressRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_CardanoAddressRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_CardanoAddressRequest_script_config_MSGTYPE shiftcrypto_bitbox02_CardanoScriptConfig

#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    network,           1) \
X(a, CALLBACK, REPEATED, MESSAGE,  inputs,            2) \
X(a, CALLBACK, REPEATED, MESSAGE,  outputs,           3) \
X(a, STATIC,   SINGULAR, UINT64,   fee,               4) \
X(a, STATIC,   SINGULAR, UINT64,   ttl,               5) \
X(a, CALLBACK, REPEATED, MESSAGE,  certificates,      6) \
X(a, CALLBACK, REPEATED, MESSAGE,  withdrawals,       7) \
X(a, STATIC,   SINGULAR, UINT64,   validity_interval_start,   8) \
X(a, STATIC,   SINGULAR, BOOL,     allow_zero_ttl,    9) \
X(a, STATIC,   SINGULAR, BOOL,     tag_cbor_sets,    10)
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_inputs_MSGTYPE shiftcrypto_bitbox02_CardanoSignTransactionRequest_Input
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_outputs_MSGTYPE shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_certificates_MSGTYPE shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_withdrawals_MSGTYPE shiftcrypto_bitbox02_CardanoSignTransactionRequest_Withdrawal

#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Input_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   keypath,           1) \
X(a, CALLBACK, SINGULAR, BYTES,    prev_out_hash,     2) \
X(a, STATIC,   SINGULAR, UINT32,   prev_out_index,    3)
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Input_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Input_DEFAULT NULL

#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    policy_id,         1) \
X(a, CALLBACK, REPEATED, MESSAGE,  tokens,            2)
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_DEFAULT NULL
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_tokens_MSGTYPE shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_Token

#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_Token_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    asset_name,        1) \
X(a, STATIC,   SINGULAR, UINT64,   value,             2)
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_Token_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_Token_DEFAULT NULL

#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   encoded_address,   1) \
X(a, STATIC,   SINGULAR, UINT64,   value,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  script_config,     3) \
X(a, CALLBACK, REPEATED, MESSAGE,  asset_groups,      4)
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output_DEFAULT NULL
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output_script_config_MSGTYPE shiftcrypto_bitbox02_CardanoScriptConfig
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output_asset_groups_MSGTYPE shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup

#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cert,stake_registration,cert.stake_registration),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cert,stake_deregistration,cert.stake_deregistration),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cert,stake_delegation,cert.stake_delegation),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cert,vote_delegation,cert.vote_delegation),  10)
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_CALLBACK NULL
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_DEFAULT NULL
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_cert_stake_registration_MSGTYPE shiftcrypto_bitbox02_Keypath
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_cert_stake_deregistration_MSGTYPE shiftcrypto_bitbox02_Keypath
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_cert_stake_delegation_MSGTYPE shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_StakeDelegation
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_cert_vote_delegation_MSGTYPE shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation

#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_StakeDelegation_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   keypath,           1) \
X(a, CALLBACK, SINGULAR, BYTES,    pool_keyhash,      2)
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_StakeDelegation_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_StakeDelegation_DEFAULT NULL

#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   keypath,           1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2) \
X(a, CALLBACK, OPTIONAL, BYTES,    drep_credhash,     3)
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_DEFAULT NULL

#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Withdrawal_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   keypath,           1) \
X(a, STATIC,   SINGULAR, UINT64,   value,             2)
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Withdrawal_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Withdrawal_DEFAULT NULL

#define shiftcrypto_bitbox02_CardanoSignTransactionResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  shelley_witnesses,   1)
#define shiftcrypto_bitbox02_CardanoSignTransactionResponse_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_CardanoSignTransactionResponse_DEFAULT NULL
#define shiftcrypto_bitbox02_CardanoSignTransactionResponse_shelley_witnesses_MSGTYPE shiftcrypto_bitbox02_CardanoSignTransactionResponse_ShelleyWitness

#define shiftcrypto_bitbox02_CardanoSignTransactionResponse_ShelleyWitness_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    public_key,        1) \
X(a, CALLBACK, SINGULAR, BYTES,    signature,         2)
#define shiftcrypto_bitbox02_CardanoSignTransactionResponse_ShelleyWitness_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_CardanoSignTransactionResponse_ShelleyWitness_DEFAULT NULL

#define shiftcrypto_bitbox02_CardanoRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,xpubs,request.xpubs),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,address,request.address),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,sign_transaction,request.sign_transaction),   3)
#define shiftcrypto_bitbox02_CardanoRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_CardanoRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_CardanoRequest_request_xpubs_MSGTYPE shiftcrypto_bitbox02_CardanoXpubsRequest
#define shiftcrypto_bitbox02_CardanoRequest_request_address_MSGTYPE shiftcrypto_bitbox02_CardanoAddressRequest
#define shiftcrypto_bitbox02_CardanoRequest_request_sign_transaction_MSGTYPE shiftcrypto_bitbox02_CardanoSignTransactionRequest

#define shiftcrypto_bitbox02_CardanoResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,xpubs,response.xpubs),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,pub,response.pub),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,sign_transaction,response.sign_transaction),   3)
#define shiftcrypto_bitbox02_CardanoResponse_CALLBACK NULL
#define shiftcrypto_bitbox02_CardanoResponse_DEFAULT NULL
#define shiftcrypto_bitbox02_CardanoResponse_response_xpubs_MSGTYPE shiftcrypto_bitbox02_CardanoXpubsResponse
#define shiftcrypto_bitbox02_CardanoResponse_response_pub_MSGTYPE shiftcrypto_bitbox02_PubResponse
#define shiftcrypto_bitbox02_CardanoResponse_response_sign_transaction_MSGTYPE shiftcrypto_bitbox02_CardanoSignTransactionResponse

extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoXpubsRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoXpubsResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoScriptConfig_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoAddressRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoSignTransactionRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoSignTransactionRequest_Input_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_Token_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_StakeDelegation_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoSignTransactionRequest_Withdrawal_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoSignTransactionResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoSignTransactionResponse_ShelleyWitness_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_CardanoResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define shiftcrypto_bitbox02_CardanoXpubsRequest_fields &shiftcrypto_bitbox02_CardanoXpubsRequest_msg
#define shiftcrypto_bitbox02_CardanoXpubsResponse_fields &shiftcrypto_bitbox02_CardanoXpubsResponse_msg
#define shiftcrypto_bitbox02_CardanoScriptConfig_fields &shiftcrypto_bitbox02_CardanoScriptConfig_msg
#define shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh_fields &shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh_msg
#define shiftcrypto_bitbox02_CardanoAddressRequest_fields &shiftcrypto_bitbox02_CardanoAddressRequest_msg
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_fields &shiftcrypto_bitbox02_CardanoSignTransactionRequest_msg
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Input_fields &shiftcrypto_bitbox02_CardanoSignTransactionRequest_Input_msg
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_fields &shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_msg
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_Token_fields &shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_Token_msg
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output_fields &shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output_msg
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_fields &shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_msg
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_StakeDelegation_fields &shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_StakeDelegation_msg
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_fields &shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_msg
#define shiftcrypto_bitbox02_CardanoSignTransactionRequest_Withdrawal_fields &shiftcrypto_bitbox02_CardanoSignTransactionRequest_Withdrawal_msg
#define shiftcrypto_bitbox02_CardanoSignTransactionResponse_fields &shiftcrypto_bitbox02_CardanoSignTransactionResponse_msg
#define shiftcrypto_bitbox02_CardanoSignTransactionResponse_ShelleyWitness_fields &shiftcrypto_bitbox02_CardanoSignTransactionResponse_ShelleyWitness_msg
#define shiftcrypto_bitbox02_CardanoRequest_fields &shiftcrypto_bitbox02_CardanoRequest_msg
#define shiftcrypto_bitbox02_CardanoResponse_fields &shiftcrypto_bitbox02_CardanoResponse_msg

/* Maximum encoded size of messages (where known) */
/* shiftcrypto_bitbox02_CardanoXpubsRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoXpubsResponse_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoScriptConfig_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoScriptConfig_PkhSkh_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoAddressRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoSignTransactionRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoSignTransactionRequest_Input_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoSignTransactionRequest_AssetGroup_Token_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoSignTransactionRequest_Output_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_StakeDelegation_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoSignTransactionRequest_Certificate_VoteDelegation_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoSignTransactionRequest_Withdrawal_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoSignTransactionResponse_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoSignTransactionResponse_ShelleyWitness_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_CardanoResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
