/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SHIFTCRYPTO_BITBOX02_COMMON_PB_H_INCLUDED
#define PB_SHIFTCRYPTO_BITBOX02_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _shiftcrypto_bitbox02_PubResponse {
    char pub[256];
} shiftcrypto_bitbox02_PubResponse;

typedef struct _shiftcrypto_bitbox02_PubsResponse {
    pb_callback_t pubs;
} shiftcrypto_bitbox02_PubsResponse;

typedef struct _shiftcrypto_bitbox02_RootFingerprintRequest {
    char dummy_field;
} shiftcrypto_bitbox02_RootFingerprintRequest;

typedef PB_BYTES_ARRAY_T(4) shiftcrypto_bitbox02_RootFingerprintResponse_fingerprint_t;
typedef struct _shiftcrypto_bitbox02_RootFingerprintResponse {
    shiftcrypto_bitbox02_RootFingerprintResponse_fingerprint_t fingerprint;
} shiftcrypto_bitbox02_RootFingerprintResponse;

typedef PB_BYTES_ARRAY_T(1) shiftcrypto_bitbox02_XPub_depth_t;
typedef PB_BYTES_ARRAY_T(4) shiftcrypto_bitbox02_XPub_parent_fingerprint_t;
typedef PB_BYTES_ARRAY_T(32) shiftcrypto_bitbox02_XPub_chain_code_t;
typedef PB_BYTES_ARRAY_T(33) shiftcrypto_bitbox02_XPub_public_key_t;
/* See https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki.
 version field dropped as it will set dynamically based on the context (xpub, ypub, etc.). */
typedef struct _shiftcrypto_bitbox02_XPub {
    shiftcrypto_bitbox02_XPub_depth_t depth;
    shiftcrypto_bitbox02_XPub_parent_fingerprint_t parent_fingerprint;
    uint32_t child_num;
    shiftcrypto_bitbox02_XPub_chain_code_t chain_code;
    shiftcrypto_bitbox02_XPub_public_key_t public_key;
} shiftcrypto_bitbox02_XPub;

/* This message exists for use in oneof or repeated fields, where one can't inline `repeated uint32` due to protobuf rules. */
typedef struct _shiftcrypto_bitbox02_Keypath {
    pb_size_t keypath_count;
    uint32_t keypath[32];
} shiftcrypto_bitbox02_Keypath;

typedef PB_BYTES_ARRAY_T(4) shiftcrypto_bitbox02_KeyOriginInfo_root_fingerprint_t;
typedef struct _shiftcrypto_bitbox02_KeyOriginInfo {
    shiftcrypto_bitbox02_KeyOriginInfo_root_fingerprint_t root_fingerprint;
    pb_size_t keypath_count;
    uint32_t keypath[32];
    bool has_xpub;
    shiftcrypto_bitbox02_XPub xpub;
} shiftcrypto_bitbox02_KeyOriginInfo;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define shiftcrypto_bitbox02_PubResponse_init_default {""}
#define shiftcrypto_bitbox02_PubsResponse_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_RootFingerprintRequest_init_default {0}
#define shiftcrypto_bitbox02_RootFingerprintResponse_init_default {{0, {0}}}
#define shiftcrypto_bitbox02_XPub_init_default   {{0, {0}}, {0, {0}}, 0, {0, {0}}, {0, {0}}}
#define shiftcrypto_bitbox02_Keypath_init_default {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define shiftcrypto_bitbox02_KeyOriginInfo_init_default {{0, {0}}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, false, shiftcrypto_bitbox02_XPub_init_default}
#define shiftcrypto_bitbox02_PubResponse_init_zero {""}
#define shiftcrypto_bitbox02_PubsResponse_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_RootFingerprintRequest_init_zero {0}
#define shiftcrypto_bitbox02_RootFingerprintResponse_init_zero {{0, {0}}}
#define shiftcrypto_bitbox02_XPub_init_zero      {{0, {0}}, {0, {0}}, 0, {0, {0}}, {0, {0}}}
#define shiftcrypto_bitbox02_Keypath_init_zero   {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define shiftcrypto_bitbox02_KeyOriginInfo_init_zero {{0, {0}}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, false, shiftcrypto_bitbox02_XPub_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define shiftcrypto_bitbox02_PubResponse_pub_tag 1
#define shiftcrypto_bitbox02_PubsResponse_pubs_tag 1
#define shiftcrypto_bitbox02_RootFingerprintResponse_fingerprint_tag 1
#define shiftcrypto_bitbox02_XPub_depth_tag      1
#define shiftcrypto_bitbox02_XPub_parent_fingerprint_tag 2
#define shiftcrypto_bitbox02_XPub_child_num_tag  3
#define shiftcrypto_bitbox02_XPub_chain_code_tag 4
#define shiftcrypto_bitbox02_XPub_public_key_tag 5
#define shiftcrypto_bitbox02_Keypath_keypath_tag 1
#define shiftcrypto_bitbox02_KeyOriginInfo_root_fingerprint_tag 1
#define shiftcrypto_bitbox02_KeyOriginInfo_keypath_tag 2
#define shiftcrypto_bitbox02_KeyOriginInfo_xpub_tag 3

/* Struct field encoding specification for nanopb */
#define shiftcrypto_bitbox02_PubResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pub,               1)
#define shiftcrypto_bitbox02_PubResponse_CALLBACK NULL
#define shiftcrypto_bitbox02_PubResponse_DEFAULT NULL

#define shiftcrypto_bitbox02_PubsResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   pubs,              1)
#define shiftcrypto_bitbox02_PubsResponse_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_PubsResponse_DEFAULT NULL

#define shiftcrypto_bitbox02_RootFingerprintRequest_FIELDLIST(X, a) \

#define shiftcrypto_bitbox02_RootFingerprintRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_RootFingerprintRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_RootFingerprintResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    fingerprint,       1)
#define shiftcrypto_bitbox02_RootFingerprintResponse_CALLBACK NULL
#define shiftcrypto_bitbox02_RootFingerprintResponse_DEFAULT NULL

#define shiftcrypto_bitbox02_XPub_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    depth,             1) \
X(a, STATIC,   SINGULAR, BYTES,    parent_fingerprint,   2) \
X(a, STATIC,   SINGULAR, UINT32,   child_num,         3) \
X(a, STATIC,   SINGULAR, BYTES,    chain_code,        4) \
X(a, STATIC,   SINGULAR, BYTES,    public_key,        5)
#define shiftcrypto_bitbox02_XPub_CALLBACK NULL
#define shiftcrypto_bitbox02_XPub_DEFAULT NULL

#define shiftcrypto_bitbox02_Keypath_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UINT32,   keypath,           1)
#define shiftcrypto_bitbox02_Keypath_CALLBACK NULL
#define shiftcrypto_bitbox02_Keypath_DEFAULT NULL

#define shiftcrypto_bitbox02_KeyOriginInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    root_fingerprint,   1) \
X(a, STATIC,   REPEATED, UINT32,   keypath,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  xpub,              3)
#define shiftcrypto_bitbox02_KeyOriginInfo_CALLBACK NULL
#define shiftcrypto_bitbox02_KeyOriginInfo_DEFAULT NULL
#define shiftcrypto_bitbox02_KeyOriginInfo_xpub_MSGTYPE shiftcrypto_bitbox02_XPub

extern const pb_msgdesc_t shiftcrypto_bitbox02_PubResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_PubsResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_RootFingerprintRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_RootFingerprintResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_XPub_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_Keypath_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_KeyOriginInfo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define shiftcrypto_bitbox02_PubResponse_fields &shiftcrypto_bitbox02_PubResponse_msg
#define shiftcrypto_bitbox02_PubsResponse_fields &shiftcrypto_bitbox02_PubsResponse_msg
#define shiftcrypto_bitbox02_RootFingerprintRequest_fields &shiftcrypto_bitbox02_RootFingerprintRequest_msg
#define shiftcrypto_bitbox02_RootFingerprintResponse_fields &shiftcrypto_bitbox02_RootFingerprintResponse_msg
#define shiftcrypto_bitbox02_XPub_fields &shiftcrypto_bitbox02_XPub_msg
#define shiftcrypto_bitbox02_Keypath_fields &shiftcrypto_bitbox02_Keypath_msg
#define shiftcrypto_bitbox02_KeyOriginInfo_fields &shiftcrypto_bitbox02_KeyOriginInfo_msg

/* Maximum encoded size of messages (where known) */
/* shiftcrypto_bitbox02_PubsResponse_size depends on runtime parameters */
#define SHIFTCRYPTO_BITBOX02_COMMON_PB_H_MAX_SIZE shiftcrypto_bitbox02_KeyOriginInfo_size
#define shiftcrypto_bitbox02_KeyOriginInfo_size  284
#define shiftcrypto_bitbox02_Keypath_size        192
#define shiftcrypto_bitbox02_PubResponse_size    258
#define shiftcrypto_bitbox02_RootFingerprintRequest_size 0
#define shiftcrypto_bitbox02_RootFingerprintResponse_size 6
#define shiftcrypto_bitbox02_XPub_size           84

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
