/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "common.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(shiftcrypto_bitbox02_PubResponse, shiftcrypto_bitbox02_PubResponse, 2)


PB_BIND(shiftcrypto_bitbox02_PubsResponse, shiftcrypto_bitbox02_PubsResponse, AUTO)


PB_BIND(shiftcrypto_bitbox02_RootFingerprintRequest, shiftcrypto_bitbox02_RootFingerprintRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_RootFingerprintResponse, shiftcrypto_bitbox02_RootFingerprintResponse, AUTO)


PB_BIND(shiftcrypto_bitbox02_XPub, shiftcrypto_bitbox02_XPub, AUTO)


PB_BIND(shiftcrypto_bitbox02_Keypath, shiftcrypto_bitbox02_Keypath, AUTO)


PB_BIND(shiftcrypto_bitbox02_KeyOriginInfo, shiftcrypto_bitbox02_KeyOriginInfo, AUTO)



