/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "eth.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(shiftcrypto_bitbox02_ETHPubRequest, shiftcrypto_bitbox02_ETHPubRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_ETHSignRequest, shiftcrypto_bitbox02_ETHSignRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_ETHSignEIP1559Request, shiftcrypto_bitbox02_ETHSignEIP1559Request, 2)


PB_BIND(shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse, shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse, AUTO)


PB_BIND(shiftcrypto_bitbox02_ETHSignDataResponseChunkRequest, shiftcrypto_bitbox02_ETHSignDataResponseChunkRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_ETHSignMessageRequest, shiftcrypto_bitbox02_ETHSignMessageRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_ETHSignResponse, shiftcrypto_bitbox02_ETHSignResponse, AUTO)


PB_BIND(shiftcrypto_bitbox02_ETHSignTypedMessageRequest, shiftcrypto_bitbox02_ETHSignTypedMessageRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType, shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType, AUTO)


PB_BIND(shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member, shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member, AUTO)


PB_BIND(shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType, shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType, AUTO)


PB_BIND(shiftcrypto_bitbox02_ETHTypedMessageValueResponse, shiftcrypto_bitbox02_ETHTypedMessageValueResponse, AUTO)


PB_BIND(shiftcrypto_bitbox02_ETHTypedMessageValueRequest, shiftcrypto_bitbox02_ETHTypedMessageValueRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_ETHRequest, shiftcrypto_bitbox02_ETHRequest, 2)


PB_BIND(shiftcrypto_bitbox02_ETHResponse, shiftcrypto_bitbox02_ETHResponse, 2)













