/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SHIFTCRYPTO_BITBOX02_ETH_PB_H_INCLUDED
#define PB_SHIFTCRYPTO_BITBOX02_ETH_PB_H_INCLUDED
#include <pb.h>
#include "common.pb.h"
#include "antiklepto.pb.h"
#include "btc.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Kept for backwards compatibility. Use chain_id instead, introduced in v9.10.0. */
typedef enum _shiftcrypto_bitbox02_ETHCoin {
    shiftcrypto_bitbox02_ETHCoin_ETH = 0,
    /* Removed in v9.14.0 - deprecated */
    shiftcrypto_bitbox02_ETHCoin_RopstenETH = 1,
    /* Removed in v9.14.0 - deprecated */
    shiftcrypto_bitbox02_ETHCoin_RinkebyETH = 2
} shiftcrypto_bitbox02_ETHCoin;

typedef enum _shiftcrypto_bitbox02_ETHAddressCase {
    shiftcrypto_bitbox02_ETHAddressCase_ETH_ADDRESS_CASE_MIXED = 0,
    shiftcrypto_bitbox02_ETHAddressCase_ETH_ADDRESS_CASE_UPPER = 1,
    shiftcrypto_bitbox02_ETHAddressCase_ETH_ADDRESS_CASE_LOWER = 2
} shiftcrypto_bitbox02_ETHAddressCase;

typedef enum _shiftcrypto_bitbox02_ETHPubRequest_OutputType {
    shiftcrypto_bitbox02_ETHPubRequest_OutputType_ADDRESS = 0,
    shiftcrypto_bitbox02_ETHPubRequest_OutputType_XPUB = 1
} shiftcrypto_bitbox02_ETHPubRequest_OutputType;

typedef enum _shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType {
    shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType_UNKNOWN = 0,
    shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType_BYTES = 1,
    shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType_UINT = 2,
    shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType_INT = 3,
    shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType_BOOL = 4,
    shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType_ADDRESS = 5,
    shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType_STRING = 6,
    shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType_ARRAY = 7,
    shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType_STRUCT = 8
} shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType;

typedef enum _shiftcrypto_bitbox02_ETHTypedMessageValueResponse_RootObject {
    shiftcrypto_bitbox02_ETHTypedMessageValueResponse_RootObject_UNKNOWN = 0,
    shiftcrypto_bitbox02_ETHTypedMessageValueResponse_RootObject_DOMAIN = 1,
    shiftcrypto_bitbox02_ETHTypedMessageValueResponse_RootObject_MESSAGE = 2
} shiftcrypto_bitbox02_ETHTypedMessageValueResponse_RootObject;

/* Struct definitions */
typedef struct _shiftcrypto_bitbox02_ETHPubRequest {
    pb_callback_t keypath;
    /* Deprecated: use chain_id instead. */
    shiftcrypto_bitbox02_ETHCoin coin;
    shiftcrypto_bitbox02_ETHPubRequest_OutputType output_type;
    bool display;
    pb_callback_t contract_address;
    /* If non-zero, `coin` is ignored and `chain_id` is used to identify the network. */
    uint64_t chain_id;
} shiftcrypto_bitbox02_ETHPubRequest;

/* TX payload for "legacy" (EIP-155) transactions: https://eips.ethereum.org/EIPS/eip-155 */
typedef struct _shiftcrypto_bitbox02_ETHSignRequest {
    /* Deprecated: use chain_id instead. */
    shiftcrypto_bitbox02_ETHCoin coin;
    pb_callback_t keypath;
    pb_callback_t nonce; /* smallest big endian serialization, max. 16 bytes */
    pb_callback_t gas_price; /* smallest big endian serialization, max. 16 bytes */
    pb_callback_t gas_limit; /* smallest big endian serialization, max. 16 bytes */
    pb_callback_t recipient; /* 20 byte recipient */
    pb_callback_t value; /* smallest big endian serialization, max. 32 bytes */
    pb_callback_t data;
    bool has_host_nonce_commitment;
    shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment host_nonce_commitment;
    /* If non-zero, `coin` is ignored and `chain_id` is used to identify the network. */
    uint64_t chain_id;
    shiftcrypto_bitbox02_ETHAddressCase address_case;
    /* For streaming: if non-zero, data field should be empty and data will be requested in chunks */
    uint32_t data_length;
} shiftcrypto_bitbox02_ETHSignRequest;

/* TX payload for an EIP-1559 (type 2) transaction: https://eips.ethereum.org/EIPS/eip-1559 */
typedef struct _shiftcrypto_bitbox02_ETHSignEIP1559Request {
    uint64_t chain_id;
    pb_callback_t keypath;
    pb_callback_t nonce; /* smallest big endian serialization, max. 16 bytes */
    pb_callback_t max_priority_fee_per_gas; /* smallest big endian serialization, max. 16 bytes */
    pb_callback_t max_fee_per_gas; /* smallest big endian serialization, max. 16 bytes */
    pb_callback_t gas_limit; /* smallest big endian serialization, max. 16 bytes */
    pb_callback_t recipient; /* 20 byte recipient */
    pb_callback_t value; /* smallest big endian serialization, max. 32 bytes */
    pb_callback_t data;
    bool has_host_nonce_commitment;
    shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment host_nonce_commitment;
    shiftcrypto_bitbox02_ETHAddressCase address_case;
    /* For streaming: if non-zero, data field should be empty and data will be requested in chunks */
    uint32_t data_length;
    bool has_payment_request;
    shiftcrypto_bitbox02_BTCPaymentRequestRequest payment_request;
} shiftcrypto_bitbox02_ETHSignEIP1559Request;

typedef struct _shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse {
    uint32_t offset;
    uint32_t length;
} shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse;

typedef struct _shiftcrypto_bitbox02_ETHSignDataResponseChunkRequest {
    pb_callback_t chunk;
} shiftcrypto_bitbox02_ETHSignDataResponseChunkRequest;

typedef struct _shiftcrypto_bitbox02_ETHSignMessageRequest {
    /* Deprecated: use chain_id instead. */
    shiftcrypto_bitbox02_ETHCoin coin;
    pb_callback_t keypath;
    pb_callback_t msg;
    bool has_host_nonce_commitment;
    shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment host_nonce_commitment;
    /* If non-zero, `coin` is ignored and `chain_id` is used to identify the network. */
    uint64_t chain_id;
} shiftcrypto_bitbox02_ETHSignMessageRequest;

typedef struct _shiftcrypto_bitbox02_ETHSignResponse {
    pb_callback_t signature; /* 65 bytes, last byte is the recid */
} shiftcrypto_bitbox02_ETHSignResponse;

typedef struct _shiftcrypto_bitbox02_ETHSignTypedMessageRequest {
    uint64_t chain_id;
    pb_callback_t keypath;
    pb_callback_t types;
    pb_callback_t primary_type;
    bool has_host_nonce_commitment;
    shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment host_nonce_commitment;
} shiftcrypto_bitbox02_ETHSignTypedMessageRequest;

typedef struct _shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType {
    pb_callback_t type;
    pb_callback_t size;
    pb_callback_t struct_name; /* if type==STRUCT, name of struct type. */
    pb_callback_t array_type; /* if type==ARRAY, type of elements */
} shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType;

typedef struct _shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member {
    pb_callback_t name;
    bool has_type;
    shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType type;
} shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member;

typedef struct _shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType {
    pb_callback_t name;
    pb_callback_t members;
} shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType;

typedef struct _shiftcrypto_bitbox02_ETHTypedMessageValueResponse {
    shiftcrypto_bitbox02_ETHTypedMessageValueResponse_RootObject root_object;
    pb_callback_t path;
} shiftcrypto_bitbox02_ETHTypedMessageValueResponse;

typedef struct _shiftcrypto_bitbox02_ETHTypedMessageValueRequest {
    pb_callback_t value;
    /* If non-zero, value should be empty and data will be streamed via
 DataRequestChunk/DataResponseChunk. */
    uint32_t data_length;
} shiftcrypto_bitbox02_ETHTypedMessageValueRequest;

typedef struct _shiftcrypto_bitbox02_ETHRequest {
    pb_size_t which_request;
    union {
        shiftcrypto_bitbox02_ETHPubRequest pub;
        shiftcrypto_bitbox02_ETHSignRequest sign;
        shiftcrypto_bitbox02_ETHSignMessageRequest sign_msg;
        shiftcrypto_bitbox02_AntiKleptoSignatureRequest antiklepto_signature;
        shiftcrypto_bitbox02_ETHSignTypedMessageRequest sign_typed_msg;
        shiftcrypto_bitbox02_ETHTypedMessageValueRequest typed_msg_value;
        shiftcrypto_bitbox02_ETHSignEIP1559Request sign_eip1559;
        shiftcrypto_bitbox02_ETHSignDataResponseChunkRequest data_response_chunk;
    } request;
} shiftcrypto_bitbox02_ETHRequest;

typedef struct _shiftcrypto_bitbox02_ETHResponse {
    pb_size_t which_response;
    union {
        shiftcrypto_bitbox02_PubResponse pub;
        shiftcrypto_bitbox02_ETHSignResponse sign;
        shiftcrypto_bitbox02_AntiKleptoSignerCommitment antiklepto_signer_commitment;
        shiftcrypto_bitbox02_ETHTypedMessageValueResponse typed_msg_value;
        shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse data_request_chunk;
    } response;
} shiftcrypto_bitbox02_ETHResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _shiftcrypto_bitbox02_ETHCoin_MIN shiftcrypto_bitbox02_ETHCoin_ETH
#define _shiftcrypto_bitbox02_ETHCoin_MAX shiftcrypto_bitbox02_ETHCoin_RinkebyETH
#define _shiftcrypto_bitbox02_ETHCoin_ARRAYSIZE ((shiftcrypto_bitbox02_ETHCoin)(shiftcrypto_bitbox02_ETHCoin_RinkebyETH+1))

#define _shiftcrypto_bitbox02_ETHAddressCase_MIN shiftcrypto_bitbox02_ETHAddressCase_ETH_ADDRESS_CASE_MIXED
#define _shiftcrypto_bitbox02_ETHAddressCase_MAX shiftcrypto_bitbox02_ETHAddressCase_ETH_ADDRESS_CASE_LOWER
#define _shiftcrypto_bitbox02_ETHAddressCase_ARRAYSIZE ((shiftcrypto_bitbox02_ETHAddressCase)(shiftcrypto_bitbox02_ETHAddressCase_ETH_ADDRESS_CASE_LOWER+1))

#define _shiftcrypto_bitbox02_ETHPubRequest_OutputType_MIN shiftcrypto_bitbox02_ETHPubRequest_OutputType_ADDRESS
#define _shiftcrypto_bitbox02_ETHPubRequest_OutputType_MAX shiftcrypto_bitbox02_ETHPubRequest_OutputType_XPUB
#define _shiftcrypto_bitbox02_ETHPubRequest_OutputType_ARRAYSIZE ((shiftcrypto_bitbox02_ETHPubRequest_OutputType)(shiftcrypto_bitbox02_ETHPubRequest_OutputType_XPUB+1))

#define _shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType_MIN shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType_UNKNOWN
#define _shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType_MAX shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType_STRUCT
#define _shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType_ARRAYSIZE ((shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType)(shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType_STRUCT+1))

#define _shiftcrypto_bitbox02_ETHTypedMessageValueResponse_RootObject_MIN shiftcrypto_bitbox02_ETHTypedMessageValueResponse_RootObject_UNKNOWN
#define _shiftcrypto_bitbox02_ETHTypedMessageValueResponse_RootObject_MAX shiftcrypto_bitbox02_ETHTypedMessageValueResponse_RootObject_MESSAGE
#define _shiftcrypto_bitbox02_ETHTypedMessageValueResponse_RootObject_ARRAYSIZE ((shiftcrypto_bitbox02_ETHTypedMessageValueResponse_RootObject)(shiftcrypto_bitbox02_ETHTypedMessageValueResponse_RootObject_MESSAGE+1))

#define shiftcrypto_bitbox02_ETHPubRequest_coin_ENUMTYPE shiftcrypto_bitbox02_ETHCoin
#define shiftcrypto_bitbox02_ETHPubRequest_output_type_ENUMTYPE shiftcrypto_bitbox02_ETHPubRequest_OutputType

#define shiftcrypto_bitbox02_ETHSignRequest_coin_ENUMTYPE shiftcrypto_bitbox02_ETHCoin
#define shiftcrypto_bitbox02_ETHSignRequest_address_case_ENUMTYPE shiftcrypto_bitbox02_ETHAddressCase

#define shiftcrypto_bitbox02_ETHSignEIP1559Request_address_case_ENUMTYPE shiftcrypto_bitbox02_ETHAddressCase



#define shiftcrypto_bitbox02_ETHSignMessageRequest_coin_ENUMTYPE shiftcrypto_bitbox02_ETHCoin



#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_type_ENUMTYPE shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DataType



#define shiftcrypto_bitbox02_ETHTypedMessageValueResponse_root_object_ENUMTYPE shiftcrypto_bitbox02_ETHTypedMessageValueResponse_RootObject





/* Initializer values for message structs */
#define shiftcrypto_bitbox02_ETHPubRequest_init_default {{{NULL}, NULL}, _shiftcrypto_bitbox02_ETHCoin_MIN, _shiftcrypto_bitbox02_ETHPubRequest_OutputType_MIN, 0, {{NULL}, NULL}, 0}
#define shiftcrypto_bitbox02_ETHSignRequest_init_default {_shiftcrypto_bitbox02_ETHCoin_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_init_default, 0, _shiftcrypto_bitbox02_ETHAddressCase_MIN, 0}
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_init_default, _shiftcrypto_bitbox02_ETHAddressCase_MIN, 0, false, shiftcrypto_bitbox02_BTCPaymentRequestRequest_init_default}
#define shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse_init_default {0, 0}
#define shiftcrypto_bitbox02_ETHSignDataResponseChunkRequest_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_ETHSignMessageRequest_init_default {_shiftcrypto_bitbox02_ETHCoin_MIN, {{NULL}, NULL}, {{NULL}, NULL}, false, shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_init_default, 0}
#define shiftcrypto_bitbox02_ETHSignResponse_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_init_default}
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member_init_default {{{NULL}, NULL}, false, shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_init_default}
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_ETHTypedMessageValueResponse_init_default {_shiftcrypto_bitbox02_ETHTypedMessageValueResponse_RootObject_MIN, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_ETHTypedMessageValueRequest_init_default {{{NULL}, NULL}, 0}
#define shiftcrypto_bitbox02_ETHRequest_init_default {0, {shiftcrypto_bitbox02_ETHPubRequest_init_default}}
#define shiftcrypto_bitbox02_ETHResponse_init_default {0, {shiftcrypto_bitbox02_PubResponse_init_default}}
#define shiftcrypto_bitbox02_ETHPubRequest_init_zero {{{NULL}, NULL}, _shiftcrypto_bitbox02_ETHCoin_MIN, _shiftcrypto_bitbox02_ETHPubRequest_OutputType_MIN, 0, {{NULL}, NULL}, 0}
#define shiftcrypto_bitbox02_ETHSignRequest_init_zero {_shiftcrypto_bitbox02_ETHCoin_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_init_zero, 0, _shiftcrypto_bitbox02_ETHAddressCase_MIN, 0}
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_init_zero {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_init_zero, _shiftcrypto_bitbox02_ETHAddressCase_MIN, 0, false, shiftcrypto_bitbox02_BTCPaymentRequestRequest_init_zero}
#define shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse_init_zero {0, 0}
#define shiftcrypto_bitbox02_ETHSignDataResponseChunkRequest_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_ETHSignMessageRequest_init_zero {_shiftcrypto_bitbox02_ETHCoin_MIN, {{NULL}, NULL}, {{NULL}, NULL}, false, shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_init_zero, 0}
#define shiftcrypto_bitbox02_ETHSignResponse_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_init_zero {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment_init_zero}
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member_init_zero {{{NULL}, NULL}, false, shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_init_zero}
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_ETHTypedMessageValueResponse_init_zero {_shiftcrypto_bitbox02_ETHTypedMessageValueResponse_RootObject_MIN, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_ETHTypedMessageValueRequest_init_zero {{{NULL}, NULL}, 0}
#define shiftcrypto_bitbox02_ETHRequest_init_zero {0, {shiftcrypto_bitbox02_ETHPubRequest_init_zero}}
#define shiftcrypto_bitbox02_ETHResponse_init_zero {0, {shiftcrypto_bitbox02_PubResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define shiftcrypto_bitbox02_ETHPubRequest_keypath_tag 1
#define shiftcrypto_bitbox02_ETHPubRequest_coin_tag 2
#define shiftcrypto_bitbox02_ETHPubRequest_output_type_tag 3
#define shiftcrypto_bitbox02_ETHPubRequest_display_tag 4
#define shiftcrypto_bitbox02_ETHPubRequest_contract_address_tag 5
#define shiftcrypto_bitbox02_ETHPubRequest_chain_id_tag 6
#define shiftcrypto_bitbox02_ETHSignRequest_coin_tag 1
#define shiftcrypto_bitbox02_ETHSignRequest_keypath_tag 2
#define shiftcrypto_bitbox02_ETHSignRequest_nonce_tag 3
#define shiftcrypto_bitbox02_ETHSignRequest_gas_price_tag 4
#define shiftcrypto_bitbox02_ETHSignRequest_gas_limit_tag 5
#define shiftcrypto_bitbox02_ETHSignRequest_recipient_tag 6
#define shiftcrypto_bitbox02_ETHSignRequest_value_tag 7
#define shiftcrypto_bitbox02_ETHSignRequest_data_tag 8
#define shiftcrypto_bitbox02_ETHSignRequest_host_nonce_commitment_tag 9
#define shiftcrypto_bitbox02_ETHSignRequest_chain_id_tag 10
#define shiftcrypto_bitbox02_ETHSignRequest_address_case_tag 11
#define shiftcrypto_bitbox02_ETHSignRequest_data_length_tag 12
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_chain_id_tag 1
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_keypath_tag 2
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_nonce_tag 3
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_max_priority_fee_per_gas_tag 4
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_max_fee_per_gas_tag 5
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_gas_limit_tag 6
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_recipient_tag 7
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_value_tag 8
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_data_tag 9
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_host_nonce_commitment_tag 10
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_address_case_tag 11
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_data_length_tag 12
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_payment_request_tag 13
#define shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse_offset_tag 1
#define shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse_length_tag 2
#define shiftcrypto_bitbox02_ETHSignDataResponseChunkRequest_chunk_tag 1
#define shiftcrypto_bitbox02_ETHSignMessageRequest_coin_tag 1
#define shiftcrypto_bitbox02_ETHSignMessageRequest_keypath_tag 2
#define shiftcrypto_bitbox02_ETHSignMessageRequest_msg_tag 3
#define shiftcrypto_bitbox02_ETHSignMessageRequest_host_nonce_commitment_tag 4
#define shiftcrypto_bitbox02_ETHSignMessageRequest_chain_id_tag 5
#define shiftcrypto_bitbox02_ETHSignResponse_signature_tag 1
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_chain_id_tag 1
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_keypath_tag 2
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_types_tag 3
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_primary_type_tag 4
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_host_nonce_commitment_tag 5
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_type_tag 1
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_size_tag 2
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_struct_name_tag 3
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_array_type_tag 4
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member_name_tag 1
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member_type_tag 2
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType_name_tag 1
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType_members_tag 2
#define shiftcrypto_bitbox02_ETHTypedMessageValueResponse_root_object_tag 1
#define shiftcrypto_bitbox02_ETHTypedMessageValueResponse_path_tag 2
#define shiftcrypto_bitbox02_ETHTypedMessageValueRequest_value_tag 1
#define shiftcrypto_bitbox02_ETHTypedMessageValueRequest_data_length_tag 2
#define shiftcrypto_bitbox02_ETHRequest_pub_tag  1
#define shiftcrypto_bitbox02_ETHRequest_sign_tag 2
#define shiftcrypto_bitbox02_ETHRequest_sign_msg_tag 3
#define shiftcrypto_bitbox02_ETHRequest_antiklepto_signature_tag 4
#define shiftcrypto_bitbox02_ETHRequest_sign_typed_msg_tag 5
#define shiftcrypto_bitbox02_ETHRequest_typed_msg_value_tag 6
#define shiftcrypto_bitbox02_ETHRequest_sign_eip1559_tag 7
#define shiftcrypto_bitbox02_ETHRequest_data_response_chunk_tag 8
#define shiftcrypto_bitbox02_ETHResponse_pub_tag 1
#define shiftcrypto_bitbox02_ETHResponse_sign_tag 2
#define shiftcrypto_bitbox02_ETHResponse_antiklepto_signer_commitment_tag 3
#define shiftcrypto_bitbox02_ETHResponse_typed_msg_value_tag 4
#define shiftcrypto_bitbox02_ETHResponse_data_request_chunk_tag 5

/* Struct field encoding specification for nanopb */
#define shiftcrypto_bitbox02_ETHPubRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   keypath,           1) \
X(a, STATIC,   SINGULAR, UENUM,    coin,              2) \
X(a, STATIC,   SINGULAR, UENUM,    output_type,       3) \
X(a, STATIC,   SINGULAR, BOOL,     display,           4) \
X(a, CALLBACK, SINGULAR, BYTES,    contract_address,   5) \
X(a, STATIC,   SINGULAR, UINT64,   chain_id,          6)
#define shiftcrypto_bitbox02_ETHPubRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_ETHPubRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_ETHSignRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    coin,              1) \
X(a, CALLBACK, REPEATED, UINT32,   keypath,           2) \
X(a, CALLBACK, SINGULAR, BYTES,    nonce,             3) \
X(a, CALLBACK, SINGULAR, BYTES,    gas_price,         4) \
X(a, CALLBACK, SINGULAR, BYTES,    gas_limit,         5) \
X(a, CALLBACK, SINGULAR, BYTES,    recipient,         6) \
X(a, CALLBACK, SINGULAR, BYTES,    value,             7) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  host_nonce_commitment,   9) \
X(a, STATIC,   SINGULAR, UINT64,   chain_id,         10) \
X(a, STATIC,   SINGULAR, UENUM,    address_case,     11) \
X(a, STATIC,   SINGULAR, UINT32,   data_length,      12)
#define shiftcrypto_bitbox02_ETHSignRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_ETHSignRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_ETHSignRequest_host_nonce_commitment_MSGTYPE shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment

#define shiftcrypto_bitbox02_ETHSignEIP1559Request_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   chain_id,          1) \
X(a, CALLBACK, REPEATED, UINT32,   keypath,           2) \
X(a, CALLBACK, SINGULAR, BYTES,    nonce,             3) \
X(a, CALLBACK, SINGULAR, BYTES,    max_priority_fee_per_gas,   4) \
X(a, CALLBACK, SINGULAR, BYTES,    max_fee_per_gas,   5) \
X(a, CALLBACK, SINGULAR, BYTES,    gas_limit,         6) \
X(a, CALLBACK, SINGULAR, BYTES,    recipient,         7) \
X(a, CALLBACK, SINGULAR, BYTES,    value,             8) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  host_nonce_commitment,  10) \
X(a, STATIC,   SINGULAR, UENUM,    address_case,     11) \
X(a, STATIC,   SINGULAR, UINT32,   data_length,      12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  payment_request,  13)
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_DEFAULT NULL
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_host_nonce_commitment_MSGTYPE shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_payment_request_MSGTYPE shiftcrypto_bitbox02_BTCPaymentRequestRequest

#define shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            1) \
X(a, STATIC,   SINGULAR, UINT32,   length,            2)
#define shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse_CALLBACK NULL
#define shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse_DEFAULT NULL

#define shiftcrypto_bitbox02_ETHSignDataResponseChunkRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    chunk,             1)
#define shiftcrypto_bitbox02_ETHSignDataResponseChunkRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_ETHSignDataResponseChunkRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_ETHSignMessageRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    coin,              1) \
X(a, CALLBACK, REPEATED, UINT32,   keypath,           2) \
X(a, CALLBACK, SINGULAR, BYTES,    msg,               3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  host_nonce_commitment,   4) \
X(a, STATIC,   SINGULAR, UINT64,   chain_id,          5)
#define shiftcrypto_bitbox02_ETHSignMessageRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_ETHSignMessageRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_ETHSignMessageRequest_host_nonce_commitment_MSGTYPE shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment

#define shiftcrypto_bitbox02_ETHSignResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    signature,         1)
#define shiftcrypto_bitbox02_ETHSignResponse_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_ETHSignResponse_DEFAULT NULL

#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   chain_id,          1) \
X(a, CALLBACK, REPEATED, UINT32,   keypath,           2) \
X(a, CALLBACK, REPEATED, MESSAGE,  types,             3) \
X(a, CALLBACK, SINGULAR, STRING,   primary_type,      4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  host_nonce_commitment,   5)
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_types_MSGTYPE shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_host_nonce_commitment_MSGTYPE shiftcrypto_bitbox02_AntiKleptoHostNonceCommitment

#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UENUM,    type,              1) \
X(a, CALLBACK, SINGULAR, UINT32,   size,              2) \
X(a, CALLBACK, SINGULAR, STRING,   struct_name,       3) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  array_type,        4)
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_DEFAULT NULL
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_array_type_MSGTYPE shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType

#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  type,              2)
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member_DEFAULT NULL
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member_type_MSGTYPE shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType

#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  members,           2)
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType_DEFAULT NULL
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType_members_MSGTYPE shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member

#define shiftcrypto_bitbox02_ETHTypedMessageValueResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    root_object,       1) \
X(a, CALLBACK, REPEATED, UINT32,   path,              2)
#define shiftcrypto_bitbox02_ETHTypedMessageValueResponse_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_ETHTypedMessageValueResponse_DEFAULT NULL

#define shiftcrypto_bitbox02_ETHTypedMessageValueRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    value,             1) \
X(a, STATIC,   SINGULAR, UINT32,   data_length,       2)
#define shiftcrypto_bitbox02_ETHTypedMessageValueRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_ETHTypedMessageValueRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_ETHRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,pub,request.pub),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,sign,request.sign),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,sign_msg,request.sign_msg),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,antiklepto_signature,request.antiklepto_signature),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,sign_typed_msg,request.sign_typed_msg),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,typed_msg_value,request.typed_msg_value),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,sign_eip1559,request.sign_eip1559),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,data_response_chunk,request.data_response_chunk),   8)
#define shiftcrypto_bitbox02_ETHRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_ETHRequest_DEFAULT NULL
#define shiftcrypto_bitbox02_ETHRequest_request_pub_MSGTYPE shiftcrypto_bitbox02_ETHPubRequest
#define shiftcrypto_bitbox02_ETHRequest_request_sign_MSGTYPE shiftcrypto_bitbox02_ETHSignRequest
#define shiftcrypto_bitbox02_ETHRequest_request_sign_msg_MSGTYPE shiftcrypto_bitbox02_ETHSignMessageRequest
#define shiftcrypto_bitbox02_ETHRequest_request_antiklepto_signature_MSGTYPE shiftcrypto_bitbox02_AntiKleptoSignatureRequest
#define shiftcrypto_bitbox02_ETHRequest_request_sign_typed_msg_MSGTYPE shiftcrypto_bitbox02_ETHSignTypedMessageRequest
#define shiftcrypto_bitbox02_ETHRequest_request_typed_msg_value_MSGTYPE shiftcrypto_bitbox02_ETHTypedMessageValueRequest
#define shiftcrypto_bitbox02_ETHRequest_request_sign_eip1559_MSGTYPE shiftcrypto_bitbox02_ETHSignEIP1559Request
#define shiftcrypto_bitbox02_ETHRequest_request_data_response_chunk_MSGTYPE shiftcrypto_bitbox02_ETHSignDataResponseChunkRequest

#define shiftcrypto_bitbox02_ETHResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,pub,response.pub),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,sign,response.sign),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,antiklepto_signer_commitment,response.antiklepto_signer_commitment),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,typed_msg_value,response.typed_msg_value),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,data_request_chunk,response.data_request_chunk),   5)
#define shiftcrypto_bitbox02_ETHResponse_CALLBACK NULL
#define shiftcrypto_bitbox02_ETHResponse_DEFAULT NULL
#define shiftcrypto_bitbox02_ETHResponse_response_pub_MSGTYPE shiftcrypto_bitbox02_PubResponse
#define shiftcrypto_bitbox02_ETHResponse_response_sign_MSGTYPE shiftcrypto_bitbox02_ETHSignResponse
#define shiftcrypto_bitbox02_ETHResponse_response_antiklepto_signer_commitment_MSGTYPE shiftcrypto_bitbox02_AntiKleptoSignerCommitment
#define shiftcrypto_bitbox02_ETHResponse_response_typed_msg_value_MSGTYPE shiftcrypto_bitbox02_ETHTypedMessageValueResponse
#define shiftcrypto_bitbox02_ETHResponse_response_data_request_chunk_MSGTYPE shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse

extern const pb_msgdesc_t shiftcrypto_bitbox02_ETHPubRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ETHSignRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ETHSignEIP1559Request_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ETHSignDataResponseChunkRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ETHSignMessageRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ETHSignResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ETHSignTypedMessageRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ETHTypedMessageValueResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ETHTypedMessageValueRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ETHRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ETHResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define shiftcrypto_bitbox02_ETHPubRequest_fields &shiftcrypto_bitbox02_ETHPubRequest_msg
#define shiftcrypto_bitbox02_ETHSignRequest_fields &shiftcrypto_bitbox02_ETHSignRequest_msg
#define shiftcrypto_bitbox02_ETHSignEIP1559Request_fields &shiftcrypto_bitbox02_ETHSignEIP1559Request_msg
#define shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse_fields &shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse_msg
#define shiftcrypto_bitbox02_ETHSignDataResponseChunkRequest_fields &shiftcrypto_bitbox02_ETHSignDataResponseChunkRequest_msg
#define shiftcrypto_bitbox02_ETHSignMessageRequest_fields &shiftcrypto_bitbox02_ETHSignMessageRequest_msg
#define shiftcrypto_bitbox02_ETHSignResponse_fields &shiftcrypto_bitbox02_ETHSignResponse_msg
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_fields &shiftcrypto_bitbox02_ETHSignTypedMessageRequest_msg
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_fields &shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_msg
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member_fields &shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member_msg
#define shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType_fields &shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType_msg
#define shiftcrypto_bitbox02_ETHTypedMessageValueResponse_fields &shiftcrypto_bitbox02_ETHTypedMessageValueResponse_msg
#define shiftcrypto_bitbox02_ETHTypedMessageValueRequest_fields &shiftcrypto_bitbox02_ETHTypedMessageValueRequest_msg
#define shiftcrypto_bitbox02_ETHRequest_fields &shiftcrypto_bitbox02_ETHRequest_msg
#define shiftcrypto_bitbox02_ETHResponse_fields &shiftcrypto_bitbox02_ETHResponse_msg

/* Maximum encoded size of messages (where known) */
/* shiftcrypto_bitbox02_ETHPubRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_ETHSignRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_ETHSignEIP1559Request_size depends on runtime parameters */
/* shiftcrypto_bitbox02_ETHSignDataResponseChunkRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_ETHSignMessageRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_ETHSignResponse_size depends on runtime parameters */
/* shiftcrypto_bitbox02_ETHSignTypedMessageRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_ETHSignTypedMessageRequest_MemberType_size depends on runtime parameters */
/* shiftcrypto_bitbox02_ETHSignTypedMessageRequest_Member_size depends on runtime parameters */
/* shiftcrypto_bitbox02_ETHSignTypedMessageRequest_StructType_size depends on runtime parameters */
/* shiftcrypto_bitbox02_ETHTypedMessageValueResponse_size depends on runtime parameters */
/* shiftcrypto_bitbox02_ETHTypedMessageValueRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_ETHRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_ETHResponse_size depends on runtime parameters */
#define SHIFTCRYPTO_BITBOX02_ETH_PB_H_MAX_SIZE   shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse_size
#define shiftcrypto_bitbox02_ETHSignDataRequestChunkResponse_size 12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
