/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SHIFTCRYPTO_BITBOX02_HWW_PB_H_INCLUDED
#define PB_SHIFTCRYPTO_BITBOX02_HWW_PB_H_INCLUDED
#include <pb.h>
#include "common.pb.h"
#include "backup_commands.pb.h"
#include "bitbox02_system.pb.h"
#include "bitboxsync.pb.h"
#include "bluetooth.pb.h"
#include "btc.pb.h"
#include "cardano.pb.h"
#include "eth.pb.h"
#include "keystore.pb.h"
#include "mnemonic.pb.h"
#include "system.pb.h"
#include "perform_attestation.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _shiftcrypto_bitbox02_Error {
    int32_t code;
    char message[256];
} shiftcrypto_bitbox02_Error;

typedef struct _shiftcrypto_bitbox02_Success {
    char dummy_field;
} shiftcrypto_bitbox02_Success;

typedef struct _shiftcrypto_bitbox02_Request {
    pb_size_t which_request;
    union {
        /* removed: RandomNumberRequest random_number = 1; */
        shiftcrypto_bitbox02_SetDeviceNameRequest device_name;
        shiftcrypto_bitbox02_SetDeviceLanguageRequest device_language;
        shiftcrypto_bitbox02_DeviceInfoRequest device_info;
        shiftcrypto_bitbox02_SetPasswordRequest set_password;
        shiftcrypto_bitbox02_CreateBackupRequest create_backup;
        shiftcrypto_bitbox02_ShowMnemonicRequest show_mnemonic;
        shiftcrypto_bitbox02_BTCPubRequest btc_pub;
        shiftcrypto_bitbox02_BTCSignInitRequest btc_sign_init;
        shiftcrypto_bitbox02_BTCSignInputRequest btc_sign_input;
        shiftcrypto_bitbox02_BTCSignOutputRequest btc_sign_output;
        shiftcrypto_bitbox02_InsertRemoveSDCardRequest insert_remove_sdcard;
        shiftcrypto_bitbox02_CheckSDCardRequest check_sdcard;
        shiftcrypto_bitbox02_SetMnemonicPassphraseEnabledRequest set_mnemonic_passphrase_enabled;
        shiftcrypto_bitbox02_ListBackupsRequest list_backups;
        shiftcrypto_bitbox02_RestoreBackupRequest restore_backup;
        shiftcrypto_bitbox02_PerformAttestationRequest perform_attestation;
        shiftcrypto_bitbox02_RebootRequest reboot;
        shiftcrypto_bitbox02_CheckBackupRequest check_backup;
        shiftcrypto_bitbox02_ETHRequest eth;
        shiftcrypto_bitbox02_ResetRequest reset;
        shiftcrypto_bitbox02_RestoreFromMnemonicRequest restore_from_mnemonic;
        /* removed: BitBoxBaseRequest bitboxbase = 23; */
        shiftcrypto_bitbox02_RootFingerprintRequest fingerprint;
        shiftcrypto_bitbox02_BTCRequest btc;
        shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest electrum_encryption_key;
        shiftcrypto_bitbox02_CardanoRequest cardano;
        shiftcrypto_bitbox02_BIP85Request bip85;
        shiftcrypto_bitbox02_BluetoothRequest bluetooth;
        shiftcrypto_bitbox02_ChangePasswordRequest change_password;
        shiftcrypto_bitbox02_BitBoxSyncRequest bitbox_sync;
    } request;
} shiftcrypto_bitbox02_Request;

typedef struct _shiftcrypto_bitbox02_Response {
    pb_size_t which_response;
    union {
        shiftcrypto_bitbox02_Success success;
        shiftcrypto_bitbox02_Error error;
        /* removed: RandomNumberResponse random_number = 3; */
        shiftcrypto_bitbox02_DeviceInfoResponse device_info;
        shiftcrypto_bitbox02_PubResponse pub;
        shiftcrypto_bitbox02_BTCSignNextResponse btc_sign_next;
        shiftcrypto_bitbox02_ListBackupsResponse list_backups;
        shiftcrypto_bitbox02_CheckBackupResponse check_backup;
        shiftcrypto_bitbox02_PerformAttestationResponse perform_attestation;
        shiftcrypto_bitbox02_CheckSDCardResponse check_sdcard;
        shiftcrypto_bitbox02_ETHResponse eth;
        shiftcrypto_bitbox02_RootFingerprintResponse fingerprint;
        shiftcrypto_bitbox02_BTCResponse btc;
        shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse electrum_encryption_key;
        shiftcrypto_bitbox02_CardanoResponse cardano;
        shiftcrypto_bitbox02_BIP85Response bip85;
        shiftcrypto_bitbox02_BluetoothResponse bluetooth;
        shiftcrypto_bitbox02_BitBoxSyncResponse bitbox_sync;
    } response;
} shiftcrypto_bitbox02_Response;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define shiftcrypto_bitbox02_Error_init_default  {0, ""}
#define shiftcrypto_bitbox02_Success_init_default {0}
#define shiftcrypto_bitbox02_Request_init_default {0, {shiftcrypto_bitbox02_SetDeviceNameRequest_init_default}}
#define shiftcrypto_bitbox02_Response_init_default {0, {shiftcrypto_bitbox02_Success_init_default}}
#define shiftcrypto_bitbox02_Error_init_zero     {0, ""}
#define shiftcrypto_bitbox02_Success_init_zero   {0}
#define shiftcrypto_bitbox02_Request_init_zero   {0, {shiftcrypto_bitbox02_SetDeviceNameRequest_init_zero}}
#define shiftcrypto_bitbox02_Response_init_zero  {0, {shiftcrypto_bitbox02_Success_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define shiftcrypto_bitbox02_Error_code_tag      1
#define shiftcrypto_bitbox02_Error_message_tag   2
#define shiftcrypto_bitbox02_Request_device_name_tag 2
#define shiftcrypto_bitbox02_Request_device_language_tag 3
#define shiftcrypto_bitbox02_Request_device_info_tag 4
#define shiftcrypto_bitbox02_Request_set_password_tag 5
#define shiftcrypto_bitbox02_Request_create_backup_tag 6
#define shiftcrypto_bitbox02_Request_show_mnemonic_tag 7
#define shiftcrypto_bitbox02_Request_btc_pub_tag 8
#define shiftcrypto_bitbox02_Request_btc_sign_init_tag 9
#define shiftcrypto_bitbox02_Request_btc_sign_input_tag 10
#define shiftcrypto_bitbox02_Request_btc_sign_output_tag 11
#define shiftcrypto_bitbox02_Request_insert_remove_sdcard_tag 12
#define shiftcrypto_bitbox02_Request_check_sdcard_tag 13
#define shiftcrypto_bitbox02_Request_set_mnemonic_passphrase_enabled_tag 14
#define shiftcrypto_bitbox02_Request_list_backups_tag 15
#define shiftcrypto_bitbox02_Request_restore_backup_tag 16
#define shiftcrypto_bitbox02_Request_perform_attestation_tag 17
#define shiftcrypto_bitbox02_Request_reboot_tag  18
#define shiftcrypto_bitbox02_Request_check_backup_tag 19
#define shiftcrypto_bitbox02_Request_eth_tag     20
#define shiftcrypto_bitbox02_Request_reset_tag   21
#define shiftcrypto_bitbox02_Request_restore_from_mnemonic_tag 22
#define shiftcrypto_bitbox02_Request_fingerprint_tag 24
#define shiftcrypto_bitbox02_Request_btc_tag     25
#define shiftcrypto_bitbox02_Request_electrum_encryption_key_tag 26
#define shiftcrypto_bitbox02_Request_cardano_tag 27
#define shiftcrypto_bitbox02_Request_bip85_tag   28
#define shiftcrypto_bitbox02_Request_bluetooth_tag 29
#define shiftcrypto_bitbox02_Request_change_password_tag 30
#define shiftcrypto_bitbox02_Request_bitbox_sync_tag 31
#define shiftcrypto_bitbox02_Response_success_tag 1
#define shiftcrypto_bitbox02_Response_error_tag  2
#define shiftcrypto_bitbox02_Response_device_info_tag 4
#define shiftcrypto_bitbox02_Response_pub_tag    5
#define shiftcrypto_bitbox02_Response_btc_sign_next_tag 6
#define shiftcrypto_bitbox02_Response_list_backups_tag 7
#define shiftcrypto_bitbox02_Response_check_backup_tag 8
#define shiftcrypto_bitbox02_Response_perform_attestation_tag 9
#define shiftcrypto_bitbox02_Response_check_sdcard_tag 10
#define shiftcrypto_bitbox02_Response_eth_tag    11
#define shiftcrypto_bitbox02_Response_fingerprint_tag 12
#define shiftcrypto_bitbox02_Response_btc_tag    13
#define shiftcrypto_bitbox02_Response_electrum_encryption_key_tag 14
#define shiftcrypto_bitbox02_Response_cardano_tag 15
#define shiftcrypto_bitbox02_Response_bip85_tag  16
#define shiftcrypto_bitbox02_Response_bluetooth_tag 17
#define shiftcrypto_bitbox02_Response_bitbox_sync_tag 18

/* Struct field encoding specification for nanopb */
#define shiftcrypto_bitbox02_Error_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    code,              1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2)
#define shiftcrypto_bitbox02_Error_CALLBACK NULL
#define shiftcrypto_bitbox02_Error_DEFAULT NULL

#define shiftcrypto_bitbox02_Success_FIELDLIST(X, a) \

#define shiftcrypto_bitbox02_Success_CALLBACK NULL
#define shiftcrypto_bitbox02_Success_DEFAULT NULL

#define shiftcrypto_bitbox02_Request_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,device_name,request.device_name),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,device_language,request.device_language),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,device_info,request.device_info),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,set_password,request.set_password),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,create_backup,request.create_backup),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,show_mnemonic,request.show_mnemonic),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,btc_pub,request.btc_pub),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,btc_sign_init,request.btc_sign_init),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,btc_sign_input,request.btc_sign_input),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,btc_sign_output,request.btc_sign_output),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,insert_remove_sdcard,request.insert_remove_sdcard),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,check_sdcard,request.check_sdcard),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,set_mnemonic_passphrase_enabled,request.set_mnemonic_passphrase_enabled),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,list_backups,request.list_backups),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,restore_backup,request.restore_backup),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,perform_attestation,request.perform_attestation),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,reboot,request.reboot),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,check_backup,request.check_backup),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,eth,request.eth),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,reset,request.reset),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,restore_from_mnemonic,request.restore_from_mnemonic),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,fingerprint,request.fingerprint),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,btc,request.btc),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,electrum_encryption_key,request.electrum_encryption_key),  26) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,cardano,request.cardano),  27) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,bip85,request.bip85),  28) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,bluetooth,request.bluetooth),  29) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,change_password,request.change_password),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,bitbox_sync,request.bitbox_sync),  31)
#define shiftcrypto_bitbox02_Request_CALLBACK NULL
#define shiftcrypto_bitbox02_Request_DEFAULT NULL
#define shiftcrypto_bitbox02_Request_request_device_name_MSGTYPE shiftcrypto_bitbox02_SetDeviceNameRequest
#define shiftcrypto_bitbox02_Request_request_device_language_MSGTYPE shiftcrypto_bitbox02_SetDeviceLanguageRequest
#define shiftcrypto_bitbox02_Request_request_device_info_MSGTYPE shiftcrypto_bitbox02_DeviceInfoRequest
#define shiftcrypto_bitbox02_Request_request_set_password_MSGTYPE shiftcrypto_bitbox02_SetPasswordRequest
#define shiftcrypto_bitbox02_Request_request_create_backup_MSGTYPE shiftcrypto_bitbox02_CreateBackupRequest
#define shiftcrypto_bitbox02_Request_request_show_mnemonic_MSGTYPE shiftcrypto_bitbox02_ShowMnemonicRequest
#define shiftcrypto_bitbox02_Request_request_btc_pub_MSGTYPE shiftcrypto_bitbox02_BTCPubRequest
#define shiftcrypto_bitbox02_Request_request_btc_sign_init_MSGTYPE shiftcrypto_bitbox02_BTCSignInitRequest
#define shiftcrypto_bitbox02_Request_request_btc_sign_input_MSGTYPE shiftcrypto_bitbox02_BTCSignInputRequest
#define shiftcrypto_bitbox02_Request_request_btc_sign_output_MSGTYPE shiftcrypto_bitbox02_BTCSignOutputRequest
#define shiftcrypto_bitbox02_Request_request_insert_remove_sdcard_MSGTYPE shiftcrypto_bitbox02_InsertRemoveSDCardRequest
#define shiftcrypto_bitbox02_Request_request_check_sdcard_MSGTYPE shiftcrypto_bitbox02_CheckSDCardRequest
#define shiftcrypto_bitbox02_Request_request_set_mnemonic_passphrase_enabled_MSGTYPE shiftcrypto_bitbox02_SetMnemonicPassphraseEnabledRequest
#define shiftcrypto_bitbox02_Request_request_list_backups_MSGTYPE shiftcrypto_bitbox02_ListBackupsRequest
#define shiftcrypto_bitbox02_Request_request_restore_backup_MSGTYPE shiftcrypto_bitbox02_RestoreBackupRequest
#define shiftcrypto_bitbox02_Request_request_perform_attestation_MSGTYPE shiftcrypto_bitbox02_PerformAttestationRequest
#define shiftcrypto_bitbox02_Request_request_reboot_MSGTYPE shiftcrypto_bitbox02_RebootRequest
#define shiftcrypto_bitbox02_Request_request_check_backup_MSGTYPE shiftcrypto_bitbox02_CheckBackupRequest
#define shiftcrypto_bitbox02_Request_request_eth_MSGTYPE shiftcrypto_bitbox02_ETHRequest
#define shiftcrypto_bitbox02_Request_request_reset_MSGTYPE shiftcrypto_bitbox02_ResetRequest
#define shiftcrypto_bitbox02_Request_request_restore_from_mnemonic_MSGTYPE shiftcrypto_bitbox02_RestoreFromMnemonicRequest
#define shiftcrypto_bitbox02_Request_request_fingerprint_MSGTYPE shiftcrypto_bitbox02_RootFingerprintRequest
#define shiftcrypto_bitbox02_Request_request_btc_MSGTYPE shiftcrypto_bitbox02_BTCRequest
#define shiftcrypto_bitbox02_Request_request_electrum_encryption_key_MSGTYPE shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest
#define shiftcrypto_bitbox02_Request_request_cardano_MSGTYPE shiftcrypto_bitbox02_CardanoRequest
#define shiftcrypto_bitbox02_Request_request_bip85_MSGTYPE shiftcrypto_bitbox02_BIP85Request
#define shiftcrypto_bitbox02_Request_request_bluetooth_MSGTYPE shiftcrypto_bitbox02_BluetoothRequest
#define shiftcrypto_bitbox02_Request_request_change_password_MSGTYPE shiftcrypto_bitbox02_ChangePasswordRequest
#define shiftcrypto_bitbox02_Request_request_bitbox_sync_MSGTYPE shiftcrypto_bitbox02_BitBoxSyncRequest

#define shiftcrypto_bitbox02_Response_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,success,response.success),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,error,response.error),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,device_info,response.device_info),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,pub,response.pub),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,btc_sign_next,response.btc_sign_next),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,list_backups,response.list_backups),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,check_backup,response.check_backup),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,perform_attestation,response.perform_attestation),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,check_sdcard,response.check_sdcard),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,eth,response.eth),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,fingerprint,response.fingerprint),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,btc,response.btc),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,electrum_encryption_key,response.electrum_encryption_key),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,cardano,response.cardano),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,bip85,response.bip85),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,bluetooth,response.bluetooth),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,bitbox_sync,response.bitbox_sync),  18)
#define shiftcrypto_bitbox02_Response_CALLBACK NULL
#define shiftcrypto_bitbox02_Response_DEFAULT NULL
#define shiftcrypto_bitbox02_Response_response_success_MSGTYPE shiftcrypto_bitbox02_Success
#define shiftcrypto_bitbox02_Response_response_error_MSGTYPE shiftcrypto_bitbox02_Error
#define shiftcrypto_bitbox02_Response_response_device_info_MSGTYPE shiftcrypto_bitbox02_DeviceInfoResponse
#define shiftcrypto_bitbox02_Response_response_pub_MSGTYPE shiftcrypto_bitbox02_PubResponse
#define shiftcrypto_bitbox02_Response_response_btc_sign_next_MSGTYPE shiftcrypto_bitbox02_BTCSignNextResponse
#define shiftcrypto_bitbox02_Response_response_list_backups_MSGTYPE shiftcrypto_bitbox02_ListBackupsResponse
#define shiftcrypto_bitbox02_Response_response_check_backup_MSGTYPE shiftcrypto_bitbox02_CheckBackupResponse
#define shiftcrypto_bitbox02_Response_response_perform_attestation_MSGTYPE shiftcrypto_bitbox02_PerformAttestationResponse
#define shiftcrypto_bitbox02_Response_response_check_sdcard_MSGTYPE shiftcrypto_bitbox02_CheckSDCardResponse
#define shiftcrypto_bitbox02_Response_response_eth_MSGTYPE shiftcrypto_bitbox02_ETHResponse
#define shiftcrypto_bitbox02_Response_response_fingerprint_MSGTYPE shiftcrypto_bitbox02_RootFingerprintResponse
#define shiftcrypto_bitbox02_Response_response_btc_MSGTYPE shiftcrypto_bitbox02_BTCResponse
#define shiftcrypto_bitbox02_Response_response_electrum_encryption_key_MSGTYPE shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse
#define shiftcrypto_bitbox02_Response_response_cardano_MSGTYPE shiftcrypto_bitbox02_CardanoResponse
#define shiftcrypto_bitbox02_Response_response_bip85_MSGTYPE shiftcrypto_bitbox02_BIP85Response
#define shiftcrypto_bitbox02_Response_response_bluetooth_MSGTYPE shiftcrypto_bitbox02_BluetoothResponse
#define shiftcrypto_bitbox02_Response_response_bitbox_sync_MSGTYPE shiftcrypto_bitbox02_BitBoxSyncResponse

extern const pb_msgdesc_t shiftcrypto_bitbox02_Error_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_Success_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_Request_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define shiftcrypto_bitbox02_Error_fields &shiftcrypto_bitbox02_Error_msg
#define shiftcrypto_bitbox02_Success_fields &shiftcrypto_bitbox02_Success_msg
#define shiftcrypto_bitbox02_Request_fields &shiftcrypto_bitbox02_Request_msg
#define shiftcrypto_bitbox02_Response_fields &shiftcrypto_bitbox02_Response_msg

/* Maximum encoded size of messages (where known) */
#if defined(shiftcrypto_bitbox02_SetDeviceNameRequest_size) && defined(shiftcrypto_bitbox02_SetDeviceLanguageRequest_size) && defined(shiftcrypto_bitbox02_SetPasswordRequest_size) && defined(shiftcrypto_bitbox02_BTCPubRequest_size) && defined(shiftcrypto_bitbox02_BTCSignInitRequest_size) && defined(shiftcrypto_bitbox02_BTCSignOutputRequest_size) && defined(shiftcrypto_bitbox02_RestoreBackupRequest_size) && defined(shiftcrypto_bitbox02_PerformAttestationRequest_size) && defined(shiftcrypto_bitbox02_ETHRequest_size) && defined(shiftcrypto_bitbox02_BTCRequest_size) && defined(shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest_size) && defined(shiftcrypto_bitbox02_CardanoRequest_size) && defined(shiftcrypto_bitbox02_BluetoothRequest_size) && defined(shiftcrypto_bitbox02_BitBoxSyncRequest_size)
union shiftcrypto_bitbox02_Request_request_size_union {char f2[(6 + shiftcrypto_bitbox02_SetDeviceNameRequest_size)]; char f3[(6 + shiftcrypto_bitbox02_SetDeviceLanguageRequest_size)]; char f5[(6 + shiftcrypto_bitbox02_SetPasswordRequest_size)]; char f8[(6 + shiftcrypto_bitbox02_BTCPubRequest_size)]; char f9[(6 + shiftcrypto_bitbox02_BTCSignInitRequest_size)]; char f11[(6 + shiftcrypto_bitbox02_BTCSignOutputRequest_size)]; char f16[(7 + shiftcrypto_bitbox02_RestoreBackupRequest_size)]; char f17[(7 + shiftcrypto_bitbox02_PerformAttestationRequest_size)]; char f20[(7 + shiftcrypto_bitbox02_ETHRequest_size)]; char f25[(7 + shiftcrypto_bitbox02_BTCRequest_size)]; char f26[(7 + shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest_size)]; char f27[(7 + shiftcrypto_bitbox02_CardanoRequest_size)]; char f29[(7 + shiftcrypto_bitbox02_BluetoothRequest_size)]; char f31[(7 + shiftcrypto_bitbox02_BitBoxSyncRequest_size)]; char f0[294];};
#endif
#if defined(shiftcrypto_bitbox02_BTCSignNextResponse_size) && defined(shiftcrypto_bitbox02_CheckBackupResponse_size) && defined(shiftcrypto_bitbox02_PerformAttestationResponse_size) && defined(shiftcrypto_bitbox02_ETHResponse_size) && defined(shiftcrypto_bitbox02_BTCResponse_size) && defined(shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse_size) && defined(shiftcrypto_bitbox02_CardanoResponse_size) && defined(shiftcrypto_bitbox02_BIP85Response_size) && defined(shiftcrypto_bitbox02_BitBoxSyncResponse_size)
union shiftcrypto_bitbox02_Response_response_size_union {char f6[(6 + shiftcrypto_bitbox02_BTCSignNextResponse_size)]; char f8[(6 + shiftcrypto_bitbox02_CheckBackupResponse_size)]; char f9[(6 + shiftcrypto_bitbox02_PerformAttestationResponse_size)]; char f11[(6 + shiftcrypto_bitbox02_ETHResponse_size)]; char f13[(6 + shiftcrypto_bitbox02_BTCResponse_size)]; char f14[(6 + shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse_size)]; char f15[(6 + shiftcrypto_bitbox02_CardanoResponse_size)]; char f16[(7 + shiftcrypto_bitbox02_BIP85Response_size)]; char f18[(7 + shiftcrypto_bitbox02_BitBoxSyncResponse_size)]; char f0[15683];};
#endif
#define SHIFTCRYPTO_BITBOX02_HWW_PB_H_MAX_SIZE   shiftcrypto_bitbox02_Error_size
#define shiftcrypto_bitbox02_Error_size          269
#define shiftcrypto_bitbox02_Success_size        0
#if defined(shiftcrypto_bitbox02_SetDeviceNameRequest_size) && defined(shiftcrypto_bitbox02_SetDeviceLanguageRequest_size) && defined(shiftcrypto_bitbox02_SetPasswordRequest_size) && defined(shiftcrypto_bitbox02_BTCPubRequest_size) && defined(shiftcrypto_bitbox02_BTCSignInitRequest_size) && defined(shiftcrypto_bitbox02_BTCSignOutputRequest_size) && defined(shiftcrypto_bitbox02_RestoreBackupRequest_size) && defined(shiftcrypto_bitbox02_PerformAttestationRequest_size) && defined(shiftcrypto_bitbox02_ETHRequest_size) && defined(shiftcrypto_bitbox02_BTCRequest_size) && defined(shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest_size) && defined(shiftcrypto_bitbox02_CardanoRequest_size) && defined(shiftcrypto_bitbox02_BluetoothRequest_size) && defined(shiftcrypto_bitbox02_BitBoxSyncRequest_size)
#define shiftcrypto_bitbox02_Request_size        (0 + sizeof(union shiftcrypto_bitbox02_Request_request_size_union))
#endif
#if defined(shiftcrypto_bitbox02_BTCSignNextResponse_size) && defined(shiftcrypto_bitbox02_CheckBackupResponse_size) && defined(shiftcrypto_bitbox02_PerformAttestationResponse_size) && defined(shiftcrypto_bitbox02_ETHResponse_size) && defined(shiftcrypto_bitbox02_BTCResponse_size) && defined(shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse_size) && defined(shiftcrypto_bitbox02_CardanoResponse_size) && defined(shiftcrypto_bitbox02_BIP85Response_size) && defined(shiftcrypto_bitbox02_BitBoxSyncResponse_size)
#define shiftcrypto_bitbox02_Response_size       (0 + sizeof(union shiftcrypto_bitbox02_Response_response_size_union))
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
