/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "hww.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(shiftcrypto_bitbox02_Error, shiftcrypto_bitbox02_Error, 2)


PB_BIND(shiftcrypto_bitbox02_Success, shiftcrypto_bitbox02_Success, AUTO)


PB_BIND(shiftcrypto_bitbox02_Request, shiftcrypto_bitbox02_Request, 2)


PB_BIND(shiftcrypto_bitbox02_Response, shiftcrypto_bitbox02_Response, 4)



