/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "keystore.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest, shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse, shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse, AUTO)


PB_BIND(shiftcrypto_bitbox02_BIP85Request, shiftcrypto_bitbox02_BIP85Request, AUTO)


PB_BIND(shiftcrypto_bitbox02_BIP85Request_AppLn, shiftcrypto_bitbox02_BIP85Request_AppLn, AUTO)


PB_BIND(shiftcrypto_bitbox02_BIP85Response, shiftcrypto_bitbox02_BIP85Response, AUTO)



