/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SHIFTCRYPTO_BITBOX02_KEYSTORE_PB_H_INCLUDED
#define PB_SHIFTCRYPTO_BITBOX02_KEYSTORE_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/empty.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest {
    pb_callback_t keypath;
} shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest;

typedef struct _shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse {
    pb_callback_t key;
} shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse;

typedef struct _shiftcrypto_bitbox02_BIP85Request_AppLn {
    uint32_t account_number;
} shiftcrypto_bitbox02_BIP85Request_AppLn;

typedef struct _shiftcrypto_bitbox02_BIP85Request {
    pb_size_t which_app;
    union {
        google_protobuf_Empty bip39;
        shiftcrypto_bitbox02_BIP85Request_AppLn ln;
    } app;
} shiftcrypto_bitbox02_BIP85Request;

typedef struct _shiftcrypto_bitbox02_BIP85Response {
    pb_size_t which_app;
    union {
        google_protobuf_Empty bip39;
        pb_callback_t ln;
    } app;
} shiftcrypto_bitbox02_BIP85Response;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BIP85Request_init_default {0, {google_protobuf_Empty_init_default}}
#define shiftcrypto_bitbox02_BIP85Request_AppLn_init_default {0}
#define shiftcrypto_bitbox02_BIP85Response_init_default {0, {google_protobuf_Empty_init_default}}
#define shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_BIP85Request_init_zero {0, {google_protobuf_Empty_init_zero}}
#define shiftcrypto_bitbox02_BIP85Request_AppLn_init_zero {0}
#define shiftcrypto_bitbox02_BIP85Response_init_zero {0, {google_protobuf_Empty_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest_keypath_tag 1
#define shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse_key_tag 1
#define shiftcrypto_bitbox02_BIP85Request_AppLn_account_number_tag 1
#define shiftcrypto_bitbox02_BIP85Request_bip39_tag 1
#define shiftcrypto_bitbox02_BIP85Request_ln_tag 2
#define shiftcrypto_bitbox02_BIP85Response_bip39_tag 1
#define shiftcrypto_bitbox02_BIP85Response_ln_tag 2

/* Struct field encoding specification for nanopb */
#define shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   keypath,           1)
#define shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1)
#define shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse_DEFAULT NULL

#define shiftcrypto_bitbox02_BIP85Request_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (app,bip39,app.bip39),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (app,ln,app.ln),   2)
#define shiftcrypto_bitbox02_BIP85Request_CALLBACK NULL
#define shiftcrypto_bitbox02_BIP85Request_DEFAULT NULL
#define shiftcrypto_bitbox02_BIP85Request_app_bip39_MSGTYPE google_protobuf_Empty
#define shiftcrypto_bitbox02_BIP85Request_app_ln_MSGTYPE shiftcrypto_bitbox02_BIP85Request_AppLn

#define shiftcrypto_bitbox02_BIP85Request_AppLn_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   account_number,    1)
#define shiftcrypto_bitbox02_BIP85Request_AppLn_CALLBACK NULL
#define shiftcrypto_bitbox02_BIP85Request_AppLn_DEFAULT NULL

#define shiftcrypto_bitbox02_BIP85Response_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (app,bip39,app.bip39),   1) \
X(a, CALLBACK, ONEOF,    BYTES,    (app,ln,app.ln),   2)
#define shiftcrypto_bitbox02_BIP85Response_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_BIP85Response_DEFAULT NULL
#define shiftcrypto_bitbox02_BIP85Response_app_bip39_MSGTYPE google_protobuf_Empty

extern const pb_msgdesc_t shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BIP85Request_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BIP85Request_AppLn_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_BIP85Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest_fields &shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest_msg
#define shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse_fields &shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse_msg
#define shiftcrypto_bitbox02_BIP85Request_fields &shiftcrypto_bitbox02_BIP85Request_msg
#define shiftcrypto_bitbox02_BIP85Request_AppLn_fields &shiftcrypto_bitbox02_BIP85Request_AppLn_msg
#define shiftcrypto_bitbox02_BIP85Response_fields &shiftcrypto_bitbox02_BIP85Response_msg

/* Maximum encoded size of messages (where known) */
/* shiftcrypto_bitbox02_ElectrumEncryptionKeyRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_ElectrumEncryptionKeyResponse_size depends on runtime parameters */
/* shiftcrypto_bitbox02_BIP85Response_size depends on runtime parameters */
#define SHIFTCRYPTO_BITBOX02_KEYSTORE_PB_H_MAX_SIZE shiftcrypto_bitbox02_BIP85Request_size
#define shiftcrypto_bitbox02_BIP85Request_AppLn_size 6
#define shiftcrypto_bitbox02_BIP85Request_size   8

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
