/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SHIFTCRYPTO_BITBOX02_MNEMONIC_PB_H_INCLUDED
#define PB_SHIFTCRYPTO_BITBOX02_MNEMONIC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _shiftcrypto_bitbox02_ShowMnemonicRequest {
    char dummy_field;
} shiftcrypto_bitbox02_ShowMnemonicRequest;

typedef struct _shiftcrypto_bitbox02_RestoreFromMnemonicRequest {
    uint32_t timestamp;
    int32_t timezone_offset;
} shiftcrypto_bitbox02_RestoreFromMnemonicRequest;

typedef struct _shiftcrypto_bitbox02_SetMnemonicPassphraseEnabledRequest {
    bool enabled;
} shiftcrypto_bitbox02_SetMnemonicPassphraseEnabledRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define shiftcrypto_bitbox02_ShowMnemonicRequest_init_default {0}
#define shiftcrypto_bitbox02_RestoreFromMnemonicRequest_init_default {0, 0}
#define shiftcrypto_bitbox02_SetMnemonicPassphraseEnabledRequest_init_default {0}
#define shiftcrypto_bitbox02_ShowMnemonicRequest_init_zero {0}
#define shiftcrypto_bitbox02_RestoreFromMnemonicRequest_init_zero {0, 0}
#define shiftcrypto_bitbox02_SetMnemonicPassphraseEnabledRequest_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define shiftcrypto_bitbox02_RestoreFromMnemonicRequest_timestamp_tag 1
#define shiftcrypto_bitbox02_RestoreFromMnemonicRequest_timezone_offset_tag 2
#define shiftcrypto_bitbox02_SetMnemonicPassphraseEnabledRequest_enabled_tag 1

/* Struct field encoding specification for nanopb */
#define shiftcrypto_bitbox02_ShowMnemonicRequest_FIELDLIST(X, a) \

#define shiftcrypto_bitbox02_ShowMnemonicRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_ShowMnemonicRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_RestoreFromMnemonicRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         1) \
X(a, STATIC,   SINGULAR, INT32,    timezone_offset,   2)
#define shiftcrypto_bitbox02_RestoreFromMnemonicRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_RestoreFromMnemonicRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_SetMnemonicPassphraseEnabledRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1)
#define shiftcrypto_bitbox02_SetMnemonicPassphraseEnabledRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_SetMnemonicPassphraseEnabledRequest_DEFAULT NULL

extern const pb_msgdesc_t shiftcrypto_bitbox02_ShowMnemonicRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_RestoreFromMnemonicRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_SetMnemonicPassphraseEnabledRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define shiftcrypto_bitbox02_ShowMnemonicRequest_fields &shiftcrypto_bitbox02_ShowMnemonicRequest_msg
#define shiftcrypto_bitbox02_RestoreFromMnemonicRequest_fields &shiftcrypto_bitbox02_RestoreFromMnemonicRequest_msg
#define shiftcrypto_bitbox02_SetMnemonicPassphraseEnabledRequest_fields &shiftcrypto_bitbox02_SetMnemonicPassphraseEnabledRequest_msg

/* Maximum encoded size of messages (where known) */
#define SHIFTCRYPTO_BITBOX02_MNEMONIC_PB_H_MAX_SIZE shiftcrypto_bitbox02_RestoreFromMnemonicRequest_size
#define shiftcrypto_bitbox02_RestoreFromMnemonicRequest_size 17
#define shiftcrypto_bitbox02_SetMnemonicPassphraseEnabledRequest_size 2
#define shiftcrypto_bitbox02_ShowMnemonicRequest_size 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
