/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "mnemonic.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(shiftcrypto_bitbox02_ShowMnemonicRequest, shiftcrypto_bitbox02_ShowMnemonicRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_RestoreFromMnemonicRequest, shiftcrypto_bitbox02_RestoreFromMnemonicRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_SetMnemonicPassphraseEnabledRequest, shiftcrypto_bitbox02_SetMnemonicPassphraseEnabledRequest, AUTO)



