/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "perform_attestation.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(shiftcrypto_bitbox02_PerformAttestationRequest, shiftcrypto_bitbox02_PerformAttestationRequest, AUTO)


PB_BIND(shiftcrypto_bitbox02_PerformAttestationResponse, shiftcrypto_bitbox02_PerformAttestationResponse, AUTO)



