/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SHIFTCRYPTO_BITBOX02_PERFORM_ATTESTATION_PB_H_INCLUDED
#define PB_SHIFTCRYPTO_BITBOX02_PERFORM_ATTESTATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Deprecated, last used in v1.0.0 */
typedef struct _shiftcrypto_bitbox02_PerformAttestationRequest {
    /* 32 bytes challenge. */
    pb_callback_t challenge;
} shiftcrypto_bitbox02_PerformAttestationRequest;

/* Deprecated, last used in v1.0.0 */
typedef struct _shiftcrypto_bitbox02_PerformAttestationResponse {
    pb_callback_t bootloader_hash;
    pb_callback_t device_pubkey;
    pb_callback_t certificate;
    pb_callback_t root_pubkey_identifier;
    pb_callback_t challenge_signature;
} shiftcrypto_bitbox02_PerformAttestationResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define shiftcrypto_bitbox02_PerformAttestationRequest_init_default {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_PerformAttestationResponse_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define shiftcrypto_bitbox02_PerformAttestationRequest_init_zero {{{NULL}, NULL}}
#define shiftcrypto_bitbox02_PerformAttestationResponse_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define shiftcrypto_bitbox02_PerformAttestationRequest_challenge_tag 1
#define shiftcrypto_bitbox02_PerformAttestationResponse_bootloader_hash_tag 1
#define shiftcrypto_bitbox02_PerformAttestationResponse_device_pubkey_tag 2
#define shiftcrypto_bitbox02_PerformAttestationResponse_certificate_tag 3
#define shiftcrypto_bitbox02_PerformAttestationResponse_root_pubkey_identifier_tag 4
#define shiftcrypto_bitbox02_PerformAttestationResponse_challenge_signature_tag 5

/* Struct field encoding specification for nanopb */
#define shiftcrypto_bitbox02_PerformAttestationRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    challenge,         1)
#define shiftcrypto_bitbox02_PerformAttestationRequest_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_PerformAttestationRequest_DEFAULT NULL

#define shiftcrypto_bitbox02_PerformAttestationResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    bootloader_hash,   1) \
X(a, CALLBACK, SINGULAR, BYTES,    device_pubkey,     2) \
X(a, CALLBACK, SINGULAR, BYTES,    certificate,       3) \
X(a, CALLBACK, SINGULAR, BYTES,    root_pubkey_identifier,   4) \
X(a, CALLBACK, SINGULAR, BYTES,    challenge_signature,   5)
#define shiftcrypto_bitbox02_PerformAttestationResponse_CALLBACK pb_default_field_callback
#define shiftcrypto_bitbox02_PerformAttestationResponse_DEFAULT NULL

extern const pb_msgdesc_t shiftcrypto_bitbox02_PerformAttestationRequest_msg;
extern const pb_msgdesc_t shiftcrypto_bitbox02_PerformAttestationResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define shiftcrypto_bitbox02_PerformAttestationRequest_fields &shiftcrypto_bitbox02_PerformAttestationRequest_msg
#define shiftcrypto_bitbox02_PerformAttestationResponse_fields &shiftcrypto_bitbox02_PerformAttestationResponse_msg

/* Maximum encoded size of messages (where known) */
/* shiftcrypto_bitbox02_PerformAttestationRequest_size depends on runtime parameters */
/* shiftcrypto_bitbox02_PerformAttestationResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
