/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SHIFTCRYPTO_BITBOX02_SYSTEM_PB_H_INCLUDED
#define PB_SHIFTCRYPTO_BITBOX02_SYSTEM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _shiftcrypto_bitbox02_RebootRequest_Purpose {
    shiftcrypto_bitbox02_RebootRequest_Purpose_UPGRADE = 0,
    shiftcrypto_bitbox02_RebootRequest_Purpose_SETTINGS = 1
} shiftcrypto_bitbox02_RebootRequest_Purpose;

/* Struct definitions */
typedef struct _shiftcrypto_bitbox02_RebootRequest {
    shiftcrypto_bitbox02_RebootRequest_Purpose purpose;
} shiftcrypto_bitbox02_RebootRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _shiftcrypto_bitbox02_RebootRequest_Purpose_MIN shiftcrypto_bitbox02_RebootRequest_Purpose_UPGRADE
#define _shiftcrypto_bitbox02_RebootRequest_Purpose_MAX shiftcrypto_bitbox02_RebootRequest_Purpose_SETTINGS
#define _shiftcrypto_bitbox02_RebootRequest_Purpose_ARRAYSIZE ((shiftcrypto_bitbox02_RebootRequest_Purpose)(shiftcrypto_bitbox02_RebootRequest_Purpose_SETTINGS+1))

#define shiftcrypto_bitbox02_RebootRequest_purpose_ENUMTYPE shiftcrypto_bitbox02_RebootRequest_Purpose


/* Initializer values for message structs */
#define shiftcrypto_bitbox02_RebootRequest_init_default {_shiftcrypto_bitbox02_RebootRequest_Purpose_MIN}
#define shiftcrypto_bitbox02_RebootRequest_init_zero {_shiftcrypto_bitbox02_RebootRequest_Purpose_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define shiftcrypto_bitbox02_RebootRequest_purpose_tag 1

/* Struct field encoding specification for nanopb */
#define shiftcrypto_bitbox02_RebootRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    purpose,           1)
#define shiftcrypto_bitbox02_RebootRequest_CALLBACK NULL
#define shiftcrypto_bitbox02_RebootRequest_DEFAULT NULL

extern const pb_msgdesc_t shiftcrypto_bitbox02_RebootRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define shiftcrypto_bitbox02_RebootRequest_fields &shiftcrypto_bitbox02_RebootRequest_msg

/* Maximum encoded size of messages (where known) */
#define SHIFTCRYPTO_BITBOX02_SYSTEM_PB_H_MAX_SIZE shiftcrypto_bitbox02_RebootRequest_size
#define shiftcrypto_bitbox02_RebootRequest_size  2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
